### ISSUE TITLE
exceptions defined in a securitySchema don't propagate to secured methods

### ISSUE THREAD

**Issue by norbertpotocki** [mulesoft/api-console#101]
When I define exceptions in a securitySchema they should be reflected in a documentation of a secured method. Unfortunately they're not.

```
securitySchemes:
  - oauth: 
....
  responses:
      401:
        description: |
          Bad or expired token.
      403:
        description: |
          Bad OAuth request.
....

securedBy: [oauth]

/test:
  get:
```

For this example the list of responses should contain codes 401 and 403. However it's empty.

**Comment by sichvoge** [comment]
I can confirm that behaviour; take the following example:

```yaml
#%RAML 0.8
title: Gello
securitySchemes:
  - oauth:
      type: OAuth 2.0
      describedBy: 
        responses:
          401:
            description: |
              Bad or expired token.
          403:
            description: |
              Bad OAuth request.

securedBy: [oauth]

/test:
  get:
/test1:
  get:
    responses:
      401:
        description: |
          Bad or expired token.
      403:
        description: |
          Bad OAuth request.
```

In test, you see:

![image](https://cloud.githubusercontent.com/assets/498114/19037381/dc79ef58-896d-11e6-8a8e-a8811380e4c9.png)

In test1, you see:

![image](https://cloud.githubusercontent.com/assets/498114/19037418/0f165604-896e-11e6-8a3d-217920fe8b58.png)

That might be a parser issue, not correctly nomalizing / expanding the necessary information. Need further investigation.

**Comment by carobazan** [comment]
verified in QA branch, will be included in next release
