### ISSUE TITLE
The console enforces both Username and Password for Basic Auth

### ISSUE THREAD

**Issue by ddossot** [mulesoft/api-console#107]
Some APIs use only the username field and leave the password field empty, which is legal as far as Basic Auth is concerned.

Unfortunately, the console enforces that both Username and Password must be filled for Basic Auth.

I think this should be relaxed and only enforce that at least one of the two field be filled.

**Comment by usarid** [comment]
In the new console that's just about to be released, the general rule about validation is that it tells you something is invalid but doesn't forbid you from submitting it anyway (except perhaps for missing uriParameters where it may not make syntactical sense to omit them). Not sure whether this general rule also applies to username/password for basic auth... @jcenturion and @dmartinezg  ?

**Comment by jcenturion** [comment]
@usarid:

The new console allows you to omit username or password for basic auth. But you have to use ***Force GET***.

![screen shot 2015-02-12 at 7 34 46 pm](https://cloud.githubusercontent.com/assets/302314/6178533/a8ddf7cc-b2ee-11e4-9c88-490496d72dcc.png)

**Comment by usarid** [comment]
Well *I* love it... David, whaddya think?

**Comment by ddossot** [comment]
I just pulled the latest version and `Force GET` works great, I'm happy with it too :smile:

**Comment by ddossot** [comment]
I'm reopening because I was wrong, it doesn't work.

If I B64 decode the Auth header the console have created I see this: `userid:undefined`

It should actually be `userid:`, the `undefined` part is too much.

**Comment by usarid** [comment]
OK thanks!

Uri

**Comment by jcenturion** [comment]
Fixed at [commit](http://goo.gl/kk1Aws). Closing issue.
