### ISSUE TITLE
Tabs (verbs) do not correspond with "Try it" forms

### ISSUE THREAD

**Issue by pacohernandezg** [mulesoft/api-console#109]
When clicking on "Put" tab, "Delete" form appears. Clicking on "Get" tab, "Put" form appears, ...

![screen shot 2015-02-24 at 08 50 00](https://cloud.githubusercontent.com/assets/2727545/6345172/f05d4932-bc02-11e4-8a64-6bf7f5e54ff1.png)

Thank you. ;-)

**Comment by dmartinezg** [comment]
Hi @pacohernandezg, thanks for catching this one, we'll fix it right away

**Comment by jcenturion** [comment]
Fixed

**Comment by pacohernandezg** [comment]
Impressive, thank you very much ;-)
