### ISSUE TITLE
Overlay between the HTTP methods and resource name

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#112]
Using chrome I get an overlay between the HTTP methods and resource name. (see image below)

![screen shot 2015-03-02 at 11 24 53](https://cloud.githubusercontent.com/assets/498114/6439855/14643ee6-c0cf-11e4-85e2-d88015612502.png)

**Comment by jcenturion** [comment]
Thanks for feedback. I will take a look.

**Comment by sichvoge** [comment]
duplicate for https://github.com/mulesoft/api-console/issues/161
