### ISSUE TITLE
Making the APIs live

### ISSUE THREAD

**Issue by shravanak** [mulesoft/api-console#114]
How do we make the APIs actually hit the end point and display the response when you click try-it. I m not sure if this documentation is clear on how to do this.
Can someone please help with this?

**Comment by ddossot** [comment]
You need to have the `baseUri` property set to the target API in your RAML config.

**Comment by shravanak** [comment]
I do have it set. When I hit the get button, it does nothing. The response is blank. The request it generates is valid. But just the response is blank.

**Comment by shravanak** [comment]
Here is the example contents from my raml

title: API Documentation
#version: v1
baseUri: http://{apiDomain}:4080/analytics/{ver}
baseUriParameters:
  ver:
    description: |
      The version of the API
    enum: ["v1"]
  apiDomain:
      description: |
        The version of the API
      enum: ["validurlishere"]
/resource:
    /aggregate/contents:
        baseUriParameters:
          ver:
            enum: ["v2"]
        get:
        description: |
          Returns metrics

**Comment by ddossot** [comment]
You need to replace `{apiDomain}` with a value.

**Comment by shravanak** [comment]
![screen shot 2015-03-05 at 1 47 54 pm](https://cloud.githubusercontent.com/assets/5891885/6515483/f491c3aa-c33e-11e4-9bfa-785ebf485171.png)

So the request it constructs has the apiDomain and is valid because when i copy it and paste it on the browser I get a response. Why don's I see it in the response field. Hope this is clear. Might be missing a setting somewhere.

**Comment by ddossot** [comment]
Maybe a CORS issue? What does the browser console say?

**Comment by shravanak** [comment]
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://0.0.0.0:9000' is therefore not allowed access.

**Comment by ddossot** [comment]
Excellent, you've found the issue! It's indeed a CORS problem: you need to configure the remote API to support your domain in its CORS policy. If not possible, you need to serve the API console from the same domain as the API itself.

**Comment by shravanak** [comment]
Any idea how to fix this issue? Not really familiar with CORS.

**Comment by ddossot** [comment]
Some resources on CORS:
- http://www.html5rocks.com/en/tutorials/cors/
- http://enable-cors.org/server.html

**Comment by shravanak** [comment]
Sorry for the late reply. But is it possible to add more instructions to setup the proxy to overcome CORS issue?

**Comment by sichvoge** [comment]
I believe thats being done already. See [here](https://github.com/mulesoft/api-console#proxying). In v4, we also have a complete chapter dedicated to CORS.
