### ISSUE TITLE
Issue - API Console 2.0 in ApiDesigner in Anypoint portal

### ISSUE THREAD

**Issue by beeva-luisgonzalez** [mulesoft/api-console#120]
Hi guys,

we have found that if you define headers name with dots (., in example "my.header-X"), the API Console allows you to input the value for that header, but when using the mocker the service wont recognize them the value which is sent. 

I debugged the call via the chrome developer console and the problem seems on the mocker/proxy service deployed on your production environments.

Its a bit urgent for us, as we were defining some APIs on the API Designer on mulesoft, and those APIs are already built and in production.

**Comment by sichvoge** [comment]
hmhmmm the mocking service is working with these type of headers. closing that, but if the problem still exists we can open it again or create a new.
