### ISSUE TITLE
Console endpoint explorer is too short on low-number endpoint documents

### ISSUE THREAD

**Issue by everyplace** [mulesoft/api-console#127]
As per the issue described in [Osprey's repo](https://github.com/mulesoft/osprey/pull/36), if there are only a few endpoints in a RAML document, the height of the response and example window is limited to the height of the initial list of endpoints.

Specifically in the DOM, the div.resource-container's height is set with an inline attribute, calculated and set when switching from viewing the endpoint list to exploring a specific endpoint, which in turn is determined by how many endpoints exist in the console landing page.

The expected behavior is that the min-height on the div.resource-container should be at least 500px always, but there isn't any reason in my mind why it shouldn't be the height of the window at a minimum. While this can be overridden easily in the css (for example, adding `min-height:500px !important` to a relevant selector), since the height is set by the angular app, I'd assume it would be better to resolve it there.

![screen shot 2015-03-20 at 5 09 28 pm](https://cloud.githubusercontent.com/assets/95356/6760924/02f2e10e-cf24-11e4-8a21-55ecd5349bed.png)

**Comment by jcenturion** [comment]
@everyplace: that's an old version of the console. I think the new version of Osprey will be released with the latest version of the console.

**Comment by everyplace** [comment]
@jcenturion I've seen screenshots of the new console, but don't think I'm aware of the timing of its release. Any ideas?

**Comment by usarid** [comment]
@blakeembrey perhaps you can comment?






On Sat, Mar 21, 2015 at 12:39 PM -0700, "Erin Sparling" <notifications@github.com> wrote:












@jcenturion I've seen screenshots of the new console, but don't think I'm aware of the timing of its release. Any ideas?

**Comment by everyplace** [comment]
We forked this locally and made the change in our internal copy of this code, so this isn't a mission-critical bug. But I do see that in the current public version of osprey, you're running 0.2.0-alpha, with the console app disabled. Any timeframe we could know when we should be migrating to 0.2.0 would be great.

**Comment by blakeembrey** [comment]
@jcenturion Is the new API console available for use? What's the upgrade path from the first version? We can patch Osprey 0.1 with the console version. Is this distributed on NPM or how should I package it within Osprey?

**Comment by jcenturion** [comment]
@blakeembrey: [https://github.com/mulesoft/api-console/releases/tag/2.0.0]()

**Comment by everyplace** [comment]
Thanks for the 2.0 release. I've tried it out locally, and its definitely a lot better. Next step is to get it running with the 0.2.0-alpha parser.
