### ISSUE TITLE
custom securitySchemes headers don't appear under 'Try it' section

### ISSUE THREAD

**Issue by thenrikie** [mulesoft/api-console#129]
I have a custom security scheme defined with some required headers. Unfortunately they don't appear under the Try it > Headers section. It would be great if it work as the same way as traits. For traits if I defined some required headers, the headers will appear under Try it > Headers section if the api belongs to that trait.

**Comment by jcenturion** [comment]
@thenrikie: Have you tried the [latest version](https://github.com/mulesoft/api-console/releases/tag/2.0.0)? Could you please post an extract of your RAML to test it?

Thanks.

**Comment by thenrikie** [comment]
@jcenturion Yes. I downloaded the lastest version and did a grunt and tried, I cannot see the header required under try it. This is the example raml I tried

```
#%RAML 0.8
title: My API
version: v1.0
baseUri: /
securitySchemes:
  - x-custom:
      type: x-custom
      description: Custom API Authentication
      describedBy:
        headers:
          X-custom-key:
            required: true
            type: string
        responses:
          401:
            description: |
              Bad or expired token

/example-api:
  get:
    securedBy: [x-custom]
```

**Comment by jcenturion** [comment]
@thenrikie: It's already fix on the [latest commit](https://github.com/mulesoft/api-console).

Thanks four your feedback.

![screen shot 2015-04-02 at 2 30 04 pm](https://cloud.githubusercontent.com/assets/302314/6969471/465ecdba-d945-11e4-8f7a-3ae7cc2ef295.png)

**Comment by thenrikie** [comment]
thx a lot. It works!
