### ISSUE TITLE
Raml Console 

### ISSUE THREAD

**Issue by mpindyala** [mulesoft/api-console#131]
How do I present console documentation and resources in collapsed state instead of expanded on first time load within browser ?

**Comment by jcenturion** [comment]
@mpindyala:

You have to use `<raml-console src="path-to-raml" resourcesCollapsed documentationCollapsed></raml-console>`

**Comment by mpindyala** [comment]
how do I do it if using it as standalone page ?

**Comment by jcenturion** [comment]
@mpindyala:

There is no way to use such options when feeding from queryString :(. I'm thinking about to provide a way to support such settings from queryString. I'll let you know.

**Comment by mpindyala** [comment]
Any update on the possible solution for collapse ?

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
