### ISSUE TITLE
Directory of APIs using more than one RAML file

### ISSUE THREAD

**Issue by MMore** [mulesoft/api-console#132]
Hi there,

well, this is more a general question. Off course, we have more than one service that provides its own RAML file.

Currently we have a simple list of links in the form of this
- http://api_console.example.com/index.html?raml=awesome_service/service.raml
- http://api_console.example.com/index.html?raml=another_awesome_service/service.raml

Is there already a solution to generate a kind of "directory" of APIs?

**Comment by sichvoge** [comment]
I think this is related to #140. So let's continue discussing it there. I am closing this issue.
