### ISSUE TITLE
A POST API that is secured by OAuth2.0 doesn't POST request body

### ISSUE THREAD

**Issue by takearun** [mulesoft/api-console#133]
Hi,

In my RAML I have a POST API that is secured by OAuth 2.0. The actual OAuth dance works fine but the subsequent request doesn't POST the request payload. If I don't use OAuth2.0 then the request payload is getting sent but of course my API Gateway throws a 401.

Can you please help.

Thanks,
Arun

**Comment by jcenturion** [comment]
Fix it's already on `master`.
