### ISSUE TITLE
Console does not support `repeat`

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#138]
Hi guys,

in RAML you can specify query parameters to be repeatable. Unfortunately the console is not supporting it right now.

![image](https://cloud.githubusercontent.com/assets/498114/7890202/4b0d8820-05f9-11e5-9676-9a22beafac7c.png)

**Comment by jcenturion** [comment]
@sichvoge: This one is related to https://github.com/mulesoft/api-console/issues/81.

**Comment by sichvoge** [comment]
Since its related to another issue. I'll close this.
