### ISSUE TITLE
raml-console attributes not working

### ISSUE THREAD

**Issue by ejwood79** [mulesoft/api-console#139]
In my html file that hosts the console, I'd like to enable several of the options to shut off theme switching, etc, but they don't seem to be working. Can someone check my syntax to make sure I have this right?

`<raml-console src="doc/service.raml" single-view disable-theme-switcher disable-raml-client-generator></raml-console>`

If I have it right, what else could be causing this? The theme switcher and client generator are still displayed, and I can't tell if `single-view` is doing anything.

**Comment by WimVanDerZijden** [comment]
Yeah this works for me. You'll probably need to post more of your code to find out what the problem is.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
