### ISSUE TITLE
Support drop down menu in RAML console

### ISSUE THREAD

**Issue by dkirrane** [mulesoft/api-console#140]
It would be nice if `<raml-initializer>` or `<raml-console>` supported a list of raml urls.

The user could then switch between different raml APIs from within a single raml console window.

Something like a select tag would be good.

```
<select>
  <option value="http://localhost/apiOne.raml">One API</option>
  <option value="http://localhost/apiTwo.raml">Two API</option>
  <option value="http://localhost/apiThree.raml">Three API</option>
</select>
```

**Comment by jarrodek** [comment]
The API console as a HTML element allows you to do this.

You can create a custom build of the console and programatically add such list (it would also require from you to use parser and enhancer to actually load and parse the content).

Other options is to use the `nav` attribute of a child of the `<api-console>` element. Elements with such attribute will be places in top main navigation. It could be an `<select>` list or whatever you feel fit.

I'm preparing an example of the API Console with such selector so I'll reference it later this month.
