### ISSUE TITLE
Expand documentation headers on load.

### ISSUE THREAD

**Issue by WimVanDerZijden** [mulesoft/api-console#150]
It would be nice to have a directive to completely expand the documentation on load. The default is now that it only expands the root, so you only see the headers, not their content.

I think it's not entirely clear that you can click on those headers to expand them, that's why for my api I actually called my only header "Click here for more info".

**Comment by jcenturion** [comment]
@WimVanDerZijden: You're right. I can add an option to the directive, something like `documenation-expanded`.

**Comment by sichvoge** [comment]
That should be much better in v4 now!

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
