### ISSUE TITLE
Stuck on loading page when error occurs loading raml

### ISSUE THREAD

**Issue by gingermusketeer** [mulesoft/api-console#152]
When the raml is not available (404 returned etc) or the raml is invalid the console gets stuck on the loading page

**Comment by jcenturion** [comment]
@gingermusketeer: Are you loading the RAML through queryParams or through the initialize page?

**Comment by nmarinel01** [comment]
Hi @gingermusketeer ,
are you still experiencing the problem ? Can you share the usage scenario to reproduce the issue?
Regardas

**Comment by gingermusketeer** [comment]
@nmarinel01 I am using an old version of the RAML console at the moment. Hoping to upgrade when I get a moment but not sure that will be anytime soon. Feel free to close this. Can open a new issue if it is still occurring!

**Comment by nmarinel01** [comment]
@gingermusketeer thanks for your feedback. Please, open a new report if the issue is still there.
Regards
