### ISSUE TITLE
Distribution files are not able to be minified

### ISSUE THREAD

**Issue by gingermusketeer** [mulesoft/api-console#153]
I am working on an integration for this with rails and i have just run into an issue with minification of the distribution source files. When i try to minify the files i get an error from angular about an unknown provider.

I was looking at using https://github.com/olov/ng-annotate to achieve this but i have run into issues with the structure of the angular components. Because there is a separation between the function which defines the component and the registration with angular the annotations do not work.

Is this something you have run into?

**Comment by jaime-olivares** [comment]
This may be relate to #169

**Comment by agustinlg** [comment]
Closed with #169
