### ISSUE TITLE
HTTP methods overlap with resource name - space is expensive

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#161]
![image](https://cloud.githubusercontent.com/assets/498114/9276013/4308420a-4299-11e5-93a6-7c57d5d41a60.png)

As you can see in the imagine above the HTTP methods easily overlap with the resource name when they are getting larger. It would be good to maybe not have them on the same line, maybe that could be a table with two rows one column using the first for the resource name and the second for the http methods. 

I would also argue if we need to show all traits/resource types next to the resource name. If we have multiple traits, that can get messy as well. Maybe just one box next to it that has a hover effect and list all applied traits as a "tooltip". Therefore you only have a single traits button.

I am using Chrome on my Mac OSX with the latest version of the console on Anypoint Platform.

**Comment by nmarinel01** [comment]
Hi @sichvoge,
this seems to be fixed using latest release. Can you verify and reopen if applies ?
Regards !
