### ISSUE TITLE
global definitions in RAML needs be resolved in the console

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#162]
Currently global definitions of, for example, schemas are not getting resolved in the API Console for a specific resource. Instead only the name is displayed. See an example below:

![image](https://cloud.githubusercontent.com/assets/498114/9276313/fc394462-429a-11e5-9278-94d25d0d0194.png)

API Console Version: current version deployed to Anypoint Platform
Browser: Chrome
OS: Mac OSX

**Comment by dmartinezg** [comment]
Can you share the RAML? that looks as if the schema named `application` does not exist.

**Comment by sichvoge** [comment]
Don't have the RAML as it is our API Platform API

https://anypoint.mulesoft.com/apiplatform/anypoint-platform#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/11197/versions/31447/pages/44834

**Comment by dmartinezg** [comment]
Then it is a missing schema, not a console issue @sichvoge

**Comment by sichvoge** [comment]
I see. Thanks Damian. I'll checked others and some are missing, some are working. Closing that and take it offline with you.
