### ISSUE TITLE
Pattern validation in API Console correct?

### ISSUE THREAD

**Issue by meeque** [mulesoft/api-console#163]
Not sure whether this is a bug, or whether I'm just understanding the RAML spec wrongly. However, the validation of string values that have a `pattern` property does not work quite the way I would expect. 

Naively, I would assume that the whole input value of a parameter must match the specified `pattern`. Instead, the API Console also accepts the input, if just a part of it matches the `pattern`. 

For example, I have this pattern: 
`[a-z][a-z0-9]+`

As expected, the following input value **does not** validate against it:
`INVALID`

However, contrary to my personal expectation, the following **does** validate successfully:
`INVALIDvalidpart`

... apperently, because parts of the input validate. 
(In this example, such valid parts would be `va`, `val`, `vali`, ..., `validpart`.)

Is this behavior intended, or is it a bug? 

I've asked a similar question some while ago in the RAML forums: 
http://forums.raml.org/t/anchoring-in-patterns-of-string-parameters/940

Unfortunately no answer yet. So it's hard to tell whether the current behavior is a bug in the API Console, are a flaw in the RAML specification:(

**Comment by meeque** [comment]
Here's screenshots of the API Console, validating the above examples. First the expected case:
![raml api console - regexp pattern validation 1](https://cloud.githubusercontent.com/assets/901490/9279067/36212900-42b5-11e5-8a11-61ba176a682b.png)
And here the unexpected case:
![raml api console - regexp pattern validation 2](https://cloud.githubusercontent.com/assets/901490/9279066/361fb6a6-42b5-11e5-8bd1-e7dd9ff3f169.png)

**Comment by blakeembrey** [comment]
@meeque All the tooling, including the API console, that I've work with uses the pattern directly as the RegExp - so yes, you need to anchor it with `^[a-z][a-z0-9]+$`.

**Comment by meeque** [comment]
@blakeembrey First of all, thanks for the lightning-fast reply:D 

Also, thanks for clarification that there is consensus about anchoring of RegExp patterns. Coming to think about it, it makes sense. The 0.8 spec does say that it is based on the RegExp specification from JavaScript. And that one only provides one way to match a RegExp: using the `test` function of RegExp itself or the `match` function of String, which can be used interchangeably.

I guess my confusion stems from the fact that some regular-expressions libraries handle that differently. For example, in the standard implementation for java, you can use a pattern directly in both ways. The following is similar to the JavaScript way, and thus returns `true`:

    Pattern.compile("[a-z][a-z0-9]+").matcher("INVALIDvalidpart").find();

In contrast, the following equivalent notations, check whether the whole input matches, and thus all return `false`:

    Pattern.compile("[a-z][a-z0-9]+").matcher("INVALIDvalidpart").matches();
    Pattern.matches("[a-z][a-z0-9]+", "INVALIDvalidpart");
    "INVALIDvalidpart".matches("[a-z][a-z0-9]+");

Being more familiar with Java than JS, the term "match" in the RAML spec got me confused.

**Comment by meeque** [comment]
So I'm closing this now -- no need for action on the API Console end.

I still believe, that the wording in the RAML 0.8 spec is in the least confusing. Maybe you guys could improve that in future versions?
