### ISSUE TITLE
Response schema not linked

### ISSUE THREAD

**Issue by ddossot** [mulesoft/api-console#164]
In this [RAML definition](https://api.unbounce.com/raml/v0.4/api.raml), the `pagedCollection` resource type specifies:

      post?:
        is: [versioned]
        responses:
          201:
            headers:
              Location:
                type: string
                required: true
            body:
              schema: <<resourcePathName | !singularize>>

This is used here:

    /leads:
      is: [subCollection]
      type: pagedCollection
      get:
      post:
        body:
          schema: new_lead
          example: |
            {
                "conversion": true,
                "visitor_id": "127.0.0.123543254378923893",
                "form_submission": {
                    "variant_id": "a",
                    "submitter_ip": "127.0.0.1",
                    "form_data": {
                        "first_name": "John",
                        "last_name": "Doe",
                        "email": "jqdoe@unbounce.com"
                    }
                }
            }

Unfortunately, the schema is not linked in the RAML Console for this resource method:

![screenshot from 2015-08-17 14 23 05](https://cloud.githubusercontent.com/assets/119028/9316705/8c276ff2-44eb-11e5-89dc-48d56c795262.png)

As you can see the `Location` header has been correctly rendered. And `schema: <<resourcePathName | !singularize>>` works perfectly fine in other sections of our API: the schema gets correctly embedded in the console. It's just this resource that fails, maybe because of the `?` in `post?` ?

**Comment by sichvoge** [comment]
It seems that might have been a problem with the parser, but its working for me now. Please let me know if that isn't true. I am closing that issue for now.
