### ISSUE TITLE
Release the dist directory on NPM

### ISSUE THREAD

**Issue by colthreepv** [mulesoft/api-console#165]
Hello, would be very useful for many users such a package.

Install from git is quirky, and does not see new releases.... moreover https://www.npmjs.com/package/api-console is free :+1:

**Comment by sichvoge** [comment]
Agree :+1: It is on our list! Thanks!

**Comment by jcenturion** [comment]
@sichvoge, @colthreepv, I've already published [API-Console](https://www.npmjs.com/package/api-console) on NPM ;)

**Comment by sichvoge** [comment]
Great!!! - closing that.

**Comment by colthreepv** [comment]
thanks a lot!
