### ISSUE TITLE
Documentation rendering doesn't follow Markdown newline convention

### ISSUE THREAD

**Issue by ddossot** [mulesoft/api-console#167]
I've updated to the latest version of the console, and now the documentation looks like this:

![screenshot from 2015-08-18 10 06 00](https://cloud.githubusercontent.com/assets/119028/9336871/bd38b18c-4590-11e5-9c2b-185e88a13519.png)

The newlines in the source RAML documentation section have been carried on as-is instead of being ignored as they are in Markdown (per the RAML spec, documentation are written in Markdown and thus should be interpreted and rendered using this convention).

**Comment by sichvoge** [comment]
@jcenturion anything that has been changed lately would be responsible for that?

**Comment by jcenturion** [comment]
@sichvoge: we have changed the configuration of [Marked](https://github.com/chjj/marked) to use breaks as-is. This was requested for a couple of users on the issues.

**Comment by sichvoge** [comment]
@ddossot does this help?

**Comment by ngoossens** [comment]
This can be configured in a similar way to the Proxying and OAuth 2 settings, after the console JavaScript has been loaded.

```
RAML.Settings.marked.breaks = false
```

Maybe this could be added to the readme?

**Comment by sichvoge** [comment]
Agree, we can update README.
