### ISSUE TITLE
Non required params are mandatory in the console

### ISSUE THREAD

**Issue by beeva-alejandrogines** [mulesoft/api-console#168]
I have ingested a RAML which has some required params, but some are not. When using the Try-it feature, the console is demanding that I need to populate the non required params and I end using the "Force GET" feature.

Kind regards,

Alex

**Comment by jcenturion** [comment]
@beeva-alejandrogines: Could you please send me an example of the RAML that you're using?

Thanks in advance.

**Comment by beeva-alejandrogines** [comment]
Sure @jcenturion , pasting it here

[code]#%RAML 0.8
title: APITest
version: "v2"
protocols:
  - HTTP
  - HTTPS
baseUri: "http://dummyurl.com"
mediaType:
  application/json
traits:
  - paging :
      queryParameters:
        _start:
          required: false
          displayName: _start
          description: Índice de comienzo de la paginación. El índice mínimo comienza en 0
          example: 1
          type: integer
        _end:
          required: false
          displayName: _end
          description: Índice de fin de la paginación
          example: 5
          type: integer
  - generalQuery :
      queryParameters:
        q :
          required: false
          displayName: q
          description: Busca el texto pasado como parámetro en todos los campos de primer nivel
          example: demarco.info
          maxLength: 255
          type: string
  - userParameters :
      body:
        application/x-www-form-urlencoded:
          formParameters:
            name:
              description: Nombre del usuario
              type: string
              example: Miguel García
              required: false
            username:
              description: Nombre del usuario en la aplicación
              type: string
              example: miguel.garcia
              required: false
            email:
              description: Correo del usuario
              type: string
              example: miguel.garcia@fakemail.com
              required: false
            phone:
              description: Teléfono del usuario
              type: string
              example: 600010203
              required: false
            website:
              description: Sitio web del usuario
              type: string
              example: testing.org
              required: false
  - albumParameters:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            userId:
              description: Identificador del usuario
              type: integer
              example: 1
              required: false
            title:
              description: Título del álbum
              type: string
              example: Álbum Familiar
              required: false
  - photoParameters:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            albumId:
              description: Identificador del álbum
              type: integer
              example: 1
              required: false
            title:
              description: Título de la foto
              type: string
              example: Foto Familiar
              required: false
            url:
              description: URL de la foto
              type: string
              example: http://placehold.it/600/92c952
              required: false
            thumbnailUrl:
              description: Thumbnail URL de la foto
              type: string
              example: http://placehold.it/150/30ac17
              required: false
  - postParameters:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            userId:
              description: Identificador del usuario que realiza el post
              type: integer
              example: 1
            title:
              description: Título del post
              type: string
              example: Primer post
              required: false
            body:
              description: Cuerpo del post
              type: string
              example: Este es un ejemplo de post
              required: false
  - commentParameters:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            postId:
              description: Identificador del post del que se quiere realizar un comentario
              type: integer
              example: 1
            name:
              description: Nombre de la persona que realiza el comentario
              type: string
              example: Miguel García
              required: false
            email:
              description: Correo de la persona que realiza el comentario
              type: string
              example: miguel.garcia@fakemail.com
              required: false
            body:
              description: Cuerpo del comentario
              type: string
              example: Este es un ejemplo de comentario
              required: false
  - todoParameters:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            userId:
              description: Identificador del usuario al que está asignada la tarea
              type: integer
              example: 1
            title:
              description: Título de la tarea
              type: string
              example: Borrar fotos borrosas
              required: false
            completed:
              description: Completada
              type: boolean
              example: true
              required: false
/users:
  get:
    description: Devuelve todos los usuarios de la aplicación
    is: [paging, generalQuery]
    responses:
      200:
        body:
          application/json:
            example: |
              [
                    {
                      "id": 1,
                      "name": "Leanne Graham",
                      "username": "Bret",
                      "email": "Sincere@april.biz",
                      "address": {
                        "street": "Kulas Light",
                        "suite": "Apt. 556",
                        "city": "Gwenborough",
                        "zipcode": "92998-3874",
                        "geo": {
                          "lat": "-37.3159",
                          "lng": "81.1496"
                        }
                      },
                      "phone": "1-770-736-8031 x56442",
                      "website": "hildegard.org",
                      "company": {
                        "name": "Romaguera-Crona",
                        "catchPhrase": "Multi-layered client-server neural-net",
                        "bs": "harness real-time e-markets"
                      }
                    },
                    {
                      "id": 2,
                      "name": "Ervin Howell",
                      "username": "Antonette",
                      "email": "Shanna@melissa.tv",
                      "address": {
                        "street": "Victor Plains",
                        "suite": "Suite 879",
                        "city": "Wisokyburgh",
                        "zipcode": "90566-7771",
                        "geo": {
                          "lat": "-43.9509",
                          "lng": "-34.4618"
                        }
                      },
                      "phone": "010-692-6593 x09125",
                      "website": "anastasia.net",
                      "company": {
                        "name": "Deckow-Crist",
                        "catchPhrase": "Proactive didactic contingency",
                        "bs": "synergize scalable supply-chains"
                      }
                    }
                  ]
      404:
              body:
                text/plain:
                  example: |
                    No encontrado
  post:
      description: Da de alta un nuevo usuario en la aplicación. Al tratarse de un API de prueba, el usuario no será dado de alta realmente.
      is: [userParameters]
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "name": "fakeName",
                  "username": "fakeUser",
                  "mail": "miguel.garcia",
                  "phone" : "600010203",
                  "website" : "testing.org",
                  "id": 11
                }
  /{id}:
    put:
      description: Modifica los datos del usuario en la aplicación. Al tratarse de un API de prueba, el usuario no será modificado realmante.
      is: [userParameters]
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "name": "fakeName",
                  "username": "fakeUser",
                  "mail": "miguel.garcia",
                  "phone" : "600010203",
                  "website" : "testing.org",
                  "id": 11
                }
    delete:
      description: Elimina el usuario de la aplicación. Al tratarse de un API de prueba, el usuario no será eliminado realmente.
      responses:
        204:
  /{id}/albums:
    get:
      description: Obtiene todos los álbumnes de un usuario
      is: [paging, generalQuery]
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "userId": 1,
                    "id": 1,
                    "title": "Álbum familiar"
                  },
                  {
                    "userId": 1,
                    "id": 2,
                    "title": "Álbum vacaciones Paris"
                  }
                ]
  /{id}/posts:
    get:
      description: Obtiene todos los posts de un usuario
      is: [paging, generalQuery]
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "userId": 1,
                    "id": 1,
                    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
                  },
                  {
                    "userId": 1,
                    "id": 2,
                    "title": "qui est esse",
                    "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
                  }
                ]
  /{id}/todos:
    get:
      description: Obtiene todas las tareas de un usuario
      is: [paging, generalQuery]
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "userId": 1,
                    "id": 1,
                    "title": "delectus aut autem",
                    "completed": false
                  },
                  {
                    "userId": 1,
                    "id": 2,
                    "title": "quis ut nam facilis et officia qui",
                    "completed": false
                  }
                ]
/albums:
  get:
    description: Devuelve todos los álbumnes de la aplicación
    is: [paging, generalQuery]
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                    "userId": 1,
                    "id": 1,
                    "title": "quidem molestiae enim"
                },
                {
                    "userId": 1,
                    "id": 2,
                    "title": "sunt qui excepturi placeat culpa"
                }
              ]
  post:
      description: Da de alta un nuevo álbum en la aplicación. Al tratarse de un API de prueba, el álbum no será dado de alta realmente.
      is: [albumParameters]
      responses:
        200:
          body:
            application/json:
              example: |
                {
                    "title": "Álbum Familar",
                    "userId": 1,
                    "id": 101
                }
  /{id}:
    put:
      description: Modifica los datos del álbum en la aplicación. Al tratarse de un API de prueba, el álbum no será modificado realmente.
      is: [albumParameters]
      responses:
        200:
          body:
            application/json:
              example: |
                {
                    "title": "Álbum Familar",
                    "userId": 1,
                    "id": 101
                }
    delete:
      description: Elimina el álbum de la aplicación. Al tratarse de un API de prueba, el álbum no será eliminado realmente.
      is: [albumParameters]
      responses:
        204:
  /{id}/photos:
    get:
      description: Obtiene todas las fotos de un álbum
      is: [paging, generalQuery]
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "albumId": 1,
                    "id": 1,
                    "title": "accusamus beatae ad facilis cum similique qui sunt",
                    "url": "http://placehold.it/600/92c952",
                    "thumbnailUrl": "http://placehold.it/150/30ac17"
                  },
                  {
                    "albumId": 1,
                    "id": 2,
                    "title": "reprehenderit est deserunt velit ipsam",
                    "url": "http://placehold.it/600/771796",
                    "thumbnailUrl": "http://placehold.it/150/dff9f6"
                  }
                ]
/photos:
    get:
      description: Devuelve todas las fotos de la aplicación.
      is: [paging, generalQuery]
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "albumId": 1,
                    "id": 1,
                    "title": "accusamus beatae ad facilis cum similique qui sunt",
                    "url": "http://placehold.it/600/92c952",
                    "thumbnailUrl": "http://placehold.it/150/30ac17"
                  },
                  {
                    "albumId": 1,
                    "id": 2,
                    "title": "reprehenderit est deserunt velit ipsam",
                    "url": "http://placehold.it/600/771796",
                    "thumbnailUrl": "http://placehold.it/150/dff9f6"
                  }
                ]
    post:
      description: Inserta una foto en la aplicación. Al tratarse de un API de prueba, la foto no será dada de alta realmente.
      is: [photoParameters]
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "albumId": 1,
                  "id": 5001,
                  "title": "Foto de prueba",
                  "url": "http://placehold.it/600/d32776",
                  "thumbnailUrl": "http://placehold.it/150/39e985"
                }
    /{id}:
      put:
        description: Modifica una foto en la aplicación. Al tratarse de un API de prueba, la foto no será modificada realmente.
        is: [photoParameters]
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "albumId": 1,
                    "id": 5001,
                    "title": "Foto de prueba",
                    "url": "http://placehold.it/600/d32776",
                    "thumbnailUrl": "http://placehold.it/150/39e985"
                  }
      delete:
        description: Elimina una foto de la aplicación. Al tratarse de un API de prueba, la foto no será eliminada realmente.
        is: [photoParameters]
        responses:
          204:
/posts:
    get:
      description: Devuelve todos los pots de la aplicación.
      is: [paging, generalQuery]
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "userId": 1,
                    "id": 1,
                    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
                  },
                  {
                    "userId": 1,
                    "id": 2,
                    "title": "qui est esse",
                    "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
                  }
                ]
    post:
      description: Inserta un nuevo post en la aplicación. Al tratarse de un API de prueba, el post no será dado de alta realmente.
      is: [postParameters]
      responses:
        200:
          body:
            application/json:
              example: |
                 {
                    "userId": 1,
                    "id": 101,
                    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
                  }
    /{id}:
      put:
        description: Modifica un post en la aplicación. Al tratarse de un API de prueba, el post no será modificado realmente.
        is: [postParameters]
        responses:
          200:
            body:
              application/json:
                example: |
                   {
                      "userId": 1,
                      "id": 101,
                      "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                      "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
                    }
      delete:
        description: Elimina un post de la aplicación. Al tratarse de un API de prueba, el post no será modificado realmente.
        is: [postParameters]
        responses:
          204:
    /{id}/comments:
      get:
        description: Obtiene todos los comentarios de un posts.
        is: [paging, generalQuery]
        responses:
          200:
            body:
              application/json:
                example: |
                  [
                     {
                        "postId": 1,
                        "id": 1,
                        "name": "id labore ex et quam laborum",
                        "email": "Eliseo@gardner.biz",
                        "body": "laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium"
                      },
                      {
                        "postId": 1,
                        "id": 2,
                        "name": "quo vero reiciendis velit similique earum",
                        "email": "Jayne_Kuhic@sydney.com",
                        "body": "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et"
                      }
                  ]
/comments:
    get:
      description: Devuelve todos los comentarios de la aplicación.
      is: [paging, generalQuery]
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "postId": 1,
                    "id": 1,
                    "name": "id labore ex et quam laborum",
                    "email": "Eliseo@gardner.biz",
                    "body": "laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium"
                  },
                  {
                    "postId": 1,
                    "id": 2,
                    "name": "quo vero reiciendis velit similique earum",
                    "email": "Jayne_Kuhic@sydney.com",
                    "body": "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et"
                  }
                ]
    post:
      description: Inserta un nuevo comentario en la aplicación. Al tratarse de un API de prueba, el comentario no será dado de alta realmente.
      is: [commentParameters]
      responses:
        200:
          body:
            application/json:
              example: |
                 {
                    "postId": 1,
                    "id": 501,
                    "name": "quo vero reiciendis velit similique earum",
                    "email": "Jayne_Kuhic@sydney.com",
                    "body": "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et"
                  }
    /{id}:
      put:
        description: Modifica un comentario en la aplicación. Al tratarse de un API de prueba, el comentario no será modificado realmente.
        is: [commentParameters]
        responses:
          200:
            body:
              application/json:
                example: |
                   {
                      "postId": 1,
                      "id": 501,
                      "name": "quo vero reiciendis velit similique earum",
                      "email": "Jayne_Kuhic@sydney.com",
                      "body": "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et"
                    }
      delete:
        description: Elimina un comentario de la aplicación. Al tratarse de un API de prueba, el comentario no será eliminado realmente.
        is: [commentParameters]
        responses:
          204:
/todos:
    get:
      description: Devuelve todas las tareas de la aplicación.
      is: [paging, generalQuery]
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "userId": 1,
                    "id": 1,
                    "title": "delectus aut autem",
                    "completed": false
                  },
                  {
                    "userId": 1,
                    "id": 2,
                    "title": "quis ut nam facilis et officia qui",
                    "completed": false
                  }
                ]
    post:
      description: Inserta una nueva tarea en la aplicación. Al tratarse de un API de prueba, la tarea no será de alta realmente.
      is: [todoParameters]
      responses:
        200:
          body:
            application/json:
              example: |
                 {
                    "userId": 1,
                    "id": 201,
                    "title": "delectus aut autem",
                    "completed": false
                  }
    /{id}:
      put:
        description: Modifica una tarea en la aplicación. Al tratarse de un API de prueba, la tarea no será modificada realmente.
        is: [todoParameters]
        responses:
          200:
            body:
              application/json:
                example: |
                   {
                      "userId": 1,
                      "id": 201,
                      "title": "delectus aut autem",
                      "completed": false
                    }
      delete:
        description: Elimina una tarea de la aplicación. Al tratarse de un API de prueba, la tarea no será eliminada realmente.
        is: [todoParameters]
        responses:
          204:[/code]

Kind regards,

Alex

**Comment by sichvoge** [comment]
This is still an issue. Weird that you are being forced to put them in. We should also consider to add an indication if something is required or not in the documentation.

**Comment by nmarinel01** [comment]
This is still an issue.
@sichvoge Using latest Console release, required attributes are marked this way. Would that be ok or were thinking of something else ? Thanks !
![image](https://cloud.githubusercontent.com/assets/19980188/23808456/b6724df2-05a8-11e7-9b40-526fe3b85ffa.png)

**Comment by sichvoge** [comment]
So is this fixed or not? I am confused.

**Comment by nmarinel01** [comment]
The part that is not fixed yet is that Console is forcing to put non-required attributes in some cases.
We need to analyze that... but I think that the ui improvement to indicate whether or not an attribute is required has been already addressed.
Regards !

**Comment by sichvoge** [comment]
This is actually been resolved in v4.

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
