### ISSUE TITLE
The Powered by MuleSoft graphic image is not found

### ISSUE THREAD

**Issue by yyamano** [mulesoft/api-console#175]
http://www.mulesoft.com/sites/all/themes/mulesoft/images/elements/powered-by-mulesoft.png is not found. The URL is mentioned at https://github.com/mulesoft/api-console/blob/master/LICENSE#L527

Also minor nits:

> EXHIBIT B. Attribution Information Attribution Copyright Notice: Copyright (c)
> 2013 MuleSoft, Inc.

The copyright year is not updated.

> Attribution URL: http://www.MuleSoft.org

I'm not sure if you want to use .org, instead of .com
Mule ESB uses http://www.MuleSoft.com. See https://github.com/mulesoft/mule/blob/mule-3.x/LICENSE.txt#L478

**Comment by sichvoge** [comment]
@jcenturion that is one for you :)

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
