### ISSUE TITLE
Authorization for the inital fetching of RAML spec file

### ISSUE THREAD

**Issue by tcompiegne** [mulesoft/api-console#176]
Hello everyone,

Our RAML spec file is not publicly accessible, you have to be authenticated and so the request to get the spec file must have an Authorization Header (Basic, Bearer, etc...).

Is there a way to add authorizations before the spec gets loaded?

Thanks

**Comment by jcenturion** [comment]
@tcompiegne: Currently, there is no way to do that. Maybe, you can proxy your RAML for the Console.

**Comment by nmarinel01** [comment]
Hi @tcompiegne !
Hope previous suggestion helped you. Im closing this thread , but please, feel free to reopen it if applies.
Thanks and regards !
