### ISSUE TITLE
Console gets duplicated in output

### ISSUE THREAD

**Issue by tomjohnson1492** [mulesoft/api-console#177]
When I integrate my RAML file, the output gets duplicated. See [http://learnapidoc.com/raml/specific.html](http://learnapidoc.com/raml/specific.html). Why is the console output appearing twice on the page? 

All I did to modify the original index.html file in the dist folder is add this:

```
<raml-console src="examples/weather.raml"></raml-console>
```

Could it be that something is coded wrong in [my RAML file](http://learnapidoc.com/raml/examples/weather.raml)? Thanks in advance for any help with this issue.

Tom

**Comment by tomjohnson1492** [comment]
The following line needs to be removed:

```
  <raml-initializer></raml-initializer>
```

If you include this line as well as the `<raml-console src=...` line, you end up with two console outputs.

**Comment by javiervidal** [comment]
Thanks for sharing. I had the same problem.
