### ISSUE TITLE
baseUri is present but Try-it is disabled

### ISSUE THREAD

**Issue by coderDem** [mulesoft/api-console#184]
Hello,

my problem is, that I try to integrate api-console in my application.
The api-console loads the raml-file linkedIn and shows the entrys,
but I can't try out the API.

I get this error: "Try-it is disabled because baseUri is not present"
But the baseUri is presented in the raml-example-file of LinkedIn.

Does any know why this error happens and how to solve it?

Best regards
coderDem

**Comment by jcenturion** [comment]
@coderDem: I'll try to reproduce it and let you know.

**Comment by coderDem** [comment]
Thx

**Comment by jcenturion** [comment]
@coderDem: I've tried with the `linkedIn.raml` from the `examples` folder and seems to be working. Could you please send me the RAML you are using?

![screenshot 2015-10-21 20 45 48](https://cloud.githubusercontent.com/assets/302314/10653322/e47d8e9e-7834-11e5-97b6-80ad2628a835.png)

**Comment by coderDem** [comment]
Hmm strange, I use the <code>github.raml</code> but it is also the same behavior with the <code>linkedIn.raml</code> file. Very strange...

**Comment by nmarinel01** [comment]
HI @coderDem !
is this problem still present ? If so, please, reopen the report and send us the raml specification that helps reproducing it.
Thanks ! Regards !
