### ISSUE TITLE
api-console allows the browser to execute arbitrary scripts included in RAML file

### ISSUE THREAD

**Issue by monami555** [mulesoft/api-console#188]
Take for example this file: https://html5sec.org/test.raml. When I attempt to load it in api-console, it displays a series of popup alerts.

This makes every site that uses api-console expose a cross-site scripting security vulnerability. It would be good if the api-console could neutralize such scripts before attempting to display the RAML.

Would that be considered a possible improvement in the near future?

**Comment by sichvoge** [comment]
TBH, this is something we should totally look at. Contributions are always welcome btw ;)

**Comment by dmartinezg** [comment]
hi @monami555, thanks for reporting, we'll $sanitize the heck out of this one, however, we will actually allow (by flag) for users to actually allow unsafe Markdown in there.

If you own the console, and the content it renders, you might actually want to put your custom JS in the markdown too.

By default, all markdown will be sanitized, you can expect a patch for this today!

**Comment by monami555** [comment]
Thank you very much! :)

**Comment by jcenturion** [comment]
Closing it ;).
