### ISSUE TITLE
RAML 1.0

### ISSUE THREAD

**Issue by JaniszM** [mulesoft/api-console#190]
api-console seems not support RAML 1.0 spec. For RAML 0.8 I had to copy content from dist dir into my dir with .raml definitions. This not work for 1.0, Unsupported #%RAML 1.0.

How can I create API for server purpose using RAML 1.0?

**Comment by jcenturion** [comment]
@JaniszM: API-Console currently does not support RAML 1.0. We are working on it. I let you know. ;)

**Comment by JaniszM** [comment]
@jcenturion: Do you know maybe if there is other tool I can use? Api-workbench supports RAML 1.0 but seems do not support standalone RAML API project, only via editor :( https://github.com/mulesoft/api-workbench

Can you aproximately say when api-console may support RAML 1.0? :)

**Comment by rvegas** [comment]
I'm also interested guys.
You guys have a plan for this so I could possibly help?

**Comment by JaniszM** [comment]
Funny thing, api-workbench seems to be only design tool right now ;) I don't see any possibility of running it locally :(

**Comment by usarid** [comment]
You can't run the API Workbench locally?






On Thu, Nov 5, 2015 at 7:42 AM -0800, "JaniszM" <notifications@github.com> wrote:












Funny thing, api-workbench seems to be only design tool right now ;) I don't see any possibility of running it locally :(

**Comment by rvegas** [comment]
I haven't found a way to check the possible responses based on the types and response examples on it.

**Comment by shlomiassaf** [comment]
Same here...
Couldnt find any notes about tools supporting documentation generation from RAML 1.0

Any clues?

**Comment by jcenturion** [comment]
@JaniszM, we are currently spiking to calculate the effort needed. I'll let you know once I have the final estimation.

**Comment by JaniszM** [comment]
@jcenturion thanks, I'm looking forward :)

@usarid Yes. this workbench seems to be only designing tool. I couldn't run designed example in browser :( Lib installed into .atom looks also very poor ;)

**Comment by h4t0n** [comment]
I'm looking forward :+1:

**Comment by aquamatthias** [comment]
+1

**Comment by felipegs** [comment]
+1

**Comment by mhonig** [comment]
+1

**Comment by JaniszM** [comment]
@jcenturion So what is the status of estimation or even work on RAML 1.0? :)

**Comment by wmccracken** [comment]
+1

**Comment by sichvoge** [comment]
@JaniszM the RAML parser for 1.0 are in a beta stage right now and being finalised by the mid of december. we are working with the workgroup to do that by slowly transition 0.8 to 1.0 in the console. we make sure to update everyone when we are done with this ;)

@dmartinezg do you want to add something?

**Comment by JaniszM** [comment]
Thanks for info.

**Comment by orzeh** [comment]
+1

**Comment by pradsheth** [comment]
+1. Currently I am exploring RAML tools to generate documentation based on 1.0

**Comment by pradsheth** [comment]
Are any other RAML tools in works for supporting 1.0 other than api-console?

**Comment by sichvoge** [comment]
@pradsheth it's the api-console, api-designer, we have the api-workbench that already has the support, and of course there will be MuleSoft's ESB and APIkit with support as well.

Other than MuleSoft, I guess there are many other tooling vendors that are currently migrating to 1.0 as well and just waiting for the finalised release for RAML 1.0 to do the last tweaks.

**Comment by jaoued** [comment]
:+1:

**Comment by pradsheth** [comment]
Thanks @sichvoge I would be very interested in learning about the timeline of these releases. As I understand once the api-console supports 1.0, raml2html will also benefit from 1.0.

**Comment by sichvoge** [comment]
MuleSoft only owns api-console whereas raml2html is a community project. But I know that there are efforts to support 1.0 there as well.

**Comment by andreidcm** [comment]
+1

**Comment by ckalima** [comment]
@sichvoge any updates on the progress of RAML 1.0 support?

**Comment by abaskov** [comment]
Also very much interested in RAML 1.0 support from tools, will be happy to get an update.

**Comment by sichvoge** [comment]
There is a branch here in this repo `feature/new-raml` that gets all the updates and we already merged multiple PRs. So we are moving forward ;)

**Comment by zilionis** [comment]
:+1:

**Comment by gingermusketeer** [comment]
Would i be correct in saying that helping with the new parser is the best thing to do? So that this project can utilize it.

Looks like there are a few things we could help with https://github.com/raml-org/raml-js-parser-2/issues

**Comment by donovankim** [comment]
+1

**Comment by knap1930** [comment]
http://raml.org/projects/projects

API Workbench, a rich, full-featured integrated development environment (IDE) for designing, building, testing, documenting and sharing RESTful HTTP APIs. It supports both RAML 0.8 and the recently launched **RAML 1.0**. RAML makes it easy to manage the whole

I assume this is incorrect?

**Comment by pelizza** [comment]
+1

**Comment by josh-jeong** [comment]
:+1:

**Comment by k-stasevich** [comment]
+1

**Comment by tjsnell** [comment]
+1

**Comment by paulcalabro** [comment]
+1

**Comment by danielocallaghan** [comment]
+1

**Comment by sichvoge** [comment]
Hi, did you guys tried out the branch [here](https://github.com/mulesoft/api-console/tree/features/raml-1.0). It is an implementation for the RAML 1.0 support. I'll lock the conversation since adding more `+1` does not add to much value to the conversation itself. If you still want to vote, you can use emoji with the original post to upvote it. But we are on that already.

**Comment by sichvoge** [comment]
The current console supports RAML 1.0. If you have issues with that version, please raise a new issue. I close that issue now.
