### ISSUE TITLE
When there is a 'proxy' set, the response URL, includes the proxy prefix

### ISSUE THREAD

**Issue by dmartinezg** [mulesoft/api-console#191]
![pasted image at 2015_11_17 09_58 pm](https://cloud.githubusercontent.com/assets/1099335/11213418/b88807f6-8d1a-11e5-9a19-fbb48bba3dcc.png)

**Comment by carowright** [comment]
Hi @dmartinezg !
Sorry for the late response. Could you please attach an example in order to reproduce this?

Thank you!

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
