### ISSUE TITLE
In Firefox, headers are not being sent.

### ISSUE THREAD

**Issue by ty10r** [mulesoft/api-console#192]
In Firefox:
After setting Basic Auth as an authentication-scheme and adding an `Authorization` header, the headers are not included in the request at all.

See this screenshot:
![apiconsole_firefox_headers_bug](https://cloud.githubusercontent.com/assets/4532146/11228043/ea8edbac-8d3e-11e5-836e-df896962c9af.png)

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
