### ISSUE TITLE
Make baseURI configurable

### ISSUE THREAD

**Issue by bertzer** [mulesoft/api-console#195]
Dear all,

is it already possible to override/configure the domain of the baseUri. We have multiple deploy environments with different domains and it is quite cumbersome to change it directly in the raml file for each deployment. I know that the api console supports a relative baseUri but this does not work with the raml-parser that we use for example to generate the Jax-RS interfaces.

Maybe this could be made available in the raml-console tag via a configuration option.

Thanks a lot for your feedback

Philipp

P.S. baseUriParameters are not a viable option :)

**Comment by sichvoge** [comment]
Hi Philipp,

The world is a very small place. :D

We are currently working on the support for RAML 1.0 that comes with couple of new features. One of them is Overlays/Extensions that can be used to separate implementation/configuration details from the interface definition. That should help you with your requirements.

I will post a blog article introducing that feature by next week, but you can read about it [here](http://docs.raml.org/specs/1.0/#overlays-and-extensions)

Please let me know if you have any other questions or something I can help you with. You know how to find me ;)

Christian

**Comment by sichvoge** [comment]
This is related to #318.

**Comment by mafischer** [comment]
Would it not be possible to inherit the domain from the request? In the "raml-console-loader" directive you could have an optional property "domain" to accomplish this functionality.
```<raml-console-loader src="api.raml" domain="inherit"></raml-console-loader>```

**Comment by sichvoge** [comment]
The new console will provide you with that anyways. Check out the [release/4.0.0](https://github.com/mulesoft/api-console/tree/release/4.0.0) branch.

**Comment by sichvoge** [comment]
@bertzer have you looked at [Overlays](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#overlays) yet? It gives you the ability to extend an existing RAML file with more information. In your case, you would have multiple overlay files per environment that basically adds the respective baseUri. For example:

**api.raml**
```yaml
#%RAML 1.0
title: Hello

/test:
```

**prd.raml**
```yaml
#%RAML 1.0 Overlay
extends: api.raml
usage: adds production URL
baseUri: http://prod.test.com
```

**stg.raml**
```yaml
#%RAML 1.0 Overlay
extends: api.raml
usage: adds staging URL
baseUri: http://stg.test.com
```

You only have to point the console to the respective overlay file (e.g. stg.raml).

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
