### ISSUE TITLE
api-console is not respecting displayName as Resource alias name

### ISSUE THREAD

**Issue by kubagruszka** [mulesoft/api-console#196]
According to raml spec http://docs.raml.org/specs/1.0/#resource-display-name the OPTIONAL displayName should be considered as primary name of the resource instead of it's URI part. I would suspect api-console to respect that but it isn't.

**Comment by sichvoge** [comment]
Hi @kubagruszka, I agree - but the console is still using 0.8 that does not have that strictness in it's spec. ;)

**Comment by sichvoge** [comment]
The question here is if the console should do that. It would be nice indeed. Since the spec states the following for the `displayName` node on resources:

> An alternate, human-friendly name for the resource. If the displayName node is not defined for a resource, documentation tools SHOULD refer to the resource by its key, which acts as the resource name. For example, tools should refer to the relative URI /jobs.

The console could always take the `displayName` as it defaults to the resource.

**Comment by sichvoge** [comment]
This is being implemented inside the new API console v4.

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
