### ISSUE TITLE
Pre actions before loading UI.

### ISSUE THREAD

**Issue by JaniszM** [mulesoft/api-console#200]
Is there possibility to execute some script before loading UI? I wish to use decorators on raml file and I need to do it before UI is loaded otherwise decorator is not applied on UI :/ For e.g. swagger allows for this by index.html.

**Comment by JaniszM** [comment]
I solved It by backend side, but it would be nice to have it in api-console ;)

**Comment by sichvoge** [comment]
That should be supported with the new API console. @jarrodek can you confirm, please?

**Comment by jarrodek** [comment]
If you are using the console as a html element (as described in the docs) you have full control over rendering process.
If you are using build tools to build the console as a standalone application then it won't be possible. However it is possible to use the build tools on custom build where you again can control how and when the console is rendered.

So basically this is supported in new versions.

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
