### ISSUE TITLE
Cannot load raml file in iframe

### ISSUE THREAD

**Issue by PabloInNz** [mulesoft/api-console#201]
Apologies if this is really obvious, but I can't seem to get this to work. I just wanted to test out the console to see what the documentation looked like, and the easiest way to do this was to wack in an iframe. I have copied the contents of the dist folder from the 2.0.5 release to a folder called APIConsole within my project (.NET Web API 2.0) and embedded in a page as below 
```html
<div>
    <iframe height="500" width="1000" src="../APIConsole/index.html?raml=../APIConsole/api.raml" />
</div>
```
The api.raml file is in the same folder as index.html. Wherever I put the file it says "cannot fetch ..... (404)"
Whatever I type in when the console is loaded will not load. I've tried just entering api.raml, assuming that the path is relative to the index.html, but no dice, and various other combinations. I think it's something very obvious that I'm missing or not doing, but for the life of me  I can't find out what.
If I copy and paste the contents of the api.raml file and use "Load RAML" it shows fine.
I'm running this in the Dev environment of Visual Studio 2013.

**Comment by dmartinezg** [comment]
Hi @PabloInNz, it is hard to tell what is going wrong. Did you look at the dev tools, network tab and see which URL it is trying to load?

I think that using relatives URIs is messing with your assumptions.

I edited your mesage, to be able to read it (the HTML broke the rendering in github)

**Comment by PabloInNz** [comment]
Thanks for looking at that. Looking in the network tab, if I just use ?raml=api.raml then the Request URL is http://localhost:54523/APIConsole/api.raml which is where the file is, but it fails in the api-console-vendor.js script FileReader.prototype.fetchFileAsynBrowser call in XMLHttpRequest.open('Get', file), but the file is just 'api.raml'   
If i change to ?raml=http://localhost:54523/APIConsole/api.raml, then the Request URL shown in the Network tab is still the same, and the file value in the XMLHttpRequest.open call is now the full URL but it still fails with a 404 error.
If I navigate directly to the index.html instead of in the i-frame it's the same behaviour. I've checked permissions on the folder just in case and it's got full control. I can't help thinking I'm getting something basic wrong somewhere.

**Comment by PabloInNz** [comment]
Ah. Found it. It was something basic. Visual Studio uses IIS Express when running, and it did not know what to do with a .raml file. Adding the following to the Web.config fixed it
'''html
 <system.webServer> 
<staticContent>
      <remove fileExtension=".raml" />
      <mimeMap fileExtension=".raml" mimeType="application/raml+yaml" />
    </staticContent>
  </system.webServer>
'''
