### ISSUE TITLE
Supporting multiple API versions

### ISSUE THREAD

**Issue by ravikiranj** [mulesoft/api-console#202]
Is there any way to change API version in the api-console ? For example, an enum of versions OR does it make sense to have a separate RAML file for each version ?

Some APIs have very aggressive versioning and I was wondering if it would be possible to support switching versions in the UI.

**Comment by dmartinezg** [comment]
API console is single document currently.

It is pretty simple to implement the switcher in a container application, by sending an event like API designer does: 

https://github.com/mulesoft/api-designer/blob/master/app/scripts/controllers/raml-editor-main.js#L196

You would have to retrieve and parse the RAML file though.

**Comment by ravikiranj** [comment]
Thank you for the pointers.
