### ISSUE TITLE
Bug: overlapping validator errors inside resource methods

### ISSUE THREAD

**Issue by JaniszM** [mulesoft/api-console#203]
When you have defined group of resources e.g. /image GET, PUT and POST and you have validator errors for some fields e.g.: "id" is required and you didn't put it then this error will be moved also to the other methods (if this methods have same fields).

Reproduce:
Make methods GET and POST with same "id" field as required. Click on method GET, send request without id (validator will raise error, red status bar), then switch tab to the POST method. You have now moved validator error on "id" field.= :(

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
