### ISSUE TITLE
Suggested content-type should be multipart/form-data instead of multipart/formdata

### ISSUE THREAD

**Issue by boukeversteegh** [mulesoft/api-console#205]
Wasted more than an hour wondering why the browser api-console crashed. The Atom api-console package generates suggestions for content-types, and one of them is broken.

``multipart/formdata`` (incorrect)
``multipart/form-data`` (correct)

In api-console.js it is seen that the contentType is checked against FORM_DATA (``multipart/form-data``), this never matches when you follow the UI suggested content types.

![image](https://cloud.githubusercontent.com/assets/53926/11850351/0c5e2940-a42d-11e5-975c-63336d03ed02.png)

**Comment by dmartinezg** [comment]
Hi @boukeversteegh, thanks for debugging this.

I saw that you also posted this in #api-workbench, if api-console (web app) crashes, we'll fix it so that it does not crash at least.

As for the wrong content-type suggested, that should be fixed in the workbench.

**Comment by sichvoge** [comment]
Does not happen for me anymore. I close that issue. If it is still a problem, let us know.
