### ISSUE TITLE
Can't add extra query parameters to the OAuth2 URI.

### ISSUE THREAD

**Issue by abienkowski** [mulesoft/api-console#206]
For example OpenAM (access management) solution, provides an option to add a realm (tenant) account to support multi-tenant access to a single resource. With this the user/oauth2 client will authenticate against a specific domain. This is done by adding ?realm=<tenant> to the query parameters for the OAuth2 authorization URI.

**Comment by jarrodek** [comment]
I can't find a base for any change here in OAuth 2 spec. The spec defines exact parameters that can be passed to OAuth authorization endpoint and `realm` is not on the list.

Since we have to comply with standards I can't see how this could be implemented.
