### ISSUE TITLE
How to pass "disable-theme-switcher" when using IFrame version

### ISSUE THREAD

**Issue by manodupont** [mulesoft/api-console#213]
The title says it all!

**Comment by jaime-olivares** [comment]
I have a similar situation, I am passing the 'raml'  parameter in the url, but still need to configure some other parameters.
I placed a similar question in stackoverflow: http://stackoverflow.com/questions/38112647/raml-api-console-configuration

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
