### ISSUE TITLE
Support for API display based on tag\category

### ISSUE THREAD

**Issue by arubalac** [mulesoft/api-console#220]
Hello,

We have a set of API's developed using RAML def and is available in the API console for reference .
Everything looks fine except we are not finding a good categorization feature for API to be grouped under a specific section\tag. This tag based categorization and rendering is observed in swagger console.
Many of your tenant’s who were new as well as experienced with swagger before felt the same and mentioned that API reference is not cool enough.

For example below are the API's we have developed and the API reference will show something similar to the one shown below

``` yaml
/mycompany/org/employee
                :get
        :post
                :put
/mycompany/org/{pfid}/employee
                :get
/mycompany/org/employee/{busid}
                :get
                :put
/mycompany/org/contractor
                :get
        :post
                :put
/mycompany/org/{pfid}/contractor
                :get
/mycompany/org/contractor/{busid}
                :get
                :put
```

Now looking at the above structure and deciphering which is for employee and which is for contractor on a glance or a quick view is difficult unless we have category to show the employee and contractor api differently under EMPLOYEE and CONTRACTOR (dropdown\link\accordion pane etc)

eg :

EMPOLOYEE

```
/mycompany/org/employee
                :get
        :post
                :put
/mycompany/org/{pfid}/employee
                :get
/mycompany/org/employee/{busid}
                :get
                :put
```

CONTRACTOR

```
/mycompany/org/contractor
                :get
        :post
                :put
/mycompany/org/{pfid}/contractor
                :get
/mycompany/org/contractor/{busid}
                :get
                :put
```

We saw this feature available in swagger for its rendering and we totally understand that the rendering of swagger console is driven by the tags that are available in the swagger file.

Our request is that , we would like to have a similar tagging feature.

Regards
Arun

**Comment by jarrodek** [comment]
This is not possible because RAML does not support tagging / grouping.
