### ISSUE TITLE
Response Status Codes out of bounds

### ISSUE THREAD

**Issue by kdcarlisle42** [mulesoft/api-console#221]
We are currently listing 11 different status codes in our api.  When we view a route and look at the Response section, the bottom three code have extended beyond the boundary
![screen_capture](https://cloud.githubusercontent.com/assets/17210658/13024514/4ef2a72a-d1bb-11e5-8527-ddbd9a7e153d.png)

**Comment by sichvoge** [comment]
Still an issue!

**Comment by nmarinel01** [comment]
Hi @kdcarlisle42 ,
Will you try with latest Console release ? 
![image](https://cloud.githubusercontent.com/assets/19980188/23812851/f4a778c4-05ba-11e7-94e2-20036bfb96e0.png)

I believe the issue has been solved but, please, reopen it if you think the problem is still present.
Regards
