### ISSUE TITLE
Running console outside of web server

### ISSUE THREAD

**Issue by kdcarlisle42** [mulesoft/api-console#222]
We built a simple stand alone page (based on the directions at the bottom of the project home page) that will display the raml api file.  When I load the page via IIS, the page loads and I see the api.  However, if I simply open the htm file in a browser, I receive an 'Error While Parsing' message, but no additional details are given.  I've tried using relative and complete paths.

Can the console be used outside of a web server?

**Comment by JaniszM** [comment]
If you use your own server for loading api-console remember to make this sources public/static. Maybe this is the reason of your problem :)

**Comment by kdcarlisle42** [comment]
True.  It use to work when opened in a browser (no web server).  Not sure what you mean by 'sources public/static'.

I've attached the htm file that I am attempting to open in the browser (via double-click).  If I place the file inside an IIS site and open it, it works.

[console_v1.zip](https://github.com/mulesoft/api-console/files/131366/console_v1.zip)

**Comment by JaniszM** [comment]
Ok, so you just run some html web directly from your hard disk? No web server hosting page?

I have no your js sources but I looked on html. First make sure that added sources is reachablen when you run index.html. Check your console browser if there is no errors. Rest looks fine I think.

But check this one:

```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>API Console</title>
        <link href="styles/api-console-light-theme.css" rel="stylesheet" class="theme">
    </head>
    <body ng-app="ramlConsoleApp" ng-cloak class="raml-console-body">
        <script src="scripts/api-console-vendor.js"></script>
        <script src="scripts/api-console.js"></script>
        <script>
            $.noConflict();
        </script>
        <raml-console src="../fcon/api_v1_draft_2.raml" single-view documentation-collapsed resources-collapsed/>
    </body>
</html>
```
This is the simples html for raml that I know, maybe you added to much to your src ? ;)

**Comment by sichvoge** [comment]
Is this still relevant?

**Comment by nmarinel01** [comment]
Hi @kdcarlisle42!
Hope that previous suggestions helped you out. I'm closing this question issue but please, feel free to reopen it if applies.
Thanks and regards !
