### ISSUE TITLE
RAML 1.0 Inline Maps are not supported

### ISSUE THREAD

**Issue by robvanmieghem** [mulesoft/api-console#235]
Inline maps are a nice way to declare maps in RAML 1.0: https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md/#shortcuts-and-syntactic-sugar but it is not supported in the api-console:
`Syntax error:Expected "|" or end of input but "{" found. `

**Comment by robvanmieghem** [comment]
Apparently it is because of this bug:
https://github.com/raml-org/raml-js-parser-2/issues/65

**Comment by fesor** [comment]
This feature was removed in RC2.
