### ISSUE TITLE
Custom header from security scheme disappears after swith methods in one resource.

### ISSUE THREAD

**Issue by xinyifly** [mulesoft/api-console#241]
It appears again if I switch security scheme.

**Comment by psotres** [comment]
This should be fixed with #229

**Comment by xinyifly** [comment]
@psotres After I updated.

$ grunt build
Running "jshint:files" (jshint) task

   test/regression/page_objects/resourcePO.js
     65 |  }
            ^ Missing semicolon.

>> 1 error in 67 files
Warning: Task "jshint:files" failed. Use --force to continue.

Aborted due to warnings.

**Comment by psotres** [comment]
This warning has been introduced in master branch after the PR

**Comment by sichvoge** [comment]
Seems that the new console v4 does not have that problem anymore anyways :)

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
