### ISSUE TITLE
Security header disappears

### ISSUE THREAD

**Issue by jeppe1990** [mulesoft/api-console#251]
Small postscript: After I posted this issue, I noticed that someone else already informed you guys about this in #241 . I checked if this was fixed in the latest version here on github, but I still get the same problem.
So instead of deleting my issue, I feel that it is still relevant as it (apparently) hasn't been fixed and my post contains additional info.  

I have defined a custom security scheme in my RAML file:

``` yaml
securitySchemes:
   Custom:
      type: x-custom
      describedBy:
          headers:
          Authorization:
            description: This header MUST be included in all requests that require authentication/authorization. The auth scheme is using a JSON Web Token Bearer Token as the header value. See [JWT](http://jwt.io/introduction/) for an introduction to JWT. (Though you don't really need to know anything about it)
            example: !include http://ramlstore/static_examples/AuthorizationHeaderValue.txt
            type: string
            required: true
        responses:
          400:
            description: Bad request
          401:
            description: Unauthorized
          403:
            description: Forbidden. You are not authorized to access this resource
```

The Authorization header is present on all my secured resources.
However, when i switch from a verb on a resource to another verb on the same resource, this header disappears from GUI and from the requests that are sent. 

Another (minor) bug is that the values of my Accept and Content-type headers are not auto completed when switching from one verb to another on the same resource.

The error displayed in the console is  "$digest already in progress": 
![api_console_ _google_chrome_2016-04-05_13-41-27](https://cloud.githubusercontent.com/assets/17174187/14280645/51b9304e-fb34-11e5-9a19-632cb6d1880c.png)

[A small screen recording demonstrating the bug](https://github.com/mulesoft/api-console/files/204331/videoOfBug.zip)

**Comment by sichvoge** [comment]
Seems that the new console v4 does not have that problem anymore anyways :)

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
