### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by jeppe1990** [mulesoft/api-console#255]
Whenever something goes wrong, be it 

> net::ERR_CONNECTION_REFUSED

or something else that might not show up in the console, the "response" section of "try it" displays a status of 0 and an empty header segtion. This could be improved significantly by displaying the error in the API console itself.

**Comment by sichvoge** [comment]
Is this still happening? Do you have an explicit example?

**Comment by sichvoge** [comment]
Closing that since it will be tracked by #297
