### ISSUE TITLE
RAML 1.0 no error message when raml file parsing failed

### ISSUE THREAD

**Issue by m3l7** [mulesoft/api-console#258]
I'm trying the 1.0 branch, and it seems that when the raml file can't be parsed correctly, the console just prints:

      TypeError: Cannot read property 'buffer' of undefined
          at api-console.js:903
          at processQueue (function.ts:82)
          at function.ts:82
          at Scope.$eval (function.ts:82)
          at Scope.$digest (function.ts:82)
          at function.ts:82
          at completeOutstandingRequest (function.ts:82)
          at function.ts:82

without useful information

**Comment by sichvoge** [comment]
Do you have a RAML file that you can add or can you try it again? We made some improvements and I wonder if its still an issue.

**Comment by sichvoge** [comment]
Closing that as this is tracked by #315.
