### ISSUE TITLE
api-console-vendor.min.js

### ISSUE THREAD

**Issue by clonq** [mulesoft/api-console#265]
Could you add minified versions of the js files in dist?

**Comment by xaka** [comment]
I guess so. I'll do today or tomorrow.

**Comment by xaka** [comment]
Done via https://github.com/mulesoft/api-console/commit/f84024c52c9a1bb3600b5b91a092d32718703dd8.

**Comment by clonq** [comment]
That was quick, thanks! Small issue though: pasting the min versions into index.html gives me "SyntaxError: unterminated string literal" on render. Didn't have much success with webpack either.
Any suggestions?
