### ISSUE TITLE
Resolve $ref in schemas, shown in api console.

### ISSUE THREAD

**Issue by alvassin** [mulesoft/api-console#267]
If i use schemas, that use $ref themselves, i can't see full request/response object.
It would be very nice if api-console would aggregate schemas itself & show all information about object.

**Comment by sichvoge** [comment]
I'd be careful here, maybe the resolution can happen dynamically when expanding a node? Expanding everything could and up in loops :)

**Comment by alvassin** [comment]
Will be possible after this [issue](https://github.com/raml-org/raml-js-parser/issues/140) and [PR] will be implemented.

**Comment by sichvoge** [comment]
Did you recently check the API Console and if that works? We added the new parser and removed the old. Can you check if it still works.
