### ISSUE TITLE
Implement ability to load raml from private repos.

### ISSUE THREAD

**Issue by alvassin** [mulesoft/api-console#271]
Hello.

I have made single-hosted api-console app instance and want to connect it with corporate private git repo, to provide users ability to specify direct url to raml in api-console instance to see documentation. Let's imagine it will be hosted at `raml.corp.example.com`.

**Private repos problem**: git repos require authentication (cookies). To send cookies in cross-domain request you have to specify `xhr.withCredentials=true` flag. If your private repo returns `Access-Control-Allow-Origin: http://raml.corp.example.com` (not wildcard!) api-console will load raml successfully.

**Public repos problem** We can't just add `xhr.withCredentials=true` flag, because all responses with wildcard `Access-Control-Allow-Origin: *` origin will fail because of browser security policy: cookies are not allowed to be sent to wildcard origin.

*_Possible solutions *_
[I've proposed to implement `xhrWithCredentials` flag in raml-parser](https://github.com/raml-org/raml-js-parser/issues/177), it will allow further implementation in api-console, but there are two possible ways how to implement support for private repos:

First is to implement additional GET parameter `sendCookies` that can be used with `raml`, e.g. `http://raml.corp.example.com/?raml=path-to-raml&sendCookies=true`. In GUI checkbox `Use cookies` can be implemented as option for users.

Second (i don't like it really) way is to hide this logic inside and to perform two requests: first will try to load raml file without credentials (as it works now), and if first request fails for some reason api-console will try to perform second one with `xhr.sendCredentials=true` flag.

What would you think? I can make pull request, if this is acceptable.

**Comment by dmartinezg** [comment]
Hi @alvassin, here are my 2c's, this looks like something that is a little too complicated for API console to support out of the box, and for a very specific case (which I agree _may_ be generic enough).

In my opinion, you should build your own console, using the <api-console directive> and build your own: raml-initializer and ramlParserWrapper, injecting your own custom ramlReader into the parser.

While it sounds like a ton of work, we actually do this in more than one place to handle authentication issues like the one you describe.

**Comment by alvassin** [comment]
@dmartinezg This is totally common case. This app would fail for every source with cookie or basic authentication. 

If you see UI improvements would make UI too complicated for users - lets implement just GET param.

**Comment by alvassin** [comment]
@dmartinezg Added PR to implement GET param.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
