### ISSUE TITLE
PATCH command doesn't work when used in cross-origin environment

### ISSUE THREAD

**Issue by sameshit** [mulesoft/api-console#272]
The issue occurs only for PATCH commands - whenever you try to execute command you got following error message in the browser:

Failed to load resource: Method patch is not allowed by Access-Control-Allow-Methods.

**Comment by dmartinezg** [comment]
How are you using console?
Are you proxying requests through the provided proxy?
if not, is the API CORS enabled?

**Comment by nmarinel01** [comment]
Hi @sameshit !
Can you provide an example or more information about this issue ? 
Is it still present ? Please, confirm.
Regards !

**Comment by jarrodek** [comment]
This is not API Console issue. The server does not support CORS correctly.
