### ISSUE TITLE
Loading "grunt-karma.js" tasks...ERROR

### ISSUE THREAD

**Issue by alvassin** [mulesoft/api-console#275]
```
$ grunt
Loading "grunt-karma.js" tasks...ERROR
>> Error: Cannot find module 'karma'

Running "jshint:files" (jshint) task
Warning: Path must be a string. Received null Use --force to continue.

Aborted due to warnings.
```

**Comment by alvassin** [comment]
Still unable to install on clean nodejs 6.0 on mac. 
I get `UNMET PEER DEPENDENCY karma@~0.12.0` error while executing `npm install`.

**Comment by alvassin** [comment]
Installing karma using `$ npm install --save-dev karma@~0.12.0` seemed to be ok, but grunt is still failing. Is there any solution for this?

**Comment by dmartinezg** [comment]
@juancoen are you having these issues?

**Comment by juancoen** [comment]
It's working for me

@alvassin which Node version are you using?

**Comment by alvassin** [comment]
@juancoen
```
$ node --version
v6.0.0
```

**Comment by juancoen** [comment]
@alvassin The Console is not working with Node 6 and npm 3. While we fix this, you can still use the Console with Node LTS version (v4.4.4 with npm 2.15.1).

**Comment by Relequestual** [comment]
I'm experiencing this issue also.
I'm using node 7.1.0 and npm 4.0.5.

Is no one else using this tool or is everyone who is still on node v4? LTS now includes node 6.

**Comment by amarnath6** [comment]
I'm experiencing this issue too.
I'm using node 7.5.0 and npm 4.1.2.

Loading "grunt-karma.js" tasks...ERROR

**Comment by sergeynechaev** [comment]
Got the same Loading "grunt-karma.js" tasks...ERROR on node v7.9.0 and npm 4.5.0.

**Comment by alexandra1030** [comment]
Hello @juancoen 
I got the same error.
I'm using node 7.9.0 and npm 4.2.0.

`$ grunt
>> Local Npm module "grunt-karma" not found. Is it installed?
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
`
I've installed the `grunt-karma`, but it doesn't still work for me.

Thanks,
Alex

**Comment by jywarren** [comment]
Same as @alexandra1030 -- node 7.9.0 and npm 4.2.0.

**Comment by carlosaparadam** [comment]
Run 
npm install grunt-contrib-imagemin --save-dev

**Comment by joannbrereton** [comment]
^^ Above did not work for me (install grunt-contrib-imagemin --save-dev) I still get the following complaint (using node 8.11.1)

```
>> Local Npm module "grunt-parallel" not found. Is it installed?
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
```

**Comment by zion3mx** [comment]
I'm experiencing this issue too when i was installed "npm install grunt-contrib-imagemin --save-dev"
I'm using node v10.9.0 and npm 6.4.0

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
