### ISSUE TITLE
date-only validation fails on raml 1.0

### ISSUE THREAD

**Issue by mafischer** [mulesoft/api-console#276]
<img width="417" alt="screen shot 2016-05-19 at 7 18 05 pm" src="https://cloud.githubusercontent.com/assets/1082176/15413521/a4354b02-1df6-11e6-88ff-112403dc1007.png">

**Comment by sichvoge** [comment]
Does it only fail in the console or somewhere else? Are you using any designer for RAML so that we can validate if that is a problem of the console or something else.

**Comment by mafischer** [comment]
I've only seen it fail in the console. I used the atom api-workbench plugin to validate that the raml was valid. I'm loading the raml file via <raml-console-loader src="api.raml"></raml-console-loader>

**Comment by sichvoge** [comment]
Guess you are using the features/raml-1.0 branch?

**Comment by mafischer** [comment]
Yes

**Comment by juancoen** [comment]
Fixed
