### ISSUE TITLE
hosting assets on a cdn

### ISSUE THREAD

**Issue by nwolff** [mulesoft/api-console#277]
This would alleviate the need for each user to copy and serve the js / fonts / css

**Comment by lapo-luchini** [comment]
Version 3.0.17 can already be used from NPM thanks to [unpkg CDN](https://unpkg.com/api-console@3.0.17/dist/).
Unfortunately version 4.x is not there yet.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
