### ISSUE TITLE
I don't understand how to use this in inline mode

### ISSUE THREAD

**Issue by CameronGo** [mulesoft/api-console#284]
I am attempting to use the api-console in inline mode using the example.  I can get it to work using the query parameter for the path to the RAML using the following:
https://testserver/api-console/dist/index.html?raml=ramlpath/api.raml

If I edit the ./dist/index.html file; however, to add this:
`<raml-console src="ramlpath/api.raml"></raml-console>`
I only see a Resources bar added to the page above the initializer with no resources or documentation.  I've tried moving this inside the raml-initializer directive, the head of the document, inside the body tag.  I don't understand what I'm doing incorrectly.  My current index.html looks like this:

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>API Console</title>
  <link href="styles/api-console-light-theme.css" rel="stylesheet" class="theme">
</head>
<body ng-app="ramlConsoleApp" ng-cloak class="raml-console-body">
  <raml-console src="ramlpath/api.raml"></raml-console>
  <raml-initializer></raml-initializer>
  <script src="scripts/api-console-vendor.js"></script>
  <script src="scripts/api-console.js"></script>
  <script>
    $.noConflict();
  </script>
</body>
</html>
```

Help?

**Comment by gianebao** [comment]
Getting the same issue. I am trying to load ./examples/box.raml

**Comment by ibnesayeed** [comment]
I am also facing this same issue.

**Comment by gianebao** [comment]
I managed to make it work here https://github.com/gianebao/api-console/pull/1.

after browsing through the code, I found out about `<raml-console-loader>` which accepts the attribute `src`. And then, just added a bit of code to support the Caveats.

**Comment by CameronGo** [comment]
Could you post your code so I can see an example of what worked for you?

**Comment by CameronGo** [comment]
I also attempted this BTW, but the additional options seem to have no affect:

`
  <raml-console-loader src="/pathtoraml/api.raml" documentation-collapsed resources-collapsed disable-theme-switcher>
  </raml-console-loader>
`

**Comment by humblelistener** [comment]
This worked
```
<raml-console-loader src="https://raw.githubusercontent.com/PageUpPeopleOrg/api-docs/master/api.raml"
                       options="{ disableRamlClientGenerator: true, disableThemeSwitcher: true }"></raml-console-loader>
```

**Comment by sichvoge** [comment]
@humblelistener happy to accept any PR ;)

**Comment by sichvoge** [comment]
Fixed in documentation!
