### ISSUE TITLE
Binding queryParameters to text/xml example

### ISSUE THREAD

**Issue by mycaule** [mulesoft/api-console#288]
I am currently designing a POST route that takes XML in the body of the request.

In RAML, `post>queryParameters` can be described with `displayName`, `description`, `type`, `example` _etc._
then in `post>responses>200>body>text/xml` I can provide a sample xml in `example`. Is there a way to bind (through XPath?) the values of `queryParameters` to the sample xml so that when users modify values in the API Console, the XML body is automatically modified ?

Thank you.

**Comment by sichvoge** [comment]
It's not possible now.

**Comment by nmarinel01** [comment]
Hi @mycaule ! Thanks for your contact.
Im closing this issue now , but please, feel free to reopen it or create a new one if applies.
Regards !
