### ISSUE TITLE
Access Token not saved?

### ISSUE THREAD

**Issue by bobmulder** [mulesoft/api-console#295]
Hi there!

I am trying my own API through the API-console. However, I discovered that every time I try the request with OAuth2 (AuthCode), a new access token is requested from the auth server.

Why isn't this saved in local storage or whatever? It's soo expensive to request a new access token every time...

**Comment by jarrodek** [comment]
New API console has different approach for this issue. 
Once the token is generated it stays in memory and is applied to next method or endpoint selected in the Try It request panel. It's not stored in local / session storage so once you reload the page the token will have to be regenerated by providing client ID.

I hope that solves this issue.

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
