### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by bkabrda** [mulesoft/api-console#297]
I'm trying to get api-console to work with my (quite complex) RAML file, but I keep getting "Api contains errors." message when I try to load it. I see no descriptive error message, nor a log message in JS console in Firefox, so I have no idea what's wrong.
- Is there any howto on debugging these errors, am I missing something?
- Would it be possible to be more verbose with the errors, so that I could try fixing the issue in my raml file?

FWIW other tooling like raml2md works fine with my spec.

**Comment by sichvoge** [comment]
@bkabrda can you attach some images that shows these errors, and maybe the RAML file. Are you using the standalone version that is currently in master?

**Comment by bkabrda** [comment]
Ok, this is weird, I'm getting a different error now, which says: `JS-YAML: [object Object]`... I haven't changed my RAML file, I just restarted the development Grunt server.
I'm attaching a screenshot of that - the error message is at the same place as the yesterday's one was. I'm running from master, commit 5c366612ba67f797b168bcfd39c27dc34a2c402c.
Unfortunately my RAML file can't be made public right now, but I have some time today, so I'll try removing things until I find minimal reproducer and then post it here.

![screenshot from 2016-06-15 09-57-01](https://cloud.githubusercontent.com/assets/1050061/16072169/c88613d0-32df-11e6-9325-bee409237364.png)

**Comment by bkabrda** [comment]
Correction: so I'm still getting "Api contains errors". I was getting the above error since my local server serving the RAML file wasn't running :) (this might be worth fixing as well)

**Comment by bkabrda** [comment]
So here's the reproducer:

```
#%RAML 0.8
title: My REST API
version: v1
baseUri: /api/{version}

/endpoint:
  get:
    displayName: Endpoint
    description: List currently tracked ecosystems, always sorted by name alphabetically
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "something": "else"
              }
```

The root cause of this problem is that I mistakenly used `displayName` for `get` method, which is not allowed by RAML 0.8 - I get that this is my fault, but it'd be cool if the console could give me more details in this case.

**Comment by sichvoge** [comment]
Does the console render the API?

**Comment by bkabrda** [comment]
If the `displayName` is there, it doesn't, it just shows the error in the red box. If I remove the erroneous `displayName`, it's displayed correctly.

**Comment by sichvoge** [comment]
Strange that the parser actually returns the correct error message. I am getting:

```
{ [Error: Api contains errors.]
  parserErrors: 
   [ { code: 2,
       message: 'Unknown node: displayName',
       path: 'test5.raml',
       start: 89,
       end: 100,
       line: 7,
       column: 4,
       range: [Object],
       isWarning: false } ] }
```

**Comment by bkabrda** [comment]
Yeah, that looks correct. I guess the problem is in the presentation of that error message, but unfortunately I have no time to debug that now :(

**Comment by sichvoge** [comment]
No worries, I'll take it from here.

**Comment by sichvoge** [comment]
This specifically happens when you load from a URL. You get the appropriated error messages inside the text box where you can copy & paste your RAML in.

**Comment by sichvoge** [comment]
Also linking https://github.com/mulesoft/api-console/issues/255. So we can use this ticket to track it also.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
