### ISSUE TITLE
!include types not working in branch feature/new-raml

### ISSUE THREAD

**Issue by iDeBugger** [mulesoft/api-console#298]
Like it's said in title it's only in branch "feature/new-raml". I'm trying to open .raml with !include directives like this
```
types:
  User: !include types/User.raml
```
but i've got error
```
inheriting from unknown type at 6:3
```

I've tried several formats of include path:
- !include /types/User.raml
- !include ./types/User.raml
- !include http://my.domain.com/path_to_root_raml/types/User.raml

None of this working correctly.

Is it bug? Should I use some special include path?

**Comment by sichvoge** [comment]
So that does not happen with the master branch?

**Comment by iDeBugger** [comment]
Master support only raml v0.8, isn't it? My file v1.0

**Comment by sichvoge** [comment]
No, master support both now.

**Comment by iDeBugger** [comment]
Ok, I will try later and write here about results

**Comment by iDeBugger** [comment]
The same problem in master

**Comment by iDeBugger** [comment]
Oh, wait, i found some non-obvious indentation problem in my files.
I fixed them and now all works as expected.

I'll close this issue.
