### ISSUE TITLE
CLI & static documentation generation

### ISSUE THREAD

**Issue by oleksandr** [mulesoft/api-console#30]
More like an enhancement - not everyone in this world is using node.js or is willing/allowed to have all its related mumble-jumble installed on the infrastructure servers. 

What would be really nice is to have a CLI command to generate static documentation (similar to https://readthedocs.org, as example). The feature of "Try it" can also be included and rely on a proxy, which settings would be provided before generation.

I'm willing to contribute, but not with the current stack used for implementation :-(

**Comment by Relequestual** [comment]
It's still unclear that this is possible in the documentation. We can't run the required stack on our production envrionment.

**Comment by sichvoge** [comment]
CLI will be provided by the new console version (see info [here](https://github.com/mulesoft/api-console/tree/release/4.0.0#build-tools)) and you only have to deploy the generated version on a simple HTTP server.

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
