### ISSUE TITLE
Custom headers not rendered in "Try it"

### ISSUE THREAD

**Issue by sanusart** [mulesoft/api-console#303]
Custom response headers are not rendered in the "Try it" tab.

I have this defined in the .raml file resourceTypes:

``` yml
get?:
 responses:
  200:
   description: |
    OK
   headers:
    Location:
     example: "<<resourcePath>>"
    Last-Modified:
     example: "Sun, 23 Nov 1980 17:00:00 GMT"
    X-Api-Version:
     example: "v1"
```

**EDIT:** `Last-Modified` header does work sometimes.

But none of this headers are rendered at the response section.

Am I missing something?

Thanks.

**Comment by sichvoge** [comment]
Are you using RAML 1.0 or 0.8? Can you maybe add a minimalistic example that shows your problem within the complete context?

**Comment by sanusart** [comment]
Sorry, I just hoped my syntax is wrong and someone will point that out.

Using RAML 0.8

When you load the following into api-console:

```yml
#%RAML 0.8
title: test API
version: v1
baseUri: https://jsonplaceholder.typicode.com
/users:
    displayName: User
    get:
      responses:
        200:
          description: |
            OK
          headers:
            X-Powered-By:
            	- example: "Express"
```

I'd expect to see a header `X-Powered-By` along with other headers of the response. But it is not there.

![image](https://cloud.githubusercontent.com/assets/267718/17154456/c615cbfc-5389-11e6-8fbe-cfe1039ac9e4.png)

The same file used in the "api manager" editor at https://anypoint.mulesoft.com shows all the headers in the response.

![image](https://cloud.githubusercontent.com/assets/267718/17154468/d572627c-5389-11e6-902c-3310c1002714.png)


So my question is how can I achieve this functionality in api-console. Thanks.

**Comment by sichvoge** [comment]
It seems that the console does not even render all information from headers in 0.8.

![image](https://cloud.githubusercontent.com/assets/498114/17210120/b4f79712-54b8-11e6-90bb-39b44bf60ae1.png)

**Comment by sichvoge** [comment]
Sorry it seems something is wrong with the CSS rather than its an actual bug. Adjusting the size of my window brought back the information :/

**Comment by sanusart** [comment]
It is actually does rendering some headers for me (as you may see in the screenshot above)

**Comment by sanusart** [comment]
> brought back the information 

With all the custom headers too?

**Comment by sichvoge** [comment]
No I just see the documentation know, but I have no idea why there is a different from what the console in the designer responses vs the standalone console.

**Comment by sanusart** [comment]
So I am doing soethig wrong?

**Comment by sichvoge** [comment]
No I don't think so! We would need to investigate the differences a bit more.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
