### ISSUE TITLE
Theme switching and static resources

### ISSUE THREAD

**Issue by s0undt3ch** [mulesoft/api-console#305]
I serve my console-api under `/api` and my static resources are served from `/static`, for console-api, `/static/api`.
i've updated the provided `index.html` to fetch the static resources form the right URL:

``` html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>API Console</title>
  <link href="/static/api/styles/api-console-light-theme.css" rel="stylesheet" class="theme">
</head>
<body ng-app="ramlConsoleApp" ng-cloak class="raml-console-body">
  <raml-console-loader src="/api/ref"></raml-console-loader>
  <script src="/static/api/scripts/api-console-vendor.js"></script>
  <script src="/static/api/scripts/api-console.js"></script>
  <script>
    $.noConflict();
  </script>
</body>
</html>
```

api-console loads properly, but when trying to switch theme's, the request made against my service is to `/styles/api-console-dark-theme.css`.
Without patching I seem to be unable to fix this.

Would it be possible to add support to specify the base url for static resources as an option to console-api?

**Comment by s0undt3ch** [comment]
This happens in both the latest stable and the latest code from the master branch

**Comment by sichvoge** [comment]
Why not sending us a PR for that support? :)

**Comment by s0undt3ch** [comment]
Because I'm really too new to the framework and right now I really don't know where to start. What would take me hours probably takes you some minutes. I will try to find some time for it though.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
