### ISSUE TITLE
Layout breaks with long text

### ISSUE THREAD

**Issue by matart15** [mulesoft/api-console#306]
Layout breaks with long text
![screen shot 2016-07-28 at 7 15 18 pm](https://cloud.githubusercontent.com/assets/17027219/17209397/cd54a40a-54f7-11e6-8be6-e8216c7d9e37.png)

**Comment by ibnesayeed** [comment]
Possible duplicate of #287?

**Comment by sichvoge** [comment]
It seems it is.

**Comment by nmarinel01** [comment]
Closing on favor of #287
