### ISSUE TITLE
examples: converts json to string

### ISSUE THREAD

**Issue by matart15** [mulesoft/api-console#309]
## example: reads json

```
responses:
      200:
        body:
          type: <<resourcePathName>>
          example: !include /responses/post_list.json
```

<img width="751" alt="screen shot 2016-07-28 at 10 30 03 pm" src="https://cloud.githubusercontent.com/assets/17027219/17214269/10fffd06-5513-11e6-9cbd-452f28839a45.png">
## examples: make json like string

```
responses:
      200:
        body:
          type: <<resourcePathName>>
          examples:
            success: !include /responses/post_list.json
            fail: !include /responses/post_list.json
```

<img width="780" alt="screen shot 2016-07-28 at 10 29 04 pm" src="https://cloud.githubusercontent.com/assets/17027219/17214286/2c10a474-5513-11e6-99b4-c0de97d823e9.png">

using exact same json file.
Am i missing something?

**Comment by sichvoge** [comment]
MH, would you be able to attach a minimalistic version of your RAML?

**Comment by matart15** [comment]
```
/list:
  type: 
    is: [paged, jwt_secured]
    description: Collection
  get:
    responses:
      200:
        body:
          type: PostListModel
          # examples:
          #   success: !include /responses/post_list.json
          #   fail: !include /responses/post_list.json
          example: !include /responses/post_list.json
```

**Comment by lwcolton** [comment]
Confirmed.  This happens with the examples from the official RAML 1.0 spec:  

https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#example-of-how-to-define-exampleexamples-in-raml

**Comment by sichvoge** [comment]
OK - that we need to investigate a little bit more. Thanks!

**Comment by carobazan** [comment]
verified on QA branch, will be included in next release
