### ISSUE TITLE
Example inserted twice in documentation

### ISSUE THREAD

**Issue by tr3ddy** [mulesoft/api-console#311]
When adding a JSON example for a response, the example will be printed twice in the documentation. As the first occurrence seems to be the right one, as this is correctly highlighted, the second one is just the text output of the JSON include. This will also break the layout, if the JSON is a little bit longer.

This occurs when using includes as well as using inline JSON in the RAML-file.

![bildschirmfoto 2016-08-02 um 10 43 45](https://cloud.githubusercontent.com/assets/2187636/17322528/1f4865d6-589e-11e6-91d6-5df431e5d4ba.png)

**Comment by sichvoge** [comment]
Thanks! We are currently reviewing all the different API Tools to make sure the quality around RAML 1.0 is appropriated. It might take some time to get to this, but we will investigate the problem asap.

**Comment by ibnesayeed** [comment]
I was facing this issue for long time, but I couldn't figure it out where to make necessary changes to deal with it. So, as a temporary fix, I added some CSS to hide the unformatted example block.

**Comment by sichvoge** [comment]
This is related to #321. I am closing this issue.

**Comment by paulcalabro** [comment]
Just fyi, I added a quick workaround in https://github.com/mulesoft/api-console/issues/321 that can be used until the bug gets fixed!
