### ISSUE TITLE
<raml-console> directive not work

### ISSUE THREAD

**Issue by edamov** [mulesoft/api-console#313]
Hi.
I clone repository and add some code in `dist/index.html` file
```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>API Console</title>
  <link href="styles/api-console-light-theme.css" rel="stylesheet" class="theme">
</head>
<body ng-app="ramlConsoleApp" ng-cloak class="raml-console-body">
  <div style="overflow:auto; position:relative"> <!-- NEW LINE -->
    <raml-console src="./examples/github.raml"></raml-console> <!-- NEW LINE -->
  </div> <!-- NEW LINE -->
  <script src="scripts/api-console-vendor.js"></script>
  <script src="scripts/api-console.js"></script>
  <script>
    $.noConflict();
  </script>
</body>
</html>
```
And when I'm trying to open `index.html` I see page with any resources:
![](http://dl1.joxi.net/drive/2016/08/07/0004/3622/269862/62/3927aea917.jpg)

What I do in a wrong way?

**Comment by edamov** [comment]
I try `<raml-console-loader>` instead `<raml-console>`. Some examples from `examples` folder is working now, but some (github, stripe, twitter) have an error such in #258

**Comment by sichvoge** [comment]
I had to use `raml-console-loader` as well.

**Comment by edamov** [comment]
All examples that doesn't work - with RAML version 0.8
I think examples with error should be removed from `examples` folder or should be rewrite for new RAML version 1.0

**Comment by sichvoge** [comment]
BTW, Github API works for me!

![image](https://cloud.githubusercontent.com/assets/498114/17479465/9aa36d54-5d6a-11e6-9125-184671ffbf79.png)

**Comment by edamov** [comment]
So, maybe the error is depend on browser or environment... Can you please show your index.html file? Is it like mine in the first comment to the issue?

**Comment by sichvoge** [comment]
```html
<html>
  <head>    
    <link rel="stylesheet" href="/api-console/styles/api-console-light-theme.css" type="text/css" />  
  </head>
  <body ng-app="ramlConsoleApp" ng-cloak id="raml-console-unembedded">    
    <script src="/api-console/scripts/api-console-vendor.js"></script>
    <script src="/api-console/scripts/api-console.js"></script>    
    <div style="overflow: auto; position: relative"> 
      <raml-console-loader src="<url>" disable-theme-switcher/>  
      <script>$.noConflict();</script>
    </div>
  </body>
</html>
```

**Comment by edamov** [comment]
In console I have such error:
```
TypeError: Cannot read property 'buffer' of undefined
    at api-console.js:1117
    at processQueue (api-console-vendor.js:425649)
    at api-console-vendor.js:425665
    at Scope.$eval (api-console-vendor.js:426901)
    at Scope.$digest (api-console-vendor.js:426717)
    at api-console-vendor.js:426940
    at completeOutstandingRequest (api-console-vendor.js:417271)
    at api-console-vendor.js:417659
```

**Comment by sichvoge** [comment]
I created an [issue](https://github.com/mulesoft/api-console/issues/315) for that behaviour although it does not explain why it is working for me not for you :)

**Comment by edamov** [comment]
Maybe I should close this issue because it duplicates your issue and #258 ?

**Comment by sichvoge** [comment]
Yes please. That makes sense.

**Comment by edamov** [comment]
Closing that as this is tracked by #315.
