### ISSUE TITLE
console should show errors

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#314]
The current console does not show any errors when you load a RAML file that is invalid. The overview page that usually shows your resources etc., is completely white and don't get an appropriate help in the Javascript console either. 

![image](https://cloud.githubusercontent.com/assets/498114/17478488/100f2dfa-5d64-11e6-8059-e4ac74e0aa0f.png)

We need to show errors and traces instead of a blank page.

**Comment by nmarinel01** [comment]
Fixed at 3.0.16 release
