### ISSUE TITLE
New parsers "errors" object handling is not updated in raml-console-loader

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#315]
The `raml-loader-console` directive does not handle the new "errors" object schema accordingly to the new parser. It seems that [this code](https://github.com/mulesoft/api-console/blob/master/src/app/directives/raml-console-loader.js#L48) was not updated, and now every time you use this directive alone plus an invalid RAML, you end up with the following:

![image](https://cloud.githubusercontent.com/assets/498114/17483702/0742efe8-5d7f-11e6-9f3f-b561a9632d55.png)

That obviously happens since the directive tries to access the buffer property, but it isn't there. `(error.context_mark || error.problem_mark).buffer`

This is related to #313 and #314

**Comment by sichvoge** [comment]
It also is a related to https://github.com/mulesoft/api-console/issues/258

**Comment by tiguchi** [comment]
I'm running into the same problem. Looks like the RAML parser cannot deal with situations where a library file tries to use another library or include type snippet files.

All referenced files are correctly downloaded. They appear in the network tab of the developer console of my browser.

When I rewrite that library file and remove all references to the other files, then the error disappears and the API console page renders again.

**Comment by sichvoge** [comment]
Do you have a small reproducible example?

**Comment by tiguchi** [comment]
I have been trying to create a minimum example for the past 20 minutes, but I cannot reproduce the problem. So I guess something else must be going sideways with my actual API project. Unfortunately I cannot share that project, since it's for a client of mine.

I noticed something though: when I remove just the `uses` statement from my library file, and keep the `!include` statements for the DataType files, then the API console loads again.

**Comment by tiguchi** [comment]
Never mind, I figured out the cause of the problem... it's the browser cache. Google Chrome doesn't re-download the updated include files even when I hit shift + F5, so it was downloading old files that contained errors.
Clearing the browser file cache fixes the problem :-/

**Comment by sichvoge** [comment]
Perfect! So can we close that?

**Comment by tiguchi** [comment]
Yes, it was just a file caching problem

**Comment by hadrienk** [comment]
Well, the error is still not displayed. 

````javascript
$scope.vm.error = angular.extend(error, {
              /*jshint camelcase: false */
              buffer: (error.context_mark || error.problem_mark).buffer
              /*jshint camelcase: true */
            });
````

Error in this context does not contain context_mark nor problem_mark. Instead we have:

````json
{
    "parserErrors": [{
        "code": 1,
        "message": "JS-YAML: bad indentation of a mapping entry at line 188, column 14",
        "path": "api.raml",
        "range": {
            "start": {
                "line": 188,
                "column": 13,
                "position": 6023
            },
            "end": {
                "line": 188,
                "column": 14,
                "position": 6024
            }
        },
        "isWarning": false
    }] 
}
````

**Comment by hadrienk** [comment]
Oh, now I see. 365 solved that. Nevermind!
