### ISSUE TITLE
Query Parameters didn't do corresponding change

### ISSUE THREAD

**Issue by baoti** [mulesoft/api-console#322]
A resource support GET and POST, but with different query parameters:

```
GET /cats
query parameters:
  a:

POST /cats
query parameters:
  b:
```

When I click `/cats GET`, the document is opened, I can see `Query Parameters: a`, then I click `POST`, `Query Parameters` no changed.
When I close document and reopen `POST` document panel, I see the `Query Parameters: b`.

**Comment by carobazan** [comment]
Verified on QA branch, will be included in next release
