### ISSUE TITLE
the types are not rendered correctly.

### ISSUE THREAD

**Issue by davisskchan** [mulesoft/api-console#326]
For the type walletConsumerPatchPayload, meta property is rendered as :

 meta required lib2.ee.metaEntity

[library1.raml.txt](https://github.com/mulesoft/api-console/files/444014/library1.raml.txt)
[library2.raml.txt](https://github.com/mulesoft/api-console/files/444015/library2.raml.txt)

**Comment by sichvoge** [comment]
any image that you can share so that we understand your problem a bit better?

**Comment by davisskchan** [comment]
In the api.raml

#%RAML 1.0
title: Eagle Eye Public Wallet API
version: 1.0

baseUri: https:// www.eagleeyesolutions.co.uk:443
#baseUriParameters:

uses:
  eeEntity: schemas/eeEntityLib.v1.0.raml
  eePayload: schemas/eePayloadLib.v1.0.raml
  eeResource: resourceTypes/eeResourceLib.v1.0.raml
  eeTraits: traits/eeTraitsLib.v1.0.raml
........

        patch:
          displayName: Update transaction details for a specific wallet.
          description: This API method allows the calling application to update a Transaction details, identified by a Transaction ID for a specific wallet.
          body:
            type: eePayload.walletTransactionPatchPayload

And in the eePayloadLib.v1.0.raml

#%RAML 1.0 Library

uses:
  ee: eeEntityLib.v1.0.raml

types:
......
  walletTransactionPatchPayload:
    properties:
      expiryDate:
        type: datetime
        description: The date that the transaction will expire.
      accounts: ee.walletTransactionAccountsEntity
      basket: ee.walletTransactionBasketEntity
      meta: ee.metaEntity

and in eeEntityLib.v1.0.raml

  walletTransactionAccountsEntity:
    type: array
    items:
      properties:
        accountId:
          type: string
          description: Account ID
        accountTransactionId:
          type: string
          description: Account Transaction ID

When displayed in the api-console types, it is parsed as the jpg attached.

![api-console-type](https://cloud.githubusercontent.com/assets/18424321/18174870/2fa69c20-703d-11e6-944d-b2d05bba64db.jpg)

**Comment by sichvoge** [comment]
This might be related to the fact that libraries are not fully expanded. We need to check if the new parser version will fix the issue.

**Comment by sichvoge** [comment]
This is fixed with the new API console version v4.

![image](https://user-images.githubusercontent.com/498114/27530918-909ecaa2-5a52-11e7-986d-a69b23370333.png)

All properties are shown.

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
