### ISSUE TITLE
API Console does not change example when mediaType is changed.

### ISSUE THREAD

**Issue by brettkroeder** [mulesoft/api-console#329]
I changed the mediaType but the example did NOT change.
<img width="508" alt="anypoint_platform_for_apis___api_administration___customer_-_1_2___designer" src="https://cloud.githubusercontent.com/assets/8449580/18183997/e110d328-7064-11e6-92f7-bbf659ada159.png">

**Comment by sichvoge** [comment]
Can you post a small reproducible RAML snippet @brettkroeder, pls.

**Comment by brettkroeder** [comment]
Here is the [Portal link](https://anypoint.mulesoft.com/apiplatform/mulesoft-314/#/portals/organizations/ccad78bd-5e3c-49d8-9ecf-231dc14f4f89/apis/46111/versions/80525/pages/118647)

**Comment by sichvoge** [comment]
Thanks. I identified the issue already. Currently the console does not really convert the YAML example into both JSON and XML. That's obviously an issue, but the question is how much you support in here. Examples mare easy, speaking about converting schemas is different. For example, what do you expect to haven in the following example:

```yaml
#%RAML 1.0
title: Customer API
version: 1.0

mediaType: [ application/xml, application/json ]

/customers:
  /all:
    get:
      responses:
        200:
          body:
            type: |
              {
                ... // any JSON schema
              }
            example: |
              {
                "name": "Brett"
              }
```

Do you expect any client, in this case the console, to show you XML and XSD as well when you switch between the media types?

**Comment by brettkroeder** [comment]
I would not expect it to cover explicit schemas and examples. But I do expect it to switch when defined with RAML DataTypes and NamedExamples.

**Comment by brettkroeder** [comment]
Just like it does when I Try It

**Comment by sichvoge** [comment]
Agree. I put that as an enhancement request. Thanks Brett. 

Summary:

Inside the API Console, I should be able to switch between XML and JSON, and see the examples that has been defined in YAML in their respective serialization format.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
