### ISSUE TITLE
Display examples?

### ISSUE THREAD

**Issue by 4hopp** [mulesoft/api-console#334]
Hello,
Why does the current repository version not show any examples?

RAML file used: https://jooby-spec.herokuapp.com/raml/api.raml

The version deployed at https://jooby-spec.herokuapp.com/raml does show the examples, however. (I do not know the version number, unfortunately.) 

Is there an option for enabling examples or something?
Thanks.

**Comment by sichvoge** [comment]
The file you linked does not contain any examples. Can you pls double check?

**Comment by 4hopp** [comment]
Are examples generated from the specified structure or do they have to be given explicitely? In case of the latter, the ticket can be closed.

**Comment by sichvoge** [comment]
Its the latter. Thanks!
