### ISSUE TITLE
doesn't substitute template variable in !include statement

### ISSUE THREAD

**Issue by vorberohus** [mulesoft/api-console#340]
Hello, in the code below resourcePathName in the !include command doesn't get substituted with the resource name and result in a url like this http://127.0.0.1:9292/specs/api/specs/%3C%3CresourcePathName%3E%3E/create.markdown
```
collection:
  post:
    description: !include specs/<<resourcePathName>>/create.markdown
    securedBy: [passthrough]
    body:
      type: <<resourcePathName|!singularize>>
    responses:
      200:
        body:
          example: |
            <<exampleCreate>>

```

**Comment by sichvoge** [comment]
Hi @vorberohus, I am afraid to tell you but parameter do not work with `!include` ;)

**Comment by vorberohus** [comment]
HI @sichvoge sorry then, but it would have been a nice feature )
