### ISSUE TITLE
Repository should include compiled sass

### ISSUE THREAD

**Issue by joeyfigaro** [mulesoft/api-console#341]
I don't care about modifying the styles, and I don't have the sass gem installed. It'd be great if this project were able to stand up with defaults, since all I want to do is generate documentation.

**Comment by sichvoge** [comment]
Guess the way how the new console works will support your use case. There is a CLI tool that you will be able to install via "npm" and you can really just generate documentation. Look at [this](https://github.com/mulesoft/api-console/tree/release/4.0.0#build-tools) and let me know if that works for you.

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
