### ISSUE TITLE
Configuration flags are not taken into account

### ISSUE THREAD

**Issue by ddidier** [mulesoft/api-console#344]
Hi,
With the v3.0.8 configuration flags such as `disable-try-it` have no effect. Here's my `index.html`:

``` html
<!doctype html>

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>API Console</title>
  <link href="styles/api-console-light-theme.css" rel="stylesheet" class="theme">
</head>

<body ng-app="ramlConsoleApp" ng-cloak>
  <script src="scripts/api-console-vendor.js"></script>
  <script src="scripts/api-console.js"></script>
  <script>
    $.noConflict();
  </script>
  <raml-console-loader
    src="apis/main.raml"
    disable-raml-client-generator
    disable-theme-switcher
    disable-try-it
    resources-collapsed>
  </raml-console-loader>
</body>

</html>
```

**Comment by skray** [comment]
It looks like with the addition of the `raml-console-loader` wrapper around the `raml-console` directive, options that were previously handled through directive attributes are now checked through the `options` scope binding.

Replacing the individual attributes in the `raml-console-loader` tag with this options block worked for me:

```html
<raml-console-loader
    src="apis/main.raml"
    options="{ disableRamlClientGenerator: true, disableThemeSwitcher: true, disableTryIt: true, resourcesCollapsed: true}">
</raml-console-loader>
```

See https://github.com/mulesoft/api-console/blob/master/src/app/directives/raml-console.js#L53 to see how these are actually checked.

**Comment by ddidier** [comment]
Thank you, that's working. Is it the intended behavior or will you fix it?

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
