### ISSUE TITLE
schema pattern with "|" makes the entire included schema disappear in the documentation

### ISSUE THREAD

**Issue by gianebao** [mulesoft/api-console#357]
With the example below, when I change the regex to ones without |, it works ok.

```
...
"date": {
  "type": "string",
  "pattern": "[0-9]{4}\\-(0[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])"       
}
```

**Comment by Relequestual** [comment]
Suggest closing in favour of https://github.com/mulesoft/api-console/issues/379 as it's almost identical and has a fix awaiting being made into a pull request

**Comment by nmarinel01** [comment]
Closing in favour of #379
