### ISSUE TITLE
Constantia font causing strange display issue in Markdown included table

### ISSUE THREAD

**Issue by marksou** [mulesoft/api-console#358]
In resource descriptions, we are including markdown files including tables. The heading row text in the table does not display the letter 'f' or the question mark character, replacing them with a swirl. 

Anywhere else in the markdown file, this does not happen, just table header rows. If you remove the Constantia font from the CSS, the header row displays these characters correctly.

See attached: 
![api_console_font_issue](https://cloud.githubusercontent.com/assets/1983518/19963099/daae89ce-a1b2-11e6-9b86-8638fa0ecfd4.png)
![api_console_font_issue2](https://cloud.githubusercontent.com/assets/1983518/19963100/dab06bf4-a1b2-11e6-93f6-c20645f9ba8c.png)

**Comment by nmarinel01** [comment]
Hi @marksou !
Can you please attach raml file and markdown files in order to verify if this is still an issue ?
Regards !

**Comment by nmarinel01** [comment]
Please reopen in case the issue is still present and attach the raml that reproduces the problem.
Regards !
