### ISSUE TITLE
'Try It' should provide templates based on JSON Schema

### ISSUE THREAD

**Issue by bripkens** [mulesoft/api-console#36]
We can define the expected request body through RAML and I think that the console could provide some kind of template based on the JSON schema (of course only if some JSON content type is selected).

Example:
I have the following very basic JSON Schema:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "collection_command",
  "description": "Writable collection representation",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    }
  },
  "required": ["name"],
  "additionalProperties": false
}
```

I switch to 'Try It' in the web console and choose `application/json` as my content type. The web console automatically inserts the following basic template:

```
{
  "name": "TODO",
  "description: "TODO (optional)"
}
```

Now I don't propose to go crazy about this and support the vast amount of features that  JSON schema supports, e.g. patternProperties, but a simple template generation for named properties (given the schema type is `object`) is possible.

Thinking further: This could even be extended to other schema types (XML), but I believe that JSON schemas would be a good place to start.

I would be willing to contribute if you find this feature acceptable for the api-console project.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
