### ISSUE TITLE
Try it tab: the boolean inputs are rendered as "false" but they are resolved to "true" when making a request

### ISSUE THREAD

**Issue by monami555** [mulesoft/api-console#361]
![screen shot 2016-11-08 at 08 50 54](https://cloud.githubusercontent.com/assets/1808940/20097131/37f669d2-a5ad-11e6-9532-4189abb3ab6c.png)
Hello,

We have discovered a problem in API Console. This is our RAML snippet:

      /bla:
        put:
          body:
            application/octet-stream:
              schema:
          queryParameters:
            validateTemplate:
              example: true
              type: boolean
              default: false
              required: false

When the `validateTemplate` renders in API Console, it shows unchecked, but when I try to make a request, it sets this query parameter to "true" (see the screenshot). In order to force the "false" value, I have to first check it and then uncheck it again.

It seems that the initial value is taken from the "example" field, and is updated with the rendered value only after clicking on the checkbox. This is quite confusing, since as long as the checkbox is rendered as not checked, I would expect the request to be made with a value "false".

We are using version 2.0.5. Please let me know if this could be addressed.

**Comment by sichvoge** [comment]
Can you try again with the latest version? 

![image](https://cloud.githubusercontent.com/assets/498114/20606682/8a8485c0-b26a-11e6-8a50-263970f48ddd.png)

It works for me.

**Comment by sichvoge** [comment]
Hi. I guess you are using RAML 0.8? Its a very old version and I wonder if the current 3.0.11 works for you?

**Comment by sichvoge** [comment]
OK, that also happens with 3.0.11! I will have someone from the team looking at it. Thanks!

**Comment by sichvoge** [comment]
This is actually fixed in the new console v4 in [this branch](https://github.com/mulesoft/api-console/tree/release/4.0.0). 

The only thing I would say is that the default value is not propagated if your parameter is not required. That is on purpose to avoid having strange values inside the URL.

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
