### ISSUE TITLE
Does api-console interpret inline html in the RAML - especially for <table> tags?

### ISSUE THREAD

**Issue by bschrammCOV** [mulesoft/api-console#362]

**Comment by bschrammCOV** [comment]
I have the following code in a RAML file. Will this table be rendered correctly in api-console?
` <style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
}
th {
    text-align:right;
}
</style>
</
 <body>

 <table>
            <h4>Cui.js Calls</h4>
            <tr>
                <th text-align: right;>Command</th>
                <td>{ cmd: "search",</td>
            </tr>
            <tr>
                <th text-align: right;>Endpoint</th>
                <td>call: "/sample/v1/samples?analyticsSample={analyticsTestId}&sortBy=-creation",</td>
            </tr>
            <tr>
                <th text-align: right;>Function</th>
                <td>type: "GET",</td>
            </tr>
			 <tr>
                <th text-align: right;>Data Format</th>
                <td>accepts: "application/samplejson.v1+json",</td>
            </tr>
			 <tr>
                <th text-align: right;>Content Type</th>
                <td>"application/moresamplejson.v1+json" }</td>
            </tr>
        </table>
		</body>`

**Comment by jarrodek** [comment]
If you use markdown it will. For example:
```
description: |
  **Cui.js Calls**
  | Label | Description |
  | --- | --- |
  | **Command** | { cmd: "search" .... |
  | Endpoint | / |
  ... 
```

**Comment by nmarinel01** [comment]
Hi @jarrodek ! Thanks for your suggestion. @bschrammCOV Did this suggestion help you ? 

Closing this issue , but please, feel free to reopen if applies.
Regards !
