### ISSUE TITLE
Release Roadmap?

### ISSUE THREAD

**Issue by deadratfink** [mulesoft/api-console#364]
Hi,

first, thx for the cool tool! Just wanted to know when the next publish to npm could be expected (the current _published_ is still be _v3.0.4_). We want to make use of latest fixes and always referencing dependencies to master (or tag in Github) or in general not getting modules from an npm proxy isn't a good idea for our production software which integrates the api-console. So, any hints for us...?

Thx and best regards
Jens

**Comment by sichvoge** [comment]
Hi Jens,

We currently plan to make an npm release around December 3. 

Christian

**Comment by deadratfink** [comment]
Cool, thx for the info, keep the good work! Regards, Jens

**Comment by thomaschaaf** [comment]
@sichvoge sadly 3.0.4 is still the current npm release. What is the plan right now :)

**Comment by deadratfink** [comment]
Reopened because this is still an issue for us.

**Comment by sichvoge** [comment]
Can you look again please. Sorry for the delay.

**Comment by deadratfink** [comment]
Cool, THX for publishing! Closing this :-)
