### ISSUE TITLE
Any way to render annotations?

### ISSUE THREAD

**Issue by memelet** [mulesoft/api-console#371]
I am trying to define our security permissions in the api docs, eg

```
/auth:
  /admin:
    /users:
      get:
        (permissions): users:read
```

Custom middleware (maybe a raml x-other security, but that is pretty limited right now) would read the annotation and perform the permission check.

But it seems annotations have no way to be rendered as part of the api-console.

**Comment by sichvoge** [comment]
currently we don't render annotation, indeed. as we redesign the console (see #328) we don't plan to include them into the latest version.

**Comment by nmarinel01** [comment]
Will be introduced into the next major version
Regards

**Comment by jarrodek** [comment]
Fixed by:
* https://github.com/advanced-rest-client/raml-docs-method-viewer/pull/5/
* https://github.com/advanced-rest-client/raml-docs-resource-viewer/commit/262bc81dd607d5928ae890a6f8f333270b14fa2d
* https://github.com/advanced-rest-client/docs-parameters-table/commit/22bf32fc964fd927a97e27848020a75007b52bbb

**Comment by sichvoge** [comment]
@jarrodek I am sure that there are more annotations. Are there any other annotations that are important to show? Maybe ALL are actually important :) Have a look [here](https://github.com/raml2html/raml2html/issues/204) for the discussion we have on raml2html.

**Comment by jarrodek** [comment]
It renders annotation for:
* method
* resource
* type property
* type

I think that it basically covers all basis.

**Comment by sichvoge** [comment]
can you add some example images on how that looks like. easier for later to understand our conversation in this ticket.

**Comment by jarrodek** [comment]
Resource:
![image](https://user-images.githubusercontent.com/3320020/27873869-73e95508-61a5-11e7-9b8c-7bb91bda9529.png)

Method:
![image](https://user-images.githubusercontent.com/3320020/27873885-815feda0-61a5-11e7-8b0b-d327165da7ea.png)

Headers:
![image](https://user-images.githubusercontent.com/3320020/27873917-9f603e86-61a5-11e7-8cdf-401a506fcc26.png)

Query parameters:
![image](https://user-images.githubusercontent.com/3320020/27874014-f3c108d4-61a5-11e7-99d1-70a1114680da.png)

I can only see that it is missing in the body viewer (request or response but it's handled by the same element).
