### ISSUE TITLE
How to preserve Authorization header entry across try-it uses?

### ISSUE THREAD

**Issue by memelet** [mulesoft/api-console#373]
For secured APIs (in our example using JWT bearer token via Authorization header) it seems that the user of the api-console must paste the token in the Authorization header entry field for every try-it. 

Can there be some way for the user to set a default value to be used for a header (or url parameter) across try-its?

**Comment by cm-tm** [comment]
This would be super useful. As the token persists when opening a different endpoint, it would be great if it was automatically added to the header (best option) or alternatively if there was at least an easier way add it to the header, for example with an extra button near the token (less neat option).

Right now, one needs to:

1. Copy the token.
2. Switch to headers.
3. Type "Bearer".
4. Paste token.

Do it a couple of times and it quickly gets tiresome.

**Comment by jarrodek** [comment]
Hi,

thank you for your comment. 
This will be resolved in version 5 that is coming soon. After we finish documenting it and update build tools we will release new version that has a lot of bug fixes and improvements.

**Comment by jarrodek** [comment]
This was fixed in version 5 and it stays fixed in 6.0.0
