### ISSUE TITLE
When using oauth2 password grant, how is the username, password entered?

### ISSUE THREAD

**Issue by memelet** [mulesoft/api-console#375]
That is, there are no fields for the credentials. Only the client_id and client_secret.

**Comment by clhodapp** [comment]
It's presently broken. See https://github.com/mulesoft/api-console/pull/356

**Comment by memelet** [comment]
Anything I can do help get that merged?

**Comment by clhodapp** [comment]
Not that I know of. I'd say "Draw enough attention to it to get someone from Mulesoft to look at it" but I think we're kind of doing as good a job of that as can be done without being annoying.

**Comment by nmarinel01** [comment]
Closing on behalf of #356
