### ISSUE TITLE
Problem: Unable to display schemas that contain patterns that contain a '|'

### ISSUE THREAD

**Issue by HughPowell** [mulesoft/api-console#379]
**Reproduction**
* Start a python server from api-console/dist as follows:
python -m SimpleHTTPServer 9950
* Navigate to localhost:9950 in your browser (I've tested this with Chrome and Firefox on a Mac)
* Paste in the following RAML (or have it served from a URL):

```
#%RAML 0.8
---
title: Pattern that includes vertical bar test
baseUri: http://localhost:3000/demo

/test:
    post:
        description: Demonstrates failure when pattern includes vertical bar
        body:
            application/json:
                schema: |
                    {
                        "title": "Test schema",
                        "description": "Schema with pattern with vertical bar",
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "type": "object",
                        "properties": {
                            "prop": {
                                "type": "string",
                                "pattern": "a|b"
                            }
                        },
                        require["prop"]
                    }

```

**Result**
Notice that when the page loads and the "POST" tab is clicked no "Show Schema" button is displayed.
Changing the pattern to "ab" allows the "Show Schema" button to be displayed.
Simplifying the if/else block starting at line 1043 of the identifyBodyType function in api-console.js from

```
if (aType.indexOf('|') !== -1) {
  $scope.isSchema = false;
  $scope.isType = true;
} else {
  $scope.definition = aType;
}
```
to
```
$scope.definition = aType;
```

solves this particular issue, but I suspect has implications I'm not aware of.

**Comment by Relequestual** [comment]
I'm also experiencing this problem. Real shame when I'm just trying to get to use api-console, and specifically want to use it with JSON Schema elements... Looking like that's currently just not possible, and untested =/

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
