### ISSUE TITLE
npm WARN grunt-karma@0.10.1 requires a peer of karma@~0.12.0 but none was installed.

### ISSUE THREAD

**Issue by Relequestual** [mulesoft/api-console#383]
When running `npm install` as per the setup process in the readme, I am met with the following error...

`npm WARN grunt-karma@0.10.1 requires a peer of karma@~0.12.0 but none was installed.`

It took me a while, but eventually I tried to do npm install karma at that specific version, which fixed the issue.
I don't use node, and I'm not familiar with npm, but it sounds like there's a dependancy problem, and I get the feeling it's here and not at grunt-karma.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
