### ISSUE TITLE
Node 0.10 is now no longer maintained. Travis script should test with v4

### ISSUE THREAD

**Issue by Relequestual** [mulesoft/api-console#384]
Node LTS plan https://github.com/nodejs/LTS
0.10 is no longer maintained, 0.12 won't last long. Does it make sense to move the tests to v4?

I currently don't think the tests would pass for v6 or v7, due to some outstanding issues on v6 and my just now test on v7.

As someone new to using node in general, I installed the latest, and then tried to use api-console, and have had a really rough ride, and still can't grunt the project because of #275. That's a showstopper that's over 6 months old... =/

**Comment by jarrodek** [comment]
Latest release of API Console works with node >= 10
