### ISSUE TITLE
'Unable to resolve type' error

### ISSUE THREAD

**Issue by KevinMitchell** [mulesoft/api-console#393]
Suppose I define a datatype `Customer` in a test library; the details aren’t important.
 
I then define a `collection` resource type as
 
    #%RAML 1.0 ResourceType
 
    get?:
      responses:
        200:
          body:
            application/json:
              type: <<typeName>>[]
 
    post?:
      body:
        application/json:
          type: <<typeName>>
 
Finally, in my main file I define
 
    ...
    resourceTypes:
      collection: !include resources/collection.raml
 
    /customers:
      type: { collection: {typeName : test.Customer } }
      #get:
 
With the `get:` commented out I get
 
    [error] Reference: ‘test.Customer’ can not be resolved.
 
If I uncomment the `get:` it’s happy, i.e. it manages to resolve the type.  I’ve encountered a number of problems in this area, sometimes generating this error, sometimes displaying nothing at all.  Hopefully they all have the same root cause...

**Comment by sichvoge** [comment]
Might that be a parser problem instead of the console?

**Comment by nmarinel01** [comment]
https://github.com/raml-org/raml-js-parser-2/issues/640

**Comment by carowright** [comment]
Fix available in [v3.0.17](https://github.com/mulesoft/api-console/releases/tag/v3.0.17)
