### ISSUE TITLE
Try it response is cut-off/overflow:hidden

### ISSUE THREAD

**Issue by treffynnon** [mulesoft/api-console#402]
This is similar to issue #87 in many ways.

I've added a simple override in my console.html file for now.

```html
  <style>
    /* get api console/try it to resize when response comes in
     * without this it is cut off (overflow: hidden)
     */
    .raml-console-sidebar-flex-wrapper,
    .raml-console-sidebar-content {
      height: inherit;
    }
    .raml-console-sidebar-content-wrapper {
      max-height: inherit;
    }
  </style>
```

Without this the Try-It section of the documentation does not resize when the response comes back from a call. The details are simply cut off.

I am using Chrome 56.0.2924.87 on OSX, but it seems to affect other operating systems and browsers too.

**Comment by sichvoge** [comment]
Have you tried the new console branch you can find [here](https://github.com/mulesoft/api-console/tree/release/4.0.0) with this to validate you still have the issue?

**Comment by treffynnon** [comment]
This issue was against v3.0.13. Looking at the v4 branch the code is entirely different so I'd guess that it does not apply there.

**Comment by sichvoge** [comment]
Can you check it out and let us know if that works for you, please? We plan to release this today or tomorrow.

**Comment by treffynnon** [comment]
I just tried to follow the [build instructions<sup>DOCs</sup>](https://github.com/mulesoft/api-console/tree/release/4.0.0#preview-and-development) but I am getting the following from `npm i -g polymer-cli`:

```
npm install -g polymer-cli
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path but we hope you'll help us figure out one.
npm ERR! code E404
npm ERR! 404 Not Found: @types/escodegen@^0.0.2
```

So I cannot get it running and therefore cannot test. I had a quick look to see if others were having issues, but didn't see anything.

I am running Node 8.1.2 and npm 5.0.4 if that helps.

**Comment by sichvoge** [comment]
@treffynnon can you install https://github.com/mulesoft-labs/api-console-cli instead? It's a little handy tool that makes generating the console so much easier.

Usually what I do is to run `python -m SimpleHTTPServer` on the generated `build` folder. That HTTP server was installed on my MacBook already. If you have some other HTTP server to serve the console, fair enough :)

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
