### ISSUE TITLE
Auto-load .raml document results in a blank page

### ISSUE THREAD

**Issue by madjufra** [mulesoft/api-console#404]
Hi,

I am trying to create an API with APIConsole. I have created the .raml document and I can load it just fine if I paste the document into the APIConsole web interface that is found in the "dist" folder.

Then I try to follow the instructions to get it to auto load using the <raml-console></raml-console> tag, but that results in a blank page. 

Here is what I have done:

I have copied the entire dist folder and altered the index.html to the following:

    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>API Console</title>
      <link href="styles/api-console-light-theme.css" rel="stylesheet" class="theme">
    </head>
    <body ng-app="ramlConsoleApp" ng-cloak class="raml-console-body">
      <script src="scripts/api-console-vendor.js"></script>
      <script src="scripts/api-console.js"></script>
      <script>
        $.noConflict();
      </script>
      <div style="overflow: auto; position: relative">
        <raml-console src="usermanagement.raml" with-root-documentation></raml-console>
      </div>
    </body>
    </html>

Then I have copied the "usermanagement.raml" into the dist folder.

Furthermore I have tried setting it up in IIS with a web.config that allows download of raml documents and allows CORS. It looks like this:

    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <system.webServer>
          <httpProtocol>
            <customHeaders>
              <add name="Access-Control-Allow-Origin" value="*" />
            </customHeaders>
          </httpProtocol>
            <staticContent>
                <mimeMap fileExtension=".raml" mimeType="application/raml+yaml" />
                <mimeMap fileExtension=".schema" mimeType="application/schema+json" />
            </staticContent>
        </system.webServer>
    </configuration> 

This results in a blank page on which I can only see the header of the api documentation. (Please note I have tested in Chrome and Firefox)

Any help is much appreciated as the APIConsole is awesome and I really want to get it to work.

Thanks in advance,
Magnus

**Comment by n0tel** [comment]
Same problem. I also tried <raml-console-loader src="path/to/raml"></raml-console-loader> but without success.

**Comment by CharanVaishnav** [comment]
I am facing same issue , any solution for this issue ?

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
