### ISSUE TITLE
Is it possible to hide "show more" link in description, so that the text is always visible?

### ISSUE THREAD

**Issue by ITemplate** [mulesoft/api-console#411]
Example:

title: Whatever
description: |
  This is a test
  This is more test
  This is even more test

The console will break and show a "Show more" link. I would like this text to be visible always - and possible so that there is no link at all.

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
