### ISSUE TITLE
Show examples for types

### ISSUE THREAD

**Issue by bennidi** [mulesoft/api-console#420]
I would like to see the console show the examples when provided in type definitions (either for the entire type or single properties).

**Comment by nmarinel01** [comment]
Thanks for reporting. Reproducible.

**Comment by bennidi** [comment]
Nice. I was worried that my description was too much of a one-liner :+1:

**Comment by carowright** [comment]
Fix available in [v3.0.17](https://github.com/mulesoft/api-console/releases/tag/v3.0.17)
