### ISSUE TITLE
The `RAML Console` is displayed, after already being loaded

### ISSUE THREAD

**Issue by GeertHauwaerts** [mulesoft/api-console#426]
When feeding a RAML file via the `src` tag, the `RAML Console` is still displayed after rendering.

Example: https://thinfactory.github.io/veeam-cloud-connect-api/

**Comment by sichvoge** [comment]
Really strange behavior indeed. Thanks for raising it and we will look at this. 

Have you had a chance to look at the current version of our improved console? There is a [branch](https://github.com/mulesoft/api-console/tree/release/4.0.0) you can try out. Setup should be fairly simple, but we really appreciate any feedback.

**Comment by nmarinel01** [comment]
Reproducible, thanks for reporting.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
