### ISSUE TITLE
After closing a root-level method section, it can't be re-expanded

### ISSUE THREAD

**Issue by lsimoneau** [mulesoft/api-console#442]
This only affects methods defined at the root of a resource. Using the twitter example in the `/examples` folder, `/direct_messages{mediaTypeExtension}` allows you to reproduce this issue.

1. Open the API console using the twitter example.
2. Click the `GET` method next to `/direct_messages{mediaTypeExtension}`
3. Click the `x Close`  link to collapse the docs for this request.
4. Click the `GET` method next to `/direct_messages{mediaTypeExtension}` again.

Expected:

* The section expands again

Actual:

* Nothing happens

**Comment by lsimoneau** [comment]
This is even easier to reproduce with the `github` example, as almost every resource has requests defined at the root.

**Comment by carowright** [comment]
Hi @lsimoneau, thanks for reporting. This fix is available in [v3.0.17](https://github.com/mulesoft/api-console/releases/tag/v3.0.17)
