### ISSUE TITLE
Log api errors on console.log

### ISSUE THREAD

**Issue by bennidi** [mulesoft/api-console#452]
I have been working with larger RAML files lately and sometimes the console just rejected a file with a "Api contains errors" message. It's super hard to find the quotes at line 659 that make a RAML parser fail...

It would be super helpful if the errors emitted by the underlying raml-parser would be either logged to console or even displayed in the browser (there could be a show errors option).

There is raml-initializer.js and around line 90

```js

var success = true;
var issues = api.errors; // errors and warnings
if (issues && issues.length > 0) {
  success = issues.filter(function (issue) {
      return !issue.isWarning;
    }).length === 0;
}

if (success) {
  $scope.vm.raml = api.specification;
} else {
  console.log(JSON.stringify(issues)); // this was my quick fix to see the errors
  // adding them to vm.error did not change anything
  // probably the handler of vm.error would be the right place to add logging
  // and then here just set { message: 'Api contains errors.', errors:issues};
  $scope.vm.error           = { message: 'Api contains errors.'};
  $scope.vm.codeMirror.lint = lintFromError(issues);

```

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
