### ISSUE TITLE
Properties with regexp keys does not display in types

### ISSUE THREAD

**Issue by gianebao** [mulesoft/api-console#466]
Following

```
#%RAML 1.0
title: My API With Types
types:
  Person:
    properties:
      name:
        required: true
        type: string
      age:
        required: false
        type: number
      /^note\d+$/: # restrict any properties whose keys start with "note"
                   # followed by a string of one or more digits
        type: string
```

https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#property-declarations

The regular expression does not appear in the type section.

**Comment by jarrodek** [comment]
@sichvoge I need some guidance here. I'm not sure how the console should handle this information.

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
