### ISSUE TITLE
TryIt URL does not change path parameter

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#484]
For the following RAML

```yaml
#%RAML 1.0
title: Programming Language Populariy
version: 1
baseUri: http://example.com
types: 
  language:
    type: string
    description: A programming language name
    enum: [Ruby, Python, JavaScript]
  country:
    type: string
    description: A country name
    examples:
      oneword: Canada
      acronym: USA
      withspace: United Kingdom
/popularity/{lang}/{place}/{year}:
  description: Yearly populaity of a language in a geographical region
  uriParameters:
    lang:
      type: language
    place:
      type: country
    year:
      type: number
      description: Year
      examples:
        earliest: 2000
        latest: 2015
  get:
    responses:
      200:
        body:
          application/json:
            example: {"lang": "Ruby", "place": "USA", "popularity": "High"}
```

Navigate to the TryIt view. See that the URL still contains path parameters `{}` despite that there are values for these parameter selected already (except for the `year` parameter).

![image](https://user-images.githubusercontent.com/498114/27532675-f119eb2c-5a58-11e7-8619-b5417f676b60.png)

Changing, for example, the language parameter has no effect on the URL either.

**Comment by lbauret** [comment]
Hi! Is there any update concerning this issue? Thank you in advance.

**Comment by jarrodek** [comment]
Hi @lbauret 
I'm working on this issue. However it is more complex than I initially anticipated.
The fix will be released in coming days.
