### ISSUE TITLE
Query parameters: example values are not sent, then try it fails with 400 bad request

### ISSUE THREAD

**Issue by nmarinel01** [mulesoft/api-console#488]
Steps to reproduce:
1. Import attached project 
[testExamples-v1.zip](https://github.com/mulesoft/api-console/files/1102743/testExamples-v1.zip)

2. Select api.raml and enable mocking server
3. In console navigate to resource CASE1_...
4. click on try it

The query parameter has an example value that seems not to be send making the call fail

**Comment by jarrodek** [comment]
This is the same issue as #484
I'm trying to fix that now but it looks like a serious bug in data exchange between URL editor and query / URI parameters panel.
Trying to fix that now.

**Comment by lbauret** [comment]
Hi @jarrodek. Is there any update concerning this issue?

**Comment by jarrodek** [comment]
Fixed with: https://github.com/advanced-rest-client/raml-request-parameters-editor/commit/58da8413366f4806f948bf9ca8651c95525a1c7b
