### ISSUE TITLE
Override input remains hidden for URI Parameters

### ISSUE THREAD

**Issue by cdierkens** [mulesoft/api-console#489]
![image](https://user-images.githubusercontent.com/4812409/27554662-26da6312-5a7d-11e7-8fca-29fa1cde3fbd.png)

![image](https://user-images.githubusercontent.com/4812409/27554674-2e6bb1f8-5a7d-11e7-84cb-9f5e210abd99.png)

![image](https://user-images.githubusercontent.com/4812409/27554703-407ed708-5a7d-11e7-871b-eaea26ae7802.png)

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
