### ISSUE TITLE
Missing space when displaying API version

### ISSUE THREAD

**Issue by nmarinel01** [mulesoft/api-console#492]
Steps to reproduce:
1. Open Console for the following raml spec:
```
#%RAML 1.0
title: my Api
version: 1.0.0
/jwt1:
  get:
    body: 
      application/json:
    responses: 
      200:
        description: OK
        body: 
          application/json:
            example: "success"
```
2. Check next screenshot. There is no space between Version and the version number.
![image](https://user-images.githubusercontent.com/19980188/27605853-4c86e13a-5b54-11e7-840f-044dc3772a73.png)

**Comment by jarrodek** [comment]
Thank you for the issue report.
Soon this component will change and it will be fixed.

**Comment by jarrodek** [comment]
Fixed with https://github.com/advanced-rest-client/raml-summary-view/commit/adcd693488913844b403abcdc09699a0de2db044
