### ISSUE TITLE
An empty string as a default value in the query parameters is not displayed in the documentation

### ISSUE THREAD

**Issue by nektru** [mulesoft/api-console#494]
It's also effects zero integer value.

I'm testing api-console 4.0

**Comment by jarrodek** [comment]
Thank you for the issue report.
The console tests for existing value and not type. It doesn't check if the value actually exists (as a zero or empty string). Though, it's a bug and should not behave this way.

**Comment by jarrodek** [comment]
Fixed by https://github.com/advanced-rest-client/docs-parameters-table/commit/5e766fc2d0caaf82c19077bea7bc5c25acd3d5c8
