### ISSUE TITLE
release 4.0 at npm

### ISSUE THREAD

**Issue by jayS-de** [mulesoft/api-console#495]
The API console has a 4.0 tag which is not available as a version at [npm](https://www.npmjs.com/package/api-console)

**Comment by sichvoge** [comment]
Have you had a chance to look at https://github.com/mulesoft/api-console/issues/328#issuecomment-311501803?

**Comment by jayS-de** [comment]
No didn't saw it. And just tried it at webjars.org with the bower deployment and it works. 👍

**Comment by sichvoge** [comment]
@jayS-de so you think we can close this?

**Comment by jayS-de** [comment]
Also I found it way easier to just use the npm release. As well as the npm release had only the dist files included, which reduced size. I'm fine with closing

**Comment by jarrodek** [comment]
@jayS-de As mentioned in referenced comment, building and adding the console to your projects it's just a matter of single command added to your `package.json` file so no loss here.
