### ISSUE TITLE
Response headers don't show up in the console

### ISSUE THREAD

**Issue by agustinlg** [mulesoft/api-console#499]
Request headers are shown, but not response headers.

![screen shot 2017-07-11 at 5 06 10 pm](https://user-images.githubusercontent.com/1583786/28119153-2edd50fa-66ea-11e7-9286-c234cf3b48dc.png)

**Comment by jarrodek** [comment]
Thanks for the issue report.

**Comment by jarrodek** [comment]
Fixed by:
- https://github.com/advanced-rest-client/docs-parameters-table/commit/162b4945b3c8eb906ae95c83f261693640ef04d9
- https://github.com/advanced-rest-client/raml-docs-response-panel/commit/d2566e8f81ae057a0a9c5ba122ad2a005913e11d
