### ISSUE TITLE
RAML from URL doesn't work

### ISSUE THREAD

**Issue by danielb2** [mulesoft/api-console#50]
I put up a copy of this project on heroku today to demonstrate the issue:

http://raml.herokuapp.com/

If I put in https://raw.githubusercontent.com/kevinrenskers/raml2html/master/example.raml

The URL, it does not work. I've also tried using http://pastie.org with raw content and it also fails.

Furthermore, it would be nice if something like: http://raml.herokuapp.com/?raml_location=https://raw.githubusercontent.com/kevinrenskers/raml2html/master/example.raml

Actually worked so I could share a link to documentation with people directly.

**Comment by clonq** [comment]
Feeding the console from the url e.g. ?raml=/examples/simple.raml seems to be very slow. I takes over 5 seconds on my machine before anything shows up. Is that a known issue?

**Comment by jcenturion** [comment]
@clonq: Are you using the latest version? which browser? version? 

Thanks in advance.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.

**Comment by danielb2** [comment]
When I filed the ticket 6 (!!!) years ago, version 6 wasn't available 😉

**Comment by jarrodek** [comment]
I know. I wasn't working on this project either :) I am cleaning up stale issues. Apologies.
