### ISSUE TITLE
Schema is not displayed in console

### ISSUE THREAD

**Issue by jarrodek** [mulesoft/api-console#503]
Following RAML do not serves schema content:

```
#%RAML 0.8
baseUri: https://mocksvc.devx.mulesoft.com/mocks/9fc066e8-0160-4dea-bc15-41a6d6a6d57b #
title: schema example
/resource:
  post:
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "prop1" : "string”",
                "prop2" : "boolean"
              }

```

**Comment by WoZ** [comment]
Experiencing the same problem with RAML 0.8. Examples don't work too.

**Comment by WoZ** [comment]
I think this bug should be marked as critical. It blocks usage of API Console.

**Comment by jarrodek** [comment]
@WoZ it already have milestone attached meaning it will be fix until end of next week.

**Comment by glodieu** [comment]
Hi @jarrodek There are two fixes in latest API console version that we need it for our GA release this Saturday but we found this new one #503. Could be possible to get a fix ASAP? Thanks.
