### ISSUE TITLE
Toggle structure display does not work for application/json schemas

### ISSUE THREAD

**Issue by carobazan** [mulesoft/api-console#504]
Verifying bug 503 I've found that the toggle button that shows/displays schema in console does not work for application/json schemas
check importing [accuWeather.zip](https://github.com/mulesoft/api-console/files/1160532/accuWeather.zip)

Then, in console, open resource Weather Alarms By Location Key : get method, scroll down to response and switch to application/json then try to hide/display schema
the icon next to Type application/json does not hide/display upon click action.

<img width="489" alt="screen shot 2017-07-19 at 6 30 09 pm" src="https://user-images.githubusercontent.com/22245749/28390512-bef722a8-6cb0-11e7-82f2-5939293e0123.png">

**Comment by glodieu** [comment]
Hi @jarrodek We found this issue while checking #503 fix.
