### ISSUE TITLE
message for required headers is not visible

### ISSUE THREAD

**Issue by carobazan** [mulesoft/api-console#506]
Check attached image, message stating that headers are required is not completely visible in console

![screen shot 2017-07-20 at 4 42 33 pm](https://user-images.githubusercontent.com/22245749/28435790-e9e5bfaa-6d6a-11e7-880e-9a0d50d145ea.png)

**Comment by jarrodek** [comment]
Please, consult this with Mulesoft design team. The element works as intended according to Mulesoft's components development guidelines.

**Comment by jarrodek** [comment]
This was fixed in 5
