### ISSUE TITLE
After a request, console does not clean 

### ISSUE THREAD

**Issue by eleonoraortega** [mulesoft/api-console#515]
Console is populated Headers, body, etc with previous requests values, so when performing a get, the body of a previous post request is sent causing unexpected behaviour and it is not easy to troubleshooting

## Expected outcome

Every single section should be cleaned after a request, at least when the method and resource change

## Actual outcome

A section used in last request is pre-filled causing a bad request 

## Steps to reproduce

1. Load any api (you can use one included down below)
2. Go to Team > PATCH, make a request
3. Go to Team > DELETE , select body section

## Was this working before?

- [ ] Yes, it was working before
- [ X] No, it was already broken, but it is more obvious as you can see request/response in one place, then you know in previous version that something is pre filled and it is easier to delete it
- [] I don't know / not sure

## Affected browsers

- [x] All
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer <\3
- [ ] Edge
- [ ] Safari
- [ ] Other (please, specify)

NOTE: previous_to_patch_request image is showing the body of delete, before performing a patch request
           patch_body shows the actual body of a patch
           after_patch_request_is prefilled shows the body of delete pre populated with patch body

[api.zip](https://github.com/mulesoft/api-console/files/1212878/api.zip)
<img width="1262" alt="after_patch_request_is prefilled" src="https://user-images.githubusercontent.com/5630419/29144151-42a91c90-7d2e-11e7-8b04-236d5babab53.png">
<img width="1242" alt="patch_body" src="https://user-images.githubusercontent.com/5630419/29144152-42a98824-7d2e-11e7-845f-8e3bc01188cc.png">
<img width="1240" alt="previous_to_patch_request" src="https://user-images.githubusercontent.com/5630419/29144153-42aa8026-7d2e-11e7-9874-9f5c3d57f2e4.png">

**Comment by jarrodek** [comment]
> when performing a get, the body of a previous post request is sent causing unexpected behaviour

This is technically impossible. The request panel uses Fetch API and Fetch API uses the Request object to construct the request. It throws an error when you try to create a `GET` request with `body` property. Therefore this can't ever happen.

Although there's an issue with clearing value from the example. For performance reasons computations are not performed when the value (in this case value of the type) turns `undefined`.  In the element that renders the view a `selectedExample` property is not cleared when type is missing (meaning old value is kept) and therefore value is transferred from previously selected method.

This will be fixed today.
