### ISSUE TITLE
Unable to properly navigate in documentation when documentation comes from an included markdown file

### ISSUE THREAD

**Issue by GuillaumedesPommareSAP** [mulesoft/api-console#516]
Hello,

We are quite extensively documenting our APIs and for that we include a markdown document in the documentation section.
When API console is then displayed, this markdown document seems interpreted. Sections are found and listed in the combobox for selection and navigation (see 1.png).
When you click on the documentation title, full document is displayed (see 2..png). But this is not an obvious navigation path. People will tend to click on a section element.

And here is the bug: when you click on a section, nothing is displayed (see 3.png).

Issue is located in api-console.js, method getDocumentationContent. I see there lines filed with the documentation, a can see that selected equals one entry of the markdown document, for example "# A" but index remains -1 and nothing is displayed.

I don't know what to fix and how to debug further ! You have a test element to reproduce, if needed.
Thanks

![1](https://user-images.githubusercontent.com/26161416/29209430-b78a9adc-7e8e-11e7-9ede-a0a65b842877.png)
![2](https://user-images.githubusercontent.com/26161416/29209432-ba08b5be-7e8e-11e7-8f3f-0b02c475079e.png)
![3](https://user-images.githubusercontent.com/26161416/29209434-bb8a744a-7e8e-11e7-8e7f-8006f9aaa5d9.png)

[test.zip](https://github.com/mulesoft/api-console/files/1217538/test.zip)

**Comment by carowright** [comment]
Hi @GuillaumedesPommareSAP!
Thank you for reporting. I am closing this as the fix is available in version 3.0.26.
