### ISSUE TITLE
After a request, message defined in raml file is not displayed

### ISSUE THREAD

**Issue by eleonoraortega** [mulesoft/api-console#517]
When using the following raml and sending a successful request, the message defined is not displayed in the response.

```
post:
    description: Add a new team to the league
    body:
      application/json:
        type: team
        example: !include examples/team-object-example.raml
    responses:
      201:
        body:
          application/json:
        description: |
          The team has been succesfully created
        headers:
          Location:
            type: string
            description: Location of the newly created team
      409:
        description: |
          The team already exists
```

Expected result:

The message "The team has been succesfully created" should be displayed

Actual result: 
Even when Apikit is sending the message in the response, is not taken into account by console V4

NOTE: Console in 3.x works fine

<img width="1210" alt="screen shot 2017-08-11 at 12 07 09 pm" src="https://user-images.githubusercontent.com/5630419/29219188-b9384470-7e8d-11e7-8b9f-a84ecff95c56.png">

**Comment by jarrodek** [comment]
This Works As Intended.
Response panel shows the response from the server and not documentation for the response. There's no room for that in this view nor it should be repeated in this view.
