### ISSUE TITLE
Resources Hierarchie is gone in Firefox 54.0.1

### ISSUE THREAD

**Issue by zerginator** [mulesoft/api-console#518]
Hi 

I think i found a bug in release 4.0.0

View in Firefox 54.0.1

![2017-08-13 11_55_11-firefox](https://user-images.githubusercontent.com/2770344/29248686-8092c892-801e-11e7-827d-4ebc21cc1cf3.png)

View in Google Chrome Version 60.0.3112.90
![2017-08-13 11_57_22-chrome](https://user-images.githubusercontent.com/2770344/29248690-9f107486-801e-11e7-9ad1-d7066809ba93.png)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. I'll fix that soon.
