### ISSUE TITLE
Loading RAML prolonged on API Console

### ISSUE THREAD

**Issue by aghorpade** [mulesoft/api-console#522]
On Anypoint studio, sometime we have faced issue that RAML get loaded on API Console but if we add something or update on RAML and try to run application then on API Console Loading RAML message gets displayed for infinite time

## Expected outcome

RAML should get loaded on API console

## Actual outcome

Loading RAML screen shown for prolonged time

## Steps to reproduce

1. Create Mule Application using correct RAML and run application
2. while application is running,update RAML .e.g add traits or change datatype of any field
3. re-run application now this time api console shows loading raml for prolonged time

## Was this working before?

- [x] Yes, it was working before

**Comment by jarrodek** [comment]
Is this related to v3? Which version of the console is used in the studio?

**Comment by CharanVaishnav** [comment]
I am facing same issue , any solution for this issue ?

**Comment by jarrodek** [comment]
The same question :) Which version of the console are you using?

**Comment by aghorpade** [comment]
version 3.6.0 for apikit

**Comment by reddepandu** [comment]
Hi Team,

I am using api console 4.0. I am facing on issue on alignment . my requirement is I need to integrate api-console in to iframe. Please suggest me I am new to api-console implementation.
js code i am using:

 var parser = document.querySelector('raml-js-parser');
                         parser.loadApi($scope.defUrl);
                         window.addEventListener('api-parse-ready', function(e) {
                          var enhacer = document.querySelector('raml-json-enhance');
                          enhacer.json = e.detail.json.specification;
                        });
                        window.addEventListener('raml-json-enhance-ready', function(e) {
                        //The e.detail.json contains the final JavaScript object
                         console.log(e.detail.json);
                         var apiConsole = document.querySelector('api-console');
                          apiConsole.raml = e.detail.json;
                        });

html code :

  <raml-js-parser json></raml-js-parser>
    <raml-json-enhance></raml-json-enhance>
    <api-console  ></api-console>

**Comment by jarrodek** [comment]
@reddepandu What do you mean? Is this the same issue? (Loading RAML prolonged on API Console)
If not, please, report another issue. Otherwise, please elaborate.

**Comment by jarrodek** [comment]
This is not the case with last 2 major releases.
