### ISSUE TITLE
Support for HAWK Authentication on Try It feature

### ISSUE THREAD

**Issue by Darius123** [mulesoft/api-console#533]
This would be use-case extension for all of us who have API with HAWK authentication.
Hawk Authentication is becoming more and more popular (https://github.com/hueniverse/hawk), as it covers some disadvantages form OAuth.
UI surface affected would be "Try It" option.
Thanks for supporting it

**Comment by jarrodek** [comment]
@sichvoge what do you think about it? 
I can support in in ARC but not in the API console until it's not a part of RAML spec.

**Comment by jarrodek** [comment]
This authorization scheme won't be supported as long as API specs won't support it. I am closing this ticket.
