### ISSUE TITLE
Cannot install api-console with npm

### ISSUE THREAD

**Issue by FractalWire** [mulesoft/api-console#538]
Hi,

I tried to install api-console using npm as it is specified in the readme file : 

```
sudo npm install -g api-console-cli
```

Unfortunately, it throws me an error : 

> npm ERR! code 128
> npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b 4.0 git://github.com/gulpjs/gulp.git /root/.npm/_cacache/tmp/git-clone-17f09827
> npm ERR! fatal: impossible de créer les répertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-17f09827': Permission non accordée
> npm ERR! 

Here is the log : https://gist.github.com/anonymous/27a97bab310842a93eac4f8ea42caec7

I don't know very well `npm` so I it's hard for me to debug. I searched similar issue, but found none.

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report.
It looks like a problem with permissions and possibly caused by npm.
Can you please try to clean npm cache by running `npm cache clean --force` command. Then reinstall the module: `sudo npm uninstall -g api-console-cli` and `sudo npm i -g api-console-cli`.
Let me know it any of this helps.

**Comment by FractalWire** [comment]
Thanks for your answer.
Unfortunately, it does not resolve my problem. It still fails with the same problem.

I'll try to reinstall npm and let you know.

**Comment by metalcamp** [comment]
Any updates on this?

**Comment by jarrodek** [comment]
@metalcamp 
I can't reproduce the problem. From the error message I can see that the problem is with permissions while dependencies are installed and this is beyond of the scope of this project.
Possible issues are with npm or with gulp package.

**Comment by AMcManigal** [comment]
I had the same problem. I installed without sudo and it worked fine.

**Comment by machaon83** [comment]
I confirm that it works better without 'sudo'.
I can't explain why.

**Comment by jarrodek** [comment]
API Console is now back to NPM with version 6.0.0.
Updated build tools are also available on NPM.
