### ISSUE TITLE
How to disable oauth-1 token calls

### ISSUE THREAD

**Issue by mpindyala** [mulesoft/api-console#54]
We are using zero legged oauth-1 .  Can anybody tell how to disable all the token calls 

/oauth/1/request_token/
/oauth/1/authorize/
/oauth/1/access_token/

I just need signature generation using consumerkey and consumersecret

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
