### ISSUE TITLE
api-console not working on Firefox.

### ISSUE THREAD

**Issue by tracysil** [mulesoft/api-console#544]
Release 4.1.0 is not working on Firefox. Result when loading the document is a blank page. 
Tested Firefox version 55.0.3.

On Chrome dashboard loads fine.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. I can't reproduce the problem. Can you try navigate to http://mulesoft.github.io/api-console/ and check if this version works?

**Comment by ewrogers** [comment]
This issue happens on Firefox Quantum (68.0), works in Chromium.

Same issue happens with the link provided.
