### ISSUE TITLE
`dist` directory disappeared

### ISSUE THREAD

**Issue by jackxxu** [mulesoft/api-console#547]
quick naive question -- until recently, there was a `dist` directory that contains the console ui. how do I regenerate it from the current master?

**Comment by jarrodek** [comment]
Please, use the `api-console-cli` module to generate api-console sources.
```
npm i -g api-console-cli
```
and then 
```
api-console build api.raml
```
Read more about the CLI tool here: https://www.npmjs.com/package/api-console-cli

**Comment by jackxxu** [comment]
@jarrodek  does it mean that I have to generate the console based a predefined raml file? the previous `dist` enables input of an raml file or url..

**Comment by jarrodek** [comment]
In version 4 RAML parser and the module that transforms parser's output into API console data model is optional. You still can do this but it is not "natively" supported by the console. Check my "API selector" demo application based on the API console to do what you referring to: https://github.com/mulesoft/api-console/tree/master/demo/api-selector
