### ISSUE TITLE
property with the name "type" not handled properly

### ISSUE THREAD

**Issue by adjokic** [mulesoft/api-console#552]
I am attaching a simple RAML file which contains a type with one property called "type".
This property is not rendered in the api-console (attaching a screenshot).

Type with property named "type" not rendered correctly
## Expected outcome

There should be a type with a rendered property called "type".

## Actual outcome

All other properties are rendered properly except for the one named "type".

## Steps to reproduce

1. build and serve the raml file from [here](https://pastebin.com/raw/g0kK0T1Q):
2. `api-console build api_type_test.raml -o api_type_test`
3. `api-console serve api_type_test`

## Was this working before?

- [ ] Yes, it was working before
- [ ] No, it was already broken
- [x] I don't know / not sure

## Affected browsers

- [x] All or I don't know
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer <\3
- [ ] Edge
- [ ] Safari
- [ ] Other (please, specify)

**Comment by javbaezga** [comment]
The problem it is in raml2obj dependencie exactly at **node_modules\raml2obj\lib\consistency-helpers.js** file, function **consistentType(obj, types)** line _95_ 
```
} else if (obj.type && obj.type.type) {
```
To fix the problem I replace the line by 
```
} else if (obj.type && obj.type.type && obj.type.name !== 'type') {
```

I opened an issue at [https://github.com/advanced-rest-client/raml2obj/issues/6](https://github.com/advanced-rest-client/raml2obj/issues/6)

**Comment by jarrodek** [comment]
This is fixed by https://github.com/advanced-rest-client/raml2obj/commit/1f5e39acea2593783d73b519b665dffd8c7835e6
