### ISSUE TITLE
Edge support

### ISSUE THREAD

**Issue by martenpalsson** [mulesoft/api-console#554]
Embedding api-console into your application using:
`<link rel="import" href="bower_components/api-console/api-console.html">`
does not currently work in Edge since Html imports are not supported.

Is there another way of embedding api-console into my application or is there a plan to support Edge?
Is api-console supported by the Edge browser?

**Comment by jarrodek** [comment]
Please, see our documentation here: https://github.com/mulesoft/api-console/blob/master/docs/api-console-element.md#setup-polyfills
to learn how to use polyfills.

This is other way of how to use polyfills:
https://github.com/mulesoft/api-console/blob/master/demo/element/index.html#L18
