### ISSUE TITLE
Deep linking not working

### ISSUE THREAD

**Issue by martenpalsson** [mulesoft/api-console#556]
When I try to link to a specific resource in my api-console web-application it renders the standard page successfuly but does not actually select the resource the path specifies. When I click around normally everything works fine.

For example:
When I go to the following url: 
`- http://127.0.0.1:8081/#/docs/resources-0-resources-0`
it shows the same page as this url:
`- http://127.0.0.1:8081`

No error printouts in the console except these depreciations:
```
This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
(anonymous) @ (index):36480
(index):36783 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
(anonymous) @ (index):36783
[Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile.It is now effectively no-op, acting as if it were a descendant combinator. /deep/ combinator will be removed, and will be invalid at M65. You should remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.
(index):45941 Form submission canceled because the form is not connected
```
Running on windows 10
api-console --version => 0.2.12
built using:
`api-console build .\KCSRaml\DocumentWebApp\api.raml --no-optimization`
I have tried with optimizations in place and same result.

**Comment by jarrodek** [comment]
Thank you for the issue report.
I tried the configuration and I can't reproduce the problem. Could you try debug in DevTools the `index.html` page. At the bottom of the page there is a script controlling application bootstrap. Function `apiconsole.app.setInitialRouteData` should set `__initialPage` to `docs` and `__initialPath` to `resources.0.resources.0` (from your example). Could you check if this is happening?

**Comment by martenpalsson** [comment]
I will try this as soon as I am able, but I have one update for now: Everything works fine in FireFox, the problem only exists in Edge and Chrome.

**Comment by martenpalsson** [comment]
I am sorry to say (mmostly for my own sake) that the project this was relevant in is coming to a close so I won't be able to make any more inquiries. So this issue can be closed. Thank you for your help.
