### ISSUE TITLE
Example for raml with json request body&response

### ISSUE THREAD

**Issue by IchordeDionysos** [mulesoft/api-console#566]
Hi,

Is there an example raml file how the json for the example page was generated https://mulesoft.github.io/api-console/#/docs/resources-0-methods-0, so that I can define what the json body looks like it was done here:
https://cl.ly/3a2A3p430z11

This is what it get: https://cl.ly/0T030R1b3b2v

My raml:
```raml
#%RAML 0.8
title: API
version: v1
baseUri: ...
mediaType: [ application/json ]
schemas:
  - someschema: !include /schemas/some-schema.json
/endpoint:
  post:
    description:  ... .
    body:
      application/json:
        schema: someschema
        example: |
          {
            "language": "someLanguageId"
          }
```
some-schema.json
```json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "id": "http://jsonschema.net",
  "required": true,
  "properties": {
    "language": {
      "type": "string",
      "required": true,
      "description": "The language"
    }
  }
}
```

I tried to minic this raml file: https://github.com/raml-apis/GoogleDrive

**Comment by jarrodek** [comment]
This is done by using RAML 1.0 data types by defining a type.
The parser does not produce any information for the schema in this case.
If you think it is unexpected behavior then please report an issue in https://github.com/aml-org/amf
