### ISSUE TITLE
Docker support to run api console

### ISSUE THREAD

**Issue by stevengonsalvez** [mulesoft/api-console#569]
Would be nice to be able to run it on docker , as the host address still reflects as 127.0.0.1 , the port is not able to be exposed. 

Docker file used

```
# This dockerfile is to render the RAML contract as an interactive api-console

FROM alpine

#
# install Node & Git
#
RUN apk add --update nodejs nodejs-npm git \
        && rm -rf /var/cache/apk/*


# Install
RUN npm install -g api-console-cli

# Define working directory.
WORKDIR /data

COPY /resources/contract/raml/ /data/raml

RUN api-console build /data/raml/api.raml

EXPOSE 8081

#RUN api-console serve build/
ENTRYPOINT ["api-console", "serve", "build/"]
```

**Comment by mesca** [comment]
Have you tried to specify the listening address?

``
ENTRYPOINT ["api-console", "serve", "-H", "0.0.0.0", "build"]
``

**Comment by stevengonsalvez** [comment]
I did try that option , but I guess I did it with something else other than the -H. ANyways , it works like a charm now . 
Thanks
