### ISSUE TITLE
Cannot POST /proxy

### ISSUE THREAD

**Issue by davidsmith7** [mulesoft/api-console#57]
I am running mule locally (survivor:8095) and api-console locally (localhost:9000).   As a comparison I also have the console available from the mule application.  When I try an example request using the mule hosted console I get a 201 as desired.  However when I try the same request from the stand-alone api-console I recieve the following error:

Cannot POST /proxy/http://survivor:8095/prioritisation/api/jobs

Looking in the mule logs I get:

2014-06-02 15:38:48 WARN  Router:265 - No matching patterns for URI

So the request is reaching the mule REST service but for some reason it can't match the request.  I'm a bit stumped as to how this is?

**Comment by jcenturion** [comment]
Closing. Same as [Keep getting 404 in API Designer](https://github.com/mulesoft/api-console/issues/51).
