### ISSUE TITLE
Api build fails with "Cannot read property 'tag_name' of undefined" error

### ISSUE THREAD

**Issue by vkuptcov** [mulesoft/api-console#572]
I'm trying to build the HelloWorld example from https://github.com/raml-org/raml-examples/blob/master/helloworld/helloworld.raml inside a docker.
```
$ cat Dockerfile 
FROM node:9.11 as builder

RUN npm install -g api-console-cli

RUN mkdir /api

WORKDIR /api

COPY . .

RUN api-console build api.raml --no-optimization
```
where api.raml is that helloworld example
```
$ cat api.raml 

#%RAML 1.0
title: Hello world # required title

/helloworld: # optional resource
  get: # HTTP method declaration
    responses: # declare a response
      200: # HTTP status code
        body: # declare content of response
          application/json: # media type
            type: | # structural definition of a response (schema or type)
              {
                "title": "Hello world Response",
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  }
                }
              }
            example: | # example of how a response looks
              {
                "message": "Hello world"
              }

```

I'm trying to execute the build
```
$ docker build --no-cache .
```

It fails with the next error:
```
Step 6/6 : RUN api-console build api.raml --no-optimization
 ---> Running in 48435c50a9e9
error:  
error: Cannot read property 'tag_name' of undefined
error: TypeError: Cannot read property 'tag_name' of undefined
    at ApiConsoleSources._downloadFromReleaseInfo (/usr/local/lib/node_modules/api-console-cli/node_modules/api-console-sources-resolver/lib/api-console-sources.js:172:29)
    at githubResolver.getLatestInfo.then (/usr/local/lib/node_modules/api-console-cli/node_modules/api-console-sources-resolver/lib/api-console-sources.js:141:26)
    at <anonymous>
error:  
The command '/bin/sh -c api-console build api.raml --no-optimization' returned a non-zero code: 1
```

I guess it happens because some `api-console` dependencies were updated recently.

**Comment by vkuptcov** [comment]
@mduesterhoeft  Thank you, it works with `api-console build -a api.raml -t "RAML 1.0" -n "5.0.0-preview"`
As I can understand, the `--no-optimization` flag isn't supported in the new `api-console`. Is it possible to build a documentation without optimization?

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report.
Stable version of the API console CLI support version 5 of the console only. If you are using console version 4 please downgrade to previous version Version 5 is not yet published as we are working out some issues related to the console. Stable version has different set of options than 0.x.x.
I am really sorry for this. I should update README to warn about that.

**Comment by jarrodek** [comment]
The console now have dedicated docker image: https://docs.api-console.io/building/docker/
