### ISSUE TITLE
Mule 4 - API Console sending error on Non-200 http status

### ISSUE THREAD

**Issue by alex-fernandez** [mulesoft/api-console#575]
I noticed a problem with API Console (Mule 4).

`<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-apikit-module</artifactId>
			<version>1.1.1</version>
			<classifier>mule-plugin</classifier>
		</dependency>
`
There is an issue displaying the error response payload on non 200 http status. Was this a correct  behaviour? 

<img width="984" alt="screen shot 2018-06-25 at 12 14 51 pm" src="https://user-images.githubusercontent.com/7582277/41827184-74b09f6c-7871-11e8-9359-9c54cc9542b7.png">

**Comment by jarrodek** [comment]
This is fixed in latest release of APIC 5.0.0
