### ISSUE TITLE
Items not visible when uncollapsing in Edge

### ISSUE THREAD

**Issue by dc950** [mulesoft/api-console#579]
The methods are sometimes not visible immediately after uncollapsing an item when using microsoft edge.

## Expected outcome

The methods should be visible after when a resource is uncollapsed

![edge3](https://user-images.githubusercontent.com/9059291/43445431-3bd4d3f4-949e-11e8-9b9d-d1cb9a15bb42.png)
------------------
![edge5](https://user-images.githubusercontent.com/9059291/43445520-7f038652-949e-11e8-8ed9-65a26a28553c.png)

## Actual outcome

The methods are sometimes hidden.  They will show when the area they should be in is hovered over with the cursor, or if another item is opened.

![edge2](https://user-images.githubusercontent.com/9059291/43445423-38cf308c-949e-11e8-98a7-1f84eb1241fd.png)
------------------
![edge4](https://user-images.githubusercontent.com/9059291/43445526-8210e0b0-949e-11e8-92db-b4851f691cfe.png)

## Steps to reproduce

1. Load the mulesoft example in edge [https://mulesoft.github.io/api-console/#/docs/summary](https://mulesoft.github.io/api-console/#/docs/summary)
2. Try to open some collapsed items in the menu on the left

## Was this working before?

- [ ] Yes, it was working before
- [ ] No, it was already broken
- [x] I don't know / not sure

## Affected browsers

- [ ] All or I don't know
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer <\3
- [x] Edge
- [ ] Safari
- [ ] Other (please, specify)

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report.
It looks like an issue in css variables polyfill or Edge. I need to investigate.
Next version of the console do not have this issue. The release is scheduled in coming weeks.

**Comment by jarrodek** [comment]
This is now fixed in version 6.0.0
