### ISSUE TITLE
Response headers not displaying all headers

### ISSUE THREAD

**Issue by saipran7777** [mulesoft/api-console#580]
Hi guys! I am new to `api-console`. I was using Postman earlier. In postman, I receive all the response headers which I can see through `Network` Tab in Debugger. But `api-console` shows only limited. Can anyone suggest me a solution for this?
![postman](https://user-images.githubusercontent.com/10899398/43714300-24fe9e16-999a-11e8-827b-d378871980a6.PNG)
![apiconsole](https://user-images.githubusercontent.com/10899398/43714307-2af8b96e-999a-11e8-9a9a-56cb2990a556.PNG)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.

API console has limited access to response headers. It is limited by the transport library [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest). It only allows limited number of headers to be read from the response. Especially if the request is made to another domain. Apparently in this case that's all what the console can read from the response object.

I can only suggest to install API console extension that do not have CORS (cross origin resource sharing) limitations but has to obey the same rules of getting response headers (which is limited by the spec). Install it from https://chrome.google.com/webstore/detail/api-console-extension/olkpohecoakpkpinafnpppponcfojioa

I am closing this issue as there's very little we can do in this case.
