### ISSUE TITLE
Does this support both RAML 0.8 and 1.0?

### ISSUE THREAD

**Issue by jimhooker2002** [mulesoft/api-console#585]
Is the latest version of the API console backwards compatible with the RAML 0.8 or will it only work with RAML 1.0? We are upgrading an old version of API console and have literally hundreds of 0.8 RAML documents.  We're trying to ensure that the latest version of the API console will still work with our older 0.8 documents.

**Comment by jarrodek** [comment]
Hi,

Thank you for asking. API console version 3.xx, 4.xx both support RAML 0.8 and 1.0 via [raml-js-parser-2](https://github.com/raml-org/raml-js-parser-2). Version 5.xx (in preview) support RAML 0.8, RAML 1.0 and OAS 2 via [AMF](https://github.com/aml-org/amf). Version 5 will be released in coming weeks.
