### ISSUE TITLE
The 'Try It' with basic authentication is not working as expected.

### ISSUE THREAD

**Issue by jerinconstant** [mulesoft/api-console#586]
While using the 'Try It' to hit any endpoint with Authorization method as 'Basic Authentication' gives request error. On further inspection it is found that the authorization header value is given as 'basic xxxxxxx=', but when manually changing this to 'Basic xxxxxxx=' the request goes through and provides the response. Is this a bug or is there something missing to make it work?

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report.
Can you tell which version of the console are you using?

**Comment by jerinconstant** [comment]
The api-console-cli 1.0.8 is used to build the console.

**Comment by jerinconstant** [comment]
@jarrodek please can you update on the issue.

**Comment by jarrodek** [comment]
Hi,
I tried to reproduce the issue and I was unable to. Latest pre-release is `v5.0.0-preview.3`. It seems to be working with this version.

**Comment by jerinconstant** [comment]
Thanks @jarrodek that seems to be working.
