### ISSUE TITLE
Tag Name

### ISSUE THREAD

**Issue by ben221199** [mulesoft/api-console#587]
Why do we have to give ``-n 5.0.0-preview-1`` if we want to succeed? Why does the client need to check every time if there is a new update? Why is it not simply possible to give a option like ``--forge`` to forge build the file, without checking for update?

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report.
API console is not yet released in version 5 which results with CLI/node build error. The console is to be released in coming days so there's no point to fix it now.

**Comment by jarrodek** [comment]
The console is finally released to stable version 5 so this issue won't happen again.
