### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by kroussevrb** [mulesoft/api-console#588]
How to fix this problem on a Mac?

**Comment by jarrodek** [comment]
Hi,
Thanks for issue report.
Do you know which version you are now using?

**Comment by kroussevrb** [comment]
I am using the following command, after having installed the utility using the recommended command in the github readme:

`api-console build -n "5.0.0-preview-1" -t "RAML 1.0" -a api_example.raml`

**Comment by jarrodek** [comment]
Great, so this is API Console version 5.
Any chance to share the API file with me that is causing the problem? This error is either caused by the API parser or by the builder. Our parser team is aware of similar issue when parsing some APIs.
If this is a problem with the builder I could try to debug it but essentially it uses Polymer build tools to create a bundle of web components so the issue would end up in the builder repository.

**Comment by kroussevrb** [comment]
Sure, this is the file I used https://github.com/raml-org/raml-examples/blob/master/schemas/api.raml

**Comment by jarrodek** [comment]
So I run into similar problem on Travis. I tracked this to memory use during the build process.
When the bundler creates the builds it can take up to 1,5GB for a brief moment (as much as I can see in my Activity Monitor app). Default node memory limit is 1GB on 64bit machines...

I don't see how this could be optimised right now. API console contains a lot of sources which are concatenated and then compiled during the build time. The actual build process is managed by Polymer's bundler library.

As a workaround I would suggest to set memory limit when running the command:
```
$ NODE_OPTIONS=--max_old_space_size=2048 api-console build -n "5.0.0-preview-1" -t "RAML 1.0" -a api.raml --verbose
```
or on Windows
```
set NODE_OPTIONS=--max_old_space_size=2048 api-console build -n "5.0.0-preview-1" -t "RAML 1.0" -a api.raml --verbose
```

This sets memory limit to 2GB. I know it might be inconvenient but I don't have other solution for now.

**Comment by kroussevrb** [comment]
Thanks, this has resolved the issue. Might be useful to add this to the repository readme file. The `--verbose` command is also very nice. 

Btw, this library is very unforgiving about syntax errors unlike raml2html which just silently ignores them and builds something (and that something might lack the part of the documentation which contained a syntax error) - but this is another matter, and probably intentional on your side.

**Comment by chrispytoes** [comment]
I am getting this error as well. I am using the same example file linked above: [https://github.com/raml-org/raml-examples/blob/master/schemas/api.raml](url)

I am on Windows, and I get an error when I run the command suggested above:
 `set NODE_OPTIONS=--max_old_space_size=2048 api-console build -n "5.0.0-preview-1" -t "RAML 1.0" -a api.raml --verbose`
error:
`Set-Variable : A positional parameter cannot be found that accepts argument 'api-console'.`

I also tried using `set NODE_OPTIONS=--max_old_space_size=2048` just by itself which seems to work, but it does not solve the issue and I still get the same error.

**Comment by wadeziegler** [comment]
> I am getting this error as well. I am using the same example file linked above: [https://github.com/raml-org/raml-examples/blob/master/schemas/api.raml](url)
> 
> I am on Windows, and I get an error when I run the command suggested above:
> `set NODE_OPTIONS=--max_old_space_size=2048 api-console build -n "5.0.0-preview-1" -t "RAML 1.0" -a api.raml --verbose`
> error:
> `Set-Variable : A positional parameter cannot be found that accepts argument 'api-console'.`
> 
> I also tried using `set NODE_OPTIONS=--max_old_space_size=2048` just by itself which seems to work, but it does not solve the issue and I still get the same error.

The example was not intended as one single command. Here are single line commands...

*Windows*
set NODE_OPTIONS=--max_old_space_size=2048 & api-console build -n "5.0.0-preview-1" -t "RAML 1.0" -a api.raml --verbose

*Linux*
export NODE_OPTIONS=--max_old_space_size=2048; api-console build -n "5.0.0-preview-1" -t "RAML 1.0" -a api.raml --verbose
