### ISSUE TITLE
webcomponents-hi.js.map missing

### ISSUE THREAD

**Issue by hubandr** [mulesoft/api-console#592]
When I try to load api-console, I'll get a webcomponents-hi.js.map error in webconsole of Firefox 64.0 on Ubuntu.
api-console was created without a raml file. I'm trying to load a json model from the same server as explained in "Passing API data":

<api-console model-location="static/api/api-model.json"></api-console>

affects api-console 5.x

**Comment by jarrodek** [comment]
Thank you for issue report. I will try to debug it.

**Comment by jarrodek** [comment]
Version 6.0.0 do not use it anymore.
