### ISSUE TITLE
Build fails with: Error Unable to find suitable version for api-console-default-theme

### ISSUE THREAD

**Issue by sajrashid** [mulesoft/api-console#599]
When running api-console build -n "5.0.0-preview-1" -t "RAML 1.0"  -a api.raml

I get 

error:
error: Unable to find suitable version for api-console-default-theme
error: api-console-default-theme: Unable to find suitable version for api-console-default-theme
    at createError 

I have ran bower install globally and locally

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report and sorry for late answer.
API Console is released in stable version so you can skip `-n` argument and install latest version when this is not happening.
