### ISSUE TITLE
Cannot link directly to a resource/method

### ISSUE THREAD

**Issue by rojoca** [mulesoft/api-console#60]
It would be useful to be able to send someone a link to a specific resource/method.

**Comment by AmShaegar13** [comment]
This is an essential feature. I am wondering why this is not included.

**Comment by ravikiranj** [comment]
Is there an event that gets published when RAML file is successfully parsed and UI load is complete. If yes, can someone point me to it. On this event callback, we can issue clicks to open a specific endpoint that lets us link endpoints using ```/doc#myendpoint```

**Comment by jcenturion** [comment]
Hi guys, this feature is in the backlog. We are figuring out how to create a non intrusive router for this  issue since there are other projects using API console embedded.

Sorry for not answering before.

**Comment by AmShaegar13** [comment]
Good to hear, thanks!

**Comment by ravikiranj** [comment]
@jcenturion as a temporarily fix, if I were to link users using ``/doc#endpoint```, is there any event I can subcribe to that indicates RAML UI loaded event ?

**Comment by ravikiranj** [comment]
Something like would totally work for now to be honest. I only need to figure out what event to subscribe to.
```
$('raml_load_complete').success(function() {
    var endpoint = window.location.hash.substr(1)
    , dom = document.querySelector( "#" + endpoint + " .raml-console-tab-list .raml-console-tab")
    ;
    if (dom) {
        dom.click();
    }
});

```

**Comment by jcenturion** [comment]
@ravikiranj: You should do that once the parser finishes at `ramlParserWrapper.onParseSuccess`.

**Comment by ravikiranj** [comment]
I'm not sure if this is pull request worthy but I'm pasting the patch here in case anyone else is looking to add permalinks with existing UI.

Patch: https://gist.github.com/ravikiranj/d525fc7a07f1339147ed
Demo URL: http://rkjanardhana.com/api-console-dist/#gists

**Comment by harry-wood** [comment]
I'm confused @jcenturion . Do you mean the anchor linking feature _was removed_ while you're "figuring out how to create a non intrusive router" ? 

We forked from this repo at a point in time when anchor linking was still working. After some extensive experimentation looking through the git history, it looks like it was working up until this commit: https://github.com/mulesoft/api-console/commit/902406b3a072b6c774f51d1d18674da35c628964 "Improve resource autofocus" Jul 2015

**Comment by ryansanford** [comment]
We ran into this limitation today. Is there any ETA on when this will be addressed?

**Comment by jcenturion** [comment]
@sichvoge Could you please take this question?

*Note: I'm not part of this team anymore. If you have any questions about this project please contact @sichvoge. Thanks.*

**Comment by harry-wood** [comment]
Unless I'm misunderstanding, the label on this should change. Despite the initial description, this is not enhancement idea. It's a thing which use to work, and was broken.

When it was broken this has somehow passed unnoticed for quite a while. I don't really understand how. Are we (TransportAPI) the only ones deploying raml console to our website, and using it for documentation? ...which we need to be able to link to! I mean anchor links to specific resources, is a basic feature of any API documentation site, used for example, when we're answering support queries about how to use our API.

Our documentation site is working fine with this at the moment. Example permalink URL: https://developer.transportapi.com/docs?raml=https://transportapi.com/v3/raml/transportapi.raml##uk_tube_stations_near_json  But that's only because we're running old api-console code from early 2015. We'd like to bring it up to date, but... this basic feature seems to have been accidentally removed.

Maybe it would be better if I create this as a new issue (?)

**Comment by jarrodek** [comment]
This feature is working on dev version of the API console.

**Comment by sichvoge** [comment]
@harry-wood I changed it to bug and we will try to fix it within our next iteration for the current version od the console (3.x.x).

**Comment by harry-wood** [comment]
@jarrodek When you say 'dev version', what do you mean exactly? I was just trying out 'develop' branch, which doesn't seem to have permalinking working. I also looked at 'release/4.0.0' branch, but this seems quite different. Is there lots of work happening on v4.0.0? where do I found out about that?

**Comment by jarrodek** [comment]
@harry-wood It is `release/4.0.0`. But the new console is a HTML element that you can use in an application that supports routing. It is now being documented but you can check https://www.npmjs.com/package/api-console-builder node module. If you won't set `mainFile` or `embedded` option it will generate a console as a standalone application  that support routing.

**Comment by sichvoge** [comment]
@harry-wood also see https://github.com/mulesoft/api-console/issues/328

**Comment by harry-wood** [comment]
Aha thanks. v4.0.0 looking pretty nice!

In relation to this issue, I notice on this v4.0.0 live demo site, that resource permalinks are working: http://mulesoft.github.io/api-console/#/docs/resources-2-resources-0

**Comment by sichvoge** [comment]
Perfect! Thanks for confirming that it fixes this issue. We are currently preparing the release which is planned for Monday atm.

**Comment by jarrodek** [comment]
PROUDLY: Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
