### ISSUE TITLE
Try it not sending requests in v5

### ISSUE THREAD

**Issue by dc950** [mulesoft/api-console#602]
When running the API-Console v5 as an embedded component, the "try it" functionality does not seem to be sending requests. It worked fine in v4. This happens in all browsers I try and test it in.

* When clicking "send" a loading circle appears and stays there forever. 
![2019-03-12 09_40_40-Documentation](https://user-images.githubusercontent.com/9059291/54190589-088c8000-44ac-11e9-914b-4feacbee77cb.png)
* Nothing is logged to the console.
* The URL is definitely correct - when copy-pasting it to postman it works.
* This happens when the URL is in the same domain as the portal is being hosted.
* No requests are received from the server the requests should be getting sent to.
* Viewing the "Network" tab in chrome developer tools shows no requests being made.

This was happening when embedding it (using `<api-console></api-console>`) and only setting the following configuration options: amf-model, base-uri, bower-location

**Comment by jarrodek** [comment]
Hi,
This part is missing updated documentation. 
When using console as an element then you also need to add `xhr-simple-request` and, if needed, `oauth2-authorization` and `oauth1-authorization` components.
They are not included into the console's sources so you also need to include them with:
```
<link rel="import" href="bower_components/xhr-simple-request/xhr-simple-request.html">
<link rel="import" href="bower_components/oauth-authorization/oauth2-authorization.html">
<link rel="import" href="bower_components/oauth-authorization/oauth1-authorization.html">
```
The reason for that is if you are already using own method of transporting the request or oauth authorization then this sources shouldn't be included into the web app for performance reason.

I will update the docs to include this information.

**Comment by dc950** [comment]
Yes, that was the issue. It works when I add that component
