### ISSUE TITLE
Array of union is not displayed properly

### ISSUE THREAD

**Issue by eNcacz** [mulesoft/api-console#608]
I have RAML file where each endpoint can return array of error objects. The set of possible error objects is defined as union type. It works well for one object or two objects in union but it does not work for three or more objects in union type, if the union is defined inplace.

Here is the simplified example RAML file:

```raml
#%RAML 1.0
title: Array of unions error demonstration
version: 1.0
mediaType: application/json

types:

  ErrorHolder:
    type: object
    properties:
      errors:
        type: object[]
      idCall:
        type: string

  Error1:
    type: object
    properties:
      fileName: string

  Error2:
    type: object
    properties:
      minValue: number
      maxValue: number

  Error3:
    type: object
    properties:
      code: string

  ErrAll: Error1 | Error2 | Error3

/e2:
  get:
    responses:
      406:
        body:
          type: ErrorHolder
          properties:
            errors: (Error1 | Error2)[]

/e3:
  get:
    responses:
      406:
        body:
          type: ErrorHolder
          properties:
            errors: (Error1 | Error2 | Error3)[]

/workaround:
  get:
    responses:
      406:
        body:
          type: ErrorHolder
          properties:
            errors: ErrAll[]
```

When I run api-console (version 1.0.13) then this error message appears in terminal:

```
warn: Model: file:///home/vaclav/develop/raml/tmp/dms.raml
Profile: RAML 1.0
Conforms? false
Number of results: 1

Level: Violation

- Source: http://a.ml/vocabularies/amf/parser#invalid-type-inheritance
  Message: Resolution error: Incompatible types [class amf.plugins.domain.shapes.models.UnionShape, class amf.plugins.domain.shapes.models.ArrayShape]
  Level: Violation
  Target: file:///home/vaclav/develop/raml/tmp/dms.raml#/web-api/end-points/%2Fe3/get/406/default/default/property/errors/union/default-union
  Property: http://a.ml/vocabularies/shapes#inherits
  Position: Some(LexicalInformation([(50,12)-(52,0)]))
  Location: file:///home/vaclav/develop/raml/tmp/dms.raml


API console build ready.
Thanks for using our API tools!
```
The created HTML then contains unwanted "UNNAMED TYPE" for `/e3` endpoint:

![image](https://user-images.githubusercontent.com/15668267/55482543-0b027580-5625-11e9-98a7-df3dc2db0283.png)

But for `/e2` endpoint it looks OK:

![image](https://user-images.githubusercontent.com/15668267/55482625-3be2aa80-5625-11e9-8ce0-2338955b565b.png)

When the union is created as named type (and not inplace) then all three objects are rendered properly and no error is produced during build. This is demonstrated by `/workaround` endpoint.

![image](https://user-images.githubusercontent.com/15668267/55482800-9419ac80-5625-11e9-8eac-9c36dfff2c08.png)

I expect the same behavior when the union is defined inplace.

**Comment by jarrodek** [comment]
This is now fixed in just released APIC 6.0.0
