### ISSUE TITLE
Oauth 1.0 base signature string is encoded with %2C (comma) instead of ampersand

### ISSUE THREAD

**Issue by authenticSam** [mulesoft/api-console#61]
this is causing signature not matching with other library trying to authenticate requests.
## Api-console

GET&http%3A%2F%2Flocalhost%3A8080%2Fimage-discovery-services%2Fapi%2Ftrs%2Fv1%2Fresolve%2Fsearch_movie&oauth_consumer_key%2Cc699a675ed4b813ca4c44d8feac3262a0a5ff67eb88b1c01b79db4dfec345b6b%2Coauth_nonce%2Cadc99bbfc7e15b2b53b5ec7e2250131b%2Coauth_signature_method%2CHMAC-SHA1%2Coauth_timestamp%2C1403222645%2Coauth_version%2C1.0%2Cw%2Cgladiator
## According to RFC 5849 

GET&http%3A%2F%2Flocalhost%3A8080%2Fimage-discovery-services%2Fapi%2Ftrs%2Fv1%2Fresolve%2Fsearch_movie&oauth_consumer_key%3Dc699a675ed4b813ca4c44d8feac3262a0a5ff67eb88b1c01b79db4dfec345b6b%26oauth_nonce%3Dc4e9dadd7baf72ea9d363d70adf273c3%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1403220735%26oauth_version%3D1.0%26w%3Dgladiator

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
