### ISSUE TITLE
Error message not shown in API Console standalone demo.

### ISSUE THREAD

**Issue by victorlev01** [mulesoft/api-console#621]
Hello, was using 6.0.0-preview api console, and not filled required fields in form demo/standalone:
![image](https://user-images.githubusercontent.com/18309707/69530793-46cbc000-0fa5-11ea-837b-9ce328a76b27.png)
**Authorization form not valid** message is hidden inside other div as it seems
![image](https://user-images.githubusercontent.com/18309707/69530984-aa55ed80-0fa5-11ea-858e-179490f78a30.png)
Issue can be reproduced on latest version running locally.
It seems it is related to paper-toast component

**Comment by victorlev01** [comment]
same for copy to clipboard when input is selected
![image](https://user-images.githubusercontent.com/18309707/69598653-97dac300-103c-11ea-8968-36c9ed3953ae.png)

**Comment by jarrodek** [comment]
Hi,

Thank you for reporting this issue.
I will look into this.

**Comment by jarrodek** [comment]
This has been fixed with 6.2.1 release (new authorization panel).
