### ISSUE TITLE
Wrong path for vendor.js

### ISSUE THREAD

**Issue by eNcacz** [mulesoft/api-console#624]
I use api-console@6.0.0 via api-console-cli@2.0.2

When I run 

```bash
api-console build -t "RAML 1.0" api.raml
```

then `build` directory is created with `index.html` and `vendor.js` (and some other) files.

The generated html application does not work (blank page is displayed) because the `vendor.js` is included in the `index.html` by this code:

```html
<script src="../vendor.js"></script>
```

If I remove two dots and slash before `vendor.js`, then it works as expected (the api console is displayed).

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report. I will fix it first thing tomorrow.

**Comment by jarrodek** [comment]
The CLI tool is now released.

**Comment by eNcacz** [comment]
I can confirm that it works well. 
Many thanks
