### ISSUE TITLE
Duplicate array decoration

### ISSUE THREAD

**Issue by eNcacz** [mulesoft/api-console#626]
Let's have this RAML file:

```raml
#%RAML 1.0
title: Example
version: 1.0

types:
  my-obj:
    type: object
    properties:
      attr1: string


/foo:
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              my-collection: my-obj[]
```

In the generated HTML there are two "Array" indicators as well as two green lines on the left side:

![image](https://user-images.githubusercontent.com/15668267/73957060-1d64d400-4906-11ea-98c0-26d6e9412643.png)

In previous version of API console (api-console-cli@1.0.13) there was only one array indicator as well as the left green line:

![image](https://user-images.githubusercontent.com/15668267/73957239-61f06f80-4906-11ea-85b0-22aaedf65b2d.png)

The old behavior better describes the response structure.

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report. I will take a look into this.

**Comment by jarrodek** [comment]
Hey @carowright 
Could you take a look into this issue? This is something with rendering with `api-type-documet` component. Not really sure where.
