### ISSUE TITLE
White Page - Opacity is set to 0 after the loader spinner is finished

### ISSUE THREAD

**Issue by aoe-aboross** [mulesoft/api-console#628]
We have the problem in all browsers on all operating systems that the transparency (opacity) remains set to 0 in the css body, after the spinner is finished.

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report. Can you tell me which version of the console are you using? We have recently released version 6 that support final WC specification. Previous version support deprecated (and already removed) previous specification of web components. It still can work but only if used with polyfills because the support for the components has to be emulated.

**Comment by aoe-aboross** [comment]
Hallo Pawel,
thanks for your feedback. Currently we use version cli version 1.0.14. with version 6

Best regards
Axel Boross

[cid:footer-logo]
Axel Boross
Development

Tel.: +49 2151 651 695 39
Fax: +49 2151 651 695 29

AOE GmbH
Girmesgath 5
47803 Krefeld
Germany

e-Mail: axel.boross@aoe.com<mailto:axel.boross@aoe.com>
Web: http://www.aoe.com<http://www.aoe.com/>

[cid:footer-omnichannel]<https://www.youtube.com/watch?v=x1u6v0_9IQE>
This e-mail message may contain confidential and/or privileged information. If you are not the
intended recipient (or have received this e-mail in error) please notify the sender immediately
and destroy this e-mail.
Legal Information<https://www.aoe.com/en/legal-information.html> / Privacy Policy<https://www.aoe.com/en/privacy-policy.html>

Von: Paweł Psztyć <notifications@github.com>
Antworten an: mulesoft/api-console <reply@reply.github.com>
Datum: Freitag, 14. Februar 2020 um 22:23
An: mulesoft/api-console <api-console@noreply.github.com>
Cc: Axel Boross <axel.boross@aoe.com>, Author <author@noreply.github.com>
Betreff: Re: [mulesoft/api-console] White Page - Opacity is set to 0 after the loader spinner is finished (#628)


Hi,
Thank you for the issue report. Can you tell me which version of the console are you using? We have recently released version 6 that support final WC specification. Previous version support deprecated (and already removed) previous specification of web components. It still can work but only if used with polyfills because the support for the components has to be emulated.

**Comment by jarrodek** [comment]
Hi Axel. Thank you for clarification.
I am still trying to understand what is happening. When you run the application the `unresolved` attribute is not removed from the `<body>`.  This was previously done by Polymer. Apparently after removing support for web components v0 it stopped working for some reason (but this logic is in Polymer).

The fastest way to walk around this is to upgrade to CLI 2.0.0 which uses API Console version 6. Your version of the CLI tool works with API Console version 5.

**Comment by aoe-aboross** [comment]
Hallo Pawel,
thanks for your quick feedback, you are welcome to close the ticket as resolved.
I will update the API Console. If the error still occurs, I will open a new ticket.

Thank you for your engagement in this project.
Axel Boross

[cid:footer-logo]
Axel Boross
Development

Tel.: +49 2151 651 695 39
Fax: +49 2151 651 695 29

AOE GmbH
Girmesgath 5
47803 Krefeld
Germany

e-Mail: axel.boross@aoe.com<mailto:axel.boross@aoe.com>
Web: http://www.aoe.com<http://www.aoe.com/>

[cid:footer-omnichannel]<https://www.youtube.com/watch?v=x1u6v0_9IQE>
This e-mail message may contain confidential and/or privileged information. If you are not the
intended recipient (or have received this e-mail in error) please notify the sender immediately
and destroy this e-mail.
Legal Information<https://www.aoe.com/en/legal-information.html> / Privacy Policy<https://www.aoe.com/en/privacy-policy.html>

Von: Paweł Psztyć <notifications@github.com>
Antworten an: mulesoft/api-console <reply@reply.github.com>
Datum: Mittwoch, 19. Februar 2020 um 02:04
An: mulesoft/api-console <api-console@noreply.github.com>
Cc: Axel Boross <axel.boross@aoe.com>, Author <author@noreply.github.com>
Betreff: Re: [mulesoft/api-console] White Page - Opacity is set to 0 after the loader spinner is finished (#628)


Hi Axel. Thank you for clarification.
I am still trying to understand what is happening. When you run the application the unresolved attribute is not removed from the <body>. This was previously done by Polymer. Apparently after removing support for web components v0 it stopped working for some reason (but this logic is in Polymer).

The fastest way to walk around this is to upgrade to CLI 2.0.0 which uses API Console version 6. Your version of the CLI tool works with API Console version 5.

**Comment by jarrodek** [comment]
Thank you for the update.
