### ISSUE TITLE
[Question] How do you specify API type and mime in `api-console-app`

### ISSUE THREAD

**Issue by dandew** [mulesoft/api-console#648]
When running the Docker image for API Console, it's possible to provide `API_TYPE` and `API_MIME`, and it works great 👍 

What is the equivalent when using `api-console-app` in `index.html`? I can see `modellocation` to point to my model file but how do I specify its type and mime?

**Comment by jarrodek** [comment]
Hi,
API Console does not processes "raw" API specs. This is done by the [AMF parser](https://github.com/aml-org/amf). The console is compatible with the output of the parser, which is a JSON representation of the web API model graph. Therefore the console has no logic that parses API files.

The workflow with the console is 1) generate the console sources; 2) generate AMI model via AMF parser; 3) copy the model to the location where `modellocation` points to.

It is better solution that parsing the API data in the browser as APIs can be extremely complex which requires final user resources (CPU, memory). We decided that model should be generated elsewhere (server, or precompiled model) so the browser doesn't need to do the heavy work. As a final result the console renders almost instantly (minus the time to download the model).

You can read more in our documentation: https://docs.api-console.io/basics/embedding-api-console/#passing-api-data-model

I am closing the issue as WAI but feel free to comment / reopen if necessary.
