### ISSUE TITLE
Parser is failing on description within response

### ISSUE THREAD

**Issue by egiraudy** [mulesoft/api-console#65]
According to the specification, a response may contain a description (see below), but the api-console parser fails when there is such an element.

From http://raml.org/spec.html:

/media/{mediaid}/content:
  displayName: Content
  get:
    description: |
      Get a media file.
    responses:
      200:
        body:
          "*/*":
            description: |
                Returns the media file.

Responses MAY contain a description property that further clarifies why the response was emitted. Response descriptions are particularly useful for describing error conditions.

**Comment by sichvoge** [comment]
That is definitely not valid RAML and I can't find the example in the spec anymore. Closing it for now
