### ISSUE TITLE
One Api-Console - several AMF JSON files

### ISSUE THREAD

**Issue by hubandr** [mulesoft/api-console#652]
Hello,

is there a simple way to have one api-console (generated by api-console-cli - build) and use it with several json (AMF) files which are specified as a URL param? 
I would like to generate only the "data" file with api-console-cli (generate-json) - after updating a RAML file - and not have to rebuild the whole api-console again.

Thanks
Andreas

**Comment by jarrodek** [comment]
Hi,
There is no mechanism like this in the console. This can be done, however, by creating a wrapper around the console. The console is a custom element and you can wrap it into your code so such a scenario would be supported. Take a look how our demo page for a standalone application is built: https://github.com/mulesoft/api-console/blob/master/demo/standalone/app.js#L35
You can pass an element to the toolbar (via `[slot=toolbar]`) and trigger this way any logic or an UI - like an API selector. THen to build a console you can follow instructions from this documentation: https://docs.api-console.io/building/rollup/
