### ISSUE TITLE
Unable to use Docker image

### ISSUE THREAD

**Issue by rohtakdev** [mulesoft/api-console#653]
I followed steps outlined here - https://docs.api-console.io/building/docker/

```
$ docker run    -it -p 8080:8080   -v "$PWD":/app/api   -e API_PROJECT="api.raml"   -e API_TYPE="RAML 1.0"   -e API_MIME="application/raml"   gcr.io/api-console-a6952/app:0.1.2

> apiconsole-docker@0.1.2 start /app
> node app.js

{"message":"Processing API file: /app/api-model.json /app","level":"info"}
{"message":"Running API parser for api.raml in /app/api","level":"info"}
{"message":"Running API parser for /app/api/api.raml","level":"info"}
App listening on port 8080
{"meta":{},"level":"info","message":"GET / 304 7ms"}
{"meta":{},"level":"info","message":"GET /api-console-import-d0dd2e7f.js 304 2ms"}
{"meta":{},"level":"info","message":"GET /vendor.js 304 1ms"}
{"meta":{},"level":"info","message":"GET /@anypoint-web-components/api-console/api-console-app.js 200 17ms"}
{"meta":{},"level":"info","message":"GET / 304 2ms"}
{"meta":{},"level":"info","message":"GET /api-console-import-d0dd2e7f.js 304 1ms"}
{"meta":{},"level":"info","message":"GET /vendor.js 304 1ms"}
{"meta":{},"level":"info","message":"GET /@anypoint-web-components/api-console/api-console-app.js 200 7ms"}
```

Then I opened http://localhost:8080 and got a blank page with below text in the developer console

```
Uncaught (in promise) TypeError: Failed to resolve module specifier "@anypoint-web-components/api-console/api-console-app.js". Relative references must start with either "/", "./", or "../".
```

Not sure what's wrong here.

**Comment by jarrodek** [comment]
Hi,
Sorry for the late response. I've been vacationing for some time.
Not entirely sure what is is about. It looks like the bundle in the docker image does not have properly compiled sources. What is the browser you are using?

**Comment by rohtakdev** [comment]
No worries, I am using below chrome version on Mac 10.13.6

Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by jarrodek** [comment]
Hi,
Sorry for taking it so long. It turned out to be a complex task involving upgrading API Console and its build process, then the build tooling around the console to finally update the docker image.
I just pushed the image with version `0.2.0`. It has the latest API Console, AMF parser, and latest build, which includes support for legacy browsers (when needed).
Closing this as fixed.
