### ISSUE TITLE
How to run api console with Angular 8

### ISSUE THREAD

**Issue by 4040** [mulesoft/api-console#664]
Hi,
Able to run demo project [https://github.com/mulesoft/api-console/](url)
So trying to run with angular 8 ,Created new angular project with below command
- ng create TestApiConsole
After that followed instruction from [https://docs.api-console.io/basics/embedding-api-console/](url)

- npm i --save api-console

- import 'api-console/api-console.js'; in app component ts

- Add selector in appcompent.html     **<api-console></api-console>**

code snapshot
![Untitled](https://user-images.githubusercontent.com/2510880/101290188-eea6db00-3800-11eb-94d4-f07ddd104075.png)

 am getting an error **api-console' is not a known element:**
![image](https://user-images.githubusercontent.com/2510880/101290202-02ead800-3801-11eb-9070-2cf05c9fc55b.png)

kindly assist if am missing any thing?
Thanks in advance

**Comment by jarrodek** [comment]
Hi,
Sorry for the late response.
I believe it is the Angular configuration issue. The error says to add some schema to NgModules.schema. I am not sure what this means as I stopped used Angular at version 2, years ago. Please, consult with Angular forum of how to run CutomElements inside an Angular project.

Regards.
