### ISSUE TITLE
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "oauth2-authorization" has already been used with this registry

### ISSUE THREAD

**Issue by back2arie** [mulesoft/api-console#667]
## Expected outcome
api-console run normally.

## Actual outcome
api-console cannot run normally (it show blank page) because of this error.

## Steps to reproduce
1. Build RAML & serve as follow (i'm using api-console-cli version 2.1.2):
```
$ api-console build -t "RAML 1.0" -a api.raml
$ api-console serve build/ --open
```
2. Open up browser & console show error:
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "oauth2-authorization" has already been used with this registry
```
3. After looking at the script i could see there is duplication, `oauth2-authorization` & `oauth1-authorization` defined twice:

Line 7919 (after formatted/ pretty print):
```
window.customElements.define("oauth2-authorization", QO),
window && (window.forceJURL = !0);
```

Line 46809:
```
window.customElements.define("oauth2-authorization", Bn);
```

Line 7421:
```
window.customElements.define("oauth1-authorization", Dn);
```
Line 47390:
```
window.customElements.define("oauth1-authorization", YO);
```

## Was this working before?

- [x] Yes, it was working before, i'm using version 1.0.14
- [ ] No, it was already broken
- [ ] I don't know / not sure

## Affected browsers (i just tested in chrome & safari)

- [ ] All or I don't know
- [x] Chrome 87.0
- [ ] Firefox
- [ ] Internet Explorer <\3
- [ ] Edge
- [x] Safari 11.1
- [ ] Other (please, specify)

**PS:** I've already tried to cleanup node_modules/, downgrade version to 2.0.0, but no luck, currently i'm just editing the id on the bundle js to avoid conflict & it resume normally.

**Comment by jarrodek** [comment]
@TwoPlusTwoOne apparently there's an issue with dependencies. Please, reinstall dependencies and remove package-lock.json file before that. Make sure that the demo page runs before publishing. Thanks.
