### ISSUE TITLE
Angular10/webpack: Uncaught SyntaxError: redeclaration of formal parameter module

### ISSUE THREAD

**Issue by dakli159** [mulesoft/api-console#668]
Uncaught SyntaxError: redeclaration of formal parameter module appears after import api-console/api-console.js to Angular10 component.

I am trying to use api-console as a web component in an Angular project.

## Expected outcome

The browser displays the page and the component without errors

## Actual outcome

Blank page.
Console shows "Uncaught SyntaxError: redeclaration of formal parameter module"

## Steps to reproduce

1. Create new Angular project with Angular-CLI
`ng new minimal`
2. Install api-console
`npm i --save api-console`
3. Import api-console to app.component.ts
`import { Component } from '@angular/core';
import 'api-console/api-console.js'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'minimal';
}`

4. compile and serve
`ng serve`

`ng serve` runs without errors.
http://localhost:4200 shows a blank page and the error message.

## Was this working before?

- [ ] Yes, it was working before
- [ ] No, it was already broken
- [x] I don't know / not sure

## Affected browsers

- [x] All or I don't know
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer <\3
- [ ] Edge
- [ ] Safari
- [ ] Other (please, specify)

I narrowed it down a bit:
The error appears after
import '@api-components/api-navigation/src/ApiNavigation.js'

This issue could be related to an issue of webpack:
[https://github.com/webpack/webpack/issues/7369](https://github.com/webpack/webpack/issues/7369)

The error only appears if the value "target" in tsconfig.json is "es2015"
Transpiled with "es5" runs without error.

**Comment by dakli159** [comment]
My output of ng --version:
```
Angular CLI: 10.1.7
Node: 12.16.1
OS: linux x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.3
typescript                      4.0.5

```

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report. I believe it is related to the other issues we recently have received and fixed involving re-declaration  of custom element. We have updated the console to fix this issue few days ago and we just finished updating build tools.
I am closing this as fixed.
