### ISSUE TITLE
Bad rendering of of multipart/form-data file example

### ISSUE THREAD

**Issue by egiraudy** [mulesoft/api-console#67]
Example file for a multipart/form-data file field is not rendered correctly:

``` json
body:
  multipart/form-data:
    formParameters:
      file:
        type: file
        example: !include example.json
```

is rendered this way:
![screen shot 2014-07-15 at 6 22 04 pm](https://cloud.githubusercontent.com/assets/666203/3593513/a38f8e1a-0c87-11e4-86e5-19e65692abf0.png)

when it should be rendered like any other example file:
![screen shot 2014-07-15 at 6 20 07 pm](https://cloud.githubusercontent.com/assets/666203/3593501/6abcd822-0c87-11e4-866c-6f0e2e2b1859.png)

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
