### ISSUE TITLE
AMF configuration issues

### ISSUE THREAD

**Issue by vickynrj** [mulesoft/api-console#674]
@jcenturion  @juancoen  @jarrodek 

Hi, I started fresh setup for api-console 
1- Checked out api-console version 6.3.6  
2- I have installed latest Nodejs an api-console-cli 
3- Installed dependencies with nmp i    Inside this path C:\Program Files (x86)\Apache Software Foundation\Apache2.2\htdocs\api-console-6.0.1
4- Created new raml api file  sample.raml  and kept it inside api-console-6.0.1 folder
5-  Now when I run   api-console build -t "RAML 1.0" sample.raml  build is not happening properly.

Is is because of AMF parser setting?  I saw the documentation about AMF parser
I referred this article https://docs.api-console.io/advanced/parsing-amf/ for AMF configuration

Ran  npm install --save amf-client-js
Then confused where to add import statement
import amf from 'amf-client-js';

I am trying to build api-console as standalone api.  Please help me in doing correct configuration of AMF so that I can get the build done

In older version 3.0.33  I was easily able to build api console and use that build anywhere to deploy.  It will be great help to all novice users if we have some demo video in Youtube for API console  basic setup. 

Thanks!

**Comment by jarrodek** [comment]
Hi,
Thank you for reaching out. I will try to help you with the problem.
The `api-console-cli` library bundles API Console so it can be used as a web application. You can then deploy it anywhere. It accepts an input parameter that points to the API file, and this file is parsed by AMF and included into the build as `api-model.json` file. The bundle points to this file when the application is loaded. The most basic usage is documented here: https://docs.api-console.io/building/cli/#building-api-console-application

The AMF library and the related documentation for API Console is targeted for cases when you have specific requirements to embedding API Console inside your application. You may embed the console in your web application and pass the AMF model manually. The majority of cases don't need these steps (I am not sure what is your end goal). 

If you would like to deploy a standalone API documentation application you can use our [docker image](https://docs.api-console.io/building/docker/#docker-image-and-kubernetes) or [build the application](https://docs.api-console.io/building/cli/#building-api-console-application) from sources. For more customized build process I prepared [these docs](https://docs.api-console.io/building/rollup/#rollup-configuration) of how to configure Rollup to build the console.

Please, let me know if I can be more of a help.
