### ISSUE TITLE
Scroll of method content does not work in Safari and old Chrome and Firefox

### ISSUE THREAD

**Issue by tuler** [mulesoft/api-console#68]
When you open a method documentation, and it's too long, the scrolling does not work.

**Comment by jcenturion** [comment]
@maryoush, @meeque: The new version is now on master. Most of the CSS issues should be fixed, if not just let us know.

Thanks!

**Comment by meeque** [comment]
Took us some while to get around to this, but now I finally upgraded our service SDK (and some of our services) to the new version. Looks pretty good so far. Thanks for your work!
