### ISSUE TITLE
SecurityScheme description not displayed

### ISSUE THREAD

**Issue by Philzen** [mulesoft/api-console#70]
The [RAML spec v0.8 allows](http://raml.org/spec.html#toc_64) for a `description` on each security scheme.

Unfortunately, this is not reflected in the api-console when selecting an Authentication mode. 

On some APIs the actual required values are not implicit when looking at a standard authentication type (i.e. in the [Parse API](https://parse.com/docs/rest#general-requests)), thus i believe it will be quite useful to display the `description` value.

Actually: Building on the parse api example, it would be even more favorable to also have an ability to provide descriptions on the expected input parameters, i.e. defining more exactly what an API expects for  `username` and `password` in a BasicAuth-Scheme. Not sure - is that possible with RAML v0.8 at all?

**Comment by jcenturion** [comment]
@Philzen: In the latest version you can see the security scheme documentation.

![screen shot 2015-03-11 at 5 52 56 pm](https://cloud.githubusercontent.com/assets/302314/6622306/14fe6eea-c899-11e4-829f-b46be0190fc1.png)

**Comment by ddossot** [comment]
I'm super happy to confirm this works perfectly :clap:

**Comment by Philzen** [comment]
Awesome, thanks!
