### ISSUE TITLE
[CHANGE REQUEST] Keyboard Shortcut CTRL-Delete

### ISSUE THREAD

**Issue by Philzen** [mulesoft/api-console#71]
Really happy getting my api accessible via console, having the full code completion features available is quite nice, however i find myself deleting whole code blocks without intent while just wanting to delete the last word when i hit `CTRL+BACKSPACE`. 

For one, technically this is a different from `CTRL+DELETE`. 
For worse, it breaks consistent user experience (I heavily rely on this "move" ;) and basically have been relying blindly on it for years) - whereever there's a gui notepad, office document editor, code IDEs, address bar urls and _most importantly_ Text-Boxes on HTML WebForms all behave this way; no matter whether on Windows or KDE

**Comment by sichvoge** [comment]
Are you talking about the API Designer or the editor that is shipped with the standalone version of the console?
