### ISSUE TITLE
Query string parameters getting stripped by api-console?

### ISSUE THREAD

**Issue by tobinmori** [mulesoft/api-console#72]
I have api-console running on the same box as an NGINX proxy server (which proxies our APIs to circumvent CORS issues).

The 'Try It' feature works fine. . .

*unless* I pass a URL to the proxy with query params. It appears that the query params are getting stripped out by api-console because the 'Request URL' under 'Response' shows with the query params stripped out. Of course, this results in a 404. . .

oh yes, NGINX is setup to forward along query params. . .

**Comment by jcenturion** [comment]
@tobinmori, is this still happening on the latest version?

**Comment by ddossot** [comment]
@jcenturion I've just tested the latest version and I can see that the console correctly sends requests with the query parameters I've selected. AFAIAC this works fine.

**Comment by jcenturion** [comment]
Great, I will close this issue.
