### ISSUE TITLE
configurable/hide anonymous option in try_it.

### ISSUE THREAD

**Issue by hadesbox** [mulesoft/api-console#80]
Currently, if your API ONLY supports authenticated calls (and not anonymous) you are still shown on the API Console this option on the try it section, and this is misleading to developers using the console.

This is because in app/views/security_schemes.tmpl.html the line 8
```
      <toggle-item heading="Anonymous"></toggle-item>
```
is hard coded to always show anonymous regardless of API configuration, and the only way to disable this is deleting the line on the source code... this should be configurable or it should be shown only when NO security (secure_by) is defined for the service.

**Comment by jbocharov** [comment]
The option to disable anonymous would be extremely useful. Many of my developers are being led astray by the option (which will never work on my API) on the first-use experience, and I look to the console to help users make valid requests as they're getting familiar. There are many other ways (curl, Postman, etc) to generate an invalid request to see what would happen.

**Comment by jcenturion** [comment]
@jbocharov:  the latest version of the console will allow you to use Anonymous requests:

- when securedBy contains a null value in the list

```yaml
/teams:
  post:
    securedBy: [ null, oauth_2_0]
```

- when no security scheme is applied to method level nor api level
