### ISSUE TITLE
No scrollbar on "Try It tab" after executing call (Firefox 34+)

### ISSUE THREAD

**Issue by brycebudd** [mulesoft/api-console#87]
When I open the api console in Firefox 34+ (linux or windows) and execute a resource call in the "Try It" tab, I get a successful response, but the payload in the body section is hidden and no scrollbar appears to view the response body.  It no longer dynamically resizes.  This problem is not present in Firefox 33.1.1 or any Chrome version.  It appears to only affect users of Firefox 34+.

**Comment by antoine-richard** [comment]
It appears to affects all of the pages which are too high (request, response...).

I think it's related to the [FF34 flexbox changes](https://developer.mozilla.org/en-US/Firefox/Releases/34/Site_Compatibility#CSS).

**Comment by antoine-richard** [comment]
Pull request proposal: https://github.com/mulesoft/api-console/pull/89

**Comment by jcenturion** [comment]
@brycebudd: Have you had the chance to try the new version?

**Comment by ddossot** [comment]
FTR the latest works fine with Firefox 35.0.1 on Ubuntu 14.04.

**Comment by carowright** [comment]
I am closing this as is not reproducible anymore using the latest version (v3.0.26).
